/*
 * CCT — Clavicula Turing
 * Object storage runtime helper emission
 *
 * FASE 40C: cct/object_storage host-runtime bridge
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "runtime.h"

bool cct_runtime_emit_object_storage_helpers(FILE *out) {
    if (!out) return false;

#define EMIT(line) fputs(line "\n", out)

    EMIT("typedef struct {");
    EMIT("    char *endpoint;");
    EMIT("    char *root_dir;");
    EMIT("    char *bucket;");
    EMIT("    char *access_key;");
    EMIT("    char *secret_key;");
    EMIT("    char *region;");
    EMIT("    int use_tls;");
    EMIT("} cct_rt_obj_client_t;");
    EMIT("");
    EMIT("static char cct_rt_obj_last_error_buf[512];");
    EMIT("static char cct_rt_obj_last_content_type[256];");
    EMIT("static char cct_rt_obj_last_etag[128];");
    EMIT("static char cct_rt_obj_last_signed_expires_at[64];");
    EMIT("static long long cct_rt_obj_last_size_value = 0LL;");
    EMIT("");
    EMIT("static void cct_rt_obj_copy_text(char *dst, size_t cap, const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    if (cap == 0u) return;");
    EMIT("    if (n >= cap) n = cap - 1u;");
    EMIT("    memcpy(dst, text, n);");
    EMIT("    dst[n] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_dup_cstr(const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);");
    EMIT("    memcpy(out_s, text, n + 1u);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_obj_set_error(const char *msg) {");
    EMIT("    cct_rt_obj_copy_text(cct_rt_obj_last_error_buf, sizeof(cct_rt_obj_last_error_buf), msg);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_obj_clear_error(void) {");
    EMIT("    cct_rt_obj_last_error_buf[0] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_obj_clear_last_meta(void) {");
    EMIT("    cct_rt_obj_last_content_type[0] = '\\0';");
    EMIT("    cct_rt_obj_last_etag[0] = '\\0';");
    EMIT("    cct_rt_obj_last_signed_expires_at[0] = '\\0';");
    EMIT("    cct_rt_obj_last_size_value = 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_last_error(void) { return cct_rt_obj_dup_cstr(cct_rt_obj_last_error_buf); }");
    EMIT("static char *cct_rt_obj_last_content_type_value(void) { return cct_rt_obj_dup_cstr(cct_rt_obj_last_content_type); }");
    EMIT("static char *cct_rt_obj_last_etag_value(void) { return cct_rt_obj_dup_cstr(cct_rt_obj_last_etag); }");
    EMIT("static long long cct_rt_obj_last_size(void) { return cct_rt_obj_last_size_value; }");
    EMIT("static char *cct_rt_obj_last_signed_expires_at_value(void) { return cct_rt_obj_dup_cstr(cct_rt_obj_last_signed_expires_at); }");
    EMIT("");
    EMIT("static int cct_rt_obj_has_segment(const char *name, const char *segment) {");
    EMIT("    const char *start = name;");
    EMIT("    const char *slash = NULL;");
    EMIT("    size_t seg_len = strlen(segment);");
    EMIT("    if (!name || !segment) return 0;");
    EMIT("    while (*start) {");
    EMIT("        slash = strchr(start, '/');");
    EMIT("        size_t part_len = slash ? (size_t)(slash - start) : strlen(start);");
    EMIT("        if (part_len == seg_len && memcmp(start, segment, seg_len) == 0) return 1;");
    EMIT("        if (!slash) break;");
    EMIT("        start = slash + 1;");
    EMIT("    }");
    EMIT("    return 0;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_obj_validate_key(const char *key) {");
    EMIT("    size_t len = key ? strlen(key) : 0u;");
    EMIT("    if (!key || len == 0u) { cct_rt_obj_set_error(\"object_storage: key ausente\"); return 0; }");
    EMIT("    if (key[0] == '/' || key[0] == '\\\\') { cct_rt_obj_set_error(\"object_storage: key absoluto rejeitado\"); return 0; }");
    EMIT("    if (strchr(key, '\\\\')) { cct_rt_obj_set_error(\"object_storage: key com barra invertida rejeitado\"); return 0; }");
    EMIT("    if (len >= 2u && isalpha((unsigned char)key[0]) && key[1] == ':') { cct_rt_obj_set_error(\"object_storage: key com drive absoluto rejeitado\"); return 0; }");
    EMIT("    if (cct_rt_obj_has_segment(key, \"..\") || cct_rt_obj_has_segment(key, \".\")) { cct_rt_obj_set_error(\"object_storage: key com path traversal rejeitado\"); return 0; }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_join2(const char *a, const char *b) {");
    EMIT("    size_t alen = strlen(a ? a : \"\");");
    EMIT("    size_t blen = strlen(b ? b : \"\");");
    EMIT("    int need_sep = (alen > 0u && a[alen - 1u] != '/');");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(alen + (need_sep ? 1u : 0u) + blen + 1u);");
    EMIT("    memcpy(out_s, a ? a : \"\", alen);");
    EMIT("    if (need_sep) out_s[alen++] = '/';");
    EMIT("    memcpy(out_s + alen, b ? b : \"\", blen);");
    EMIT("    out_s[alen + blen] = '\\0';");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_parent_dir(const char *path) {");
    EMIT("    const char *slash = strrchr(path ? path : \"\", '/');");
    EMIT("    char *out_s = NULL;");
    EMIT("    size_t len = 0u;");
    EMIT("    if (!slash) return cct_rt_obj_dup_cstr(\"\");");
    EMIT("    len = (size_t)(slash - path);");
    EMIT("    out_s = (char*)cct_rt_alloc_or_fail(len + 1u);");
    EMIT("    memcpy(out_s, path, len);");
    EMIT("    out_s[len] = '\\0';");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_meta_path(const char *object_path) {");
    EMIT("    size_t len = strlen(object_path ? object_path : \"\");");
    EMIT("    const char *suffix = \".cctobjmeta\";");
    EMIT("    size_t slen = strlen(suffix);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(len + slen + 1u);");
    EMIT("    memcpy(out_s, object_path ? object_path : \"\", len);");
    EMIT("    memcpy(out_s + len, suffix, slen + 1u);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_digest_bytes(const unsigned char *data, size_t len) {");
    EMIT("    EVP_MD_CTX *ctx = NULL;");
    EMIT("    unsigned char digest[EVP_MAX_MD_SIZE];");
    EMIT("    unsigned int digest_len = 0u;");
    EMIT("    char hex[EVP_MAX_MD_SIZE * 2 + 1];");
    EMIT("    char *out_s = NULL;");
    EMIT("    size_t i = 0u;");
    EMIT("    ctx = EVP_MD_CTX_new();");
    EMIT("    if (!ctx) return cct_rt_obj_dup_cstr(\"\");");
    EMIT("    if (EVP_DigestInit_ex(ctx, EVP_sha256(), NULL) != 1) { EVP_MD_CTX_free(ctx); return cct_rt_obj_dup_cstr(\"\"); }");
    EMIT("    if (EVP_DigestUpdate(ctx, data ? data : (const unsigned char*)\"\", len) != 1) { EVP_MD_CTX_free(ctx); return cct_rt_obj_dup_cstr(\"\"); }");
    EMIT("    if (EVP_DigestFinal_ex(ctx, digest, &digest_len) != 1) { EVP_MD_CTX_free(ctx); return cct_rt_obj_dup_cstr(\"\"); }");
    EMIT("    EVP_MD_CTX_free(ctx);");
    EMIT("    for (i = 0u; i < (size_t)digest_len; i++) snprintf(hex + (i * 2u), 3u, \"%02x\", digest[i]);");
    EMIT("    hex[(size_t)digest_len * 2u] = '\\0';");
    EMIT("    out_s = cct_rt_obj_dup_cstr(hex);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_obj_write_meta(const char *meta_path, const char *content_type, const char *etag, long long size) {");
    EMIT("    FILE *fp = fopen(meta_path, \"wb\");");
    EMIT("    if (!fp) return 0;");
    EMIT("    fprintf(fp, \"%s\\n%s\\n%lld\\n\", content_type ? content_type : \"\", etag ? etag : \"\", size);");
    EMIT("    fclose(fp);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_obj_read_meta(const char *meta_path, char *content_type, size_t ct_cap, char *etag, size_t etag_cap, long long *size) {");
    EMIT("    FILE *fp = fopen(meta_path, \"rb\");");
    EMIT("    char line[512];");
    EMIT("    if (!fp) return 0;");
    EMIT("    if (!fgets(line, sizeof(line), fp)) { fclose(fp); return 0; }");
    EMIT("    line[strcspn(line, \"\\r\\n\")] = '\\0';");
    EMIT("    cct_rt_obj_copy_text(content_type, ct_cap, line);");
    EMIT("    if (!fgets(line, sizeof(line), fp)) { fclose(fp); return 0; }");
    EMIT("    line[strcspn(line, \"\\r\\n\")] = '\\0';");
    EMIT("    cct_rt_obj_copy_text(etag, etag_cap, line);");
    EMIT("    if (!fgets(line, sizeof(line), fp)) { fclose(fp); return 0; }");
    EMIT("    *size = atoll(line);");
    EMIT("    fclose(fp);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static void *cct_rt_obj_open(const char *endpoint, const char *bucket, const char *access_key, const char *secret_key, const char *region, long long use_tls) {");
    EMIT("    cct_rt_obj_client_t *client = NULL;");
    EMIT("    const char *root = NULL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    cct_rt_obj_clear_last_meta();");
    EMIT("    if (!endpoint || !*endpoint) { cct_rt_obj_set_error(\"object_storage: endpoint ausente\"); return NULL; }");
    EMIT("    if (!bucket || !*bucket) { cct_rt_obj_set_error(\"object_storage: bucket ausente\"); return NULL; }");
    EMIT("    if (strncmp(endpoint, \"file://\", 7u) == 0) root = endpoint + 7;");
    EMIT("    else if (strncmp(endpoint, \"fs://\", 5u) == 0) root = endpoint + 5;");
    EMIT("    else if (endpoint[0] == '/') root = endpoint;");
    EMIT("    else { cct_rt_obj_set_error(\"object_storage: runtime atual suporta endpoint local file:// ou fs://\"); return NULL; }");
    EMIT("    client = (cct_rt_obj_client_t*)cct_rt_alloc_or_fail(sizeof(cct_rt_obj_client_t));");
    EMIT("    memset(client, 0, sizeof(*client));");
    EMIT("    client->endpoint = cct_rt_obj_dup_cstr(endpoint);");
    EMIT("    client->root_dir = cct_rt_obj_dup_cstr(root);");
    EMIT("    client->bucket = cct_rt_obj_dup_cstr(bucket);");
    EMIT("    client->access_key = cct_rt_obj_dup_cstr(access_key ? access_key : \"\");");
    EMIT("    client->secret_key = cct_rt_obj_dup_cstr(secret_key ? secret_key : \"\");");
    EMIT("    client->region = cct_rt_obj_dup_cstr(region ? region : \"us-east-1\");");
    EMIT("    client->use_tls = use_tls ? 1 : 0;");
    EMIT("    { char *bucket_dir = cct_rt_obj_join2(client->root_dir, client->bucket); cct_rt_fs_mkdir_all(bucket_dir); cct_rt_free_ptr(bucket_dir); }");
    EMIT("    return client;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_obj_close(void *ptr) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    if (!client) return;");
    EMIT("    if (client->endpoint) cct_rt_free_ptr(client->endpoint);");
    EMIT("    if (client->root_dir) cct_rt_free_ptr(client->root_dir);");
    EMIT("    if (client->bucket) cct_rt_free_ptr(client->bucket);");
    EMIT("    if (client->access_key) cct_rt_free_ptr(client->access_key);");
    EMIT("    if (client->secret_key) cct_rt_free_ptr(client->secret_key);");
    EMIT("    if (client->region) cct_rt_free_ptr(client->region);");
    EMIT("    cct_rt_free_ptr(client);");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_object_path(cct_rt_obj_client_t *client, const char *key) {");
    EMIT("    char *bucket_dir = cct_rt_obj_join2(client->root_dir, client->bucket);");
    EMIT("    char *object_path = cct_rt_obj_join2(bucket_dir, key);");
    EMIT("    cct_rt_free_ptr(bucket_dir);");
    EMIT("    return object_path;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_obj_store_bytes(cct_rt_obj_client_t *client, const char *key, const unsigned char *data, size_t len, const char *content_type) {");
    EMIT("    char *object_path = NULL;");
    EMIT("    char *parent = NULL;");
    EMIT("    char *meta_path = NULL;");
    EMIT("    char *etag = NULL;");
    EMIT("    FILE *fp = NULL;");
    EMIT("    if (!client || !cct_rt_obj_validate_key(key)) return 0;");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    parent = cct_rt_obj_parent_dir(object_path);");
    EMIT("    if (parent[0] != '\\0') cct_rt_fs_mkdir_all(parent);");
    EMIT("    fp = fopen(object_path, \"wb\");");
    EMIT("    if (!fp) { cct_rt_free_ptr(parent); cct_rt_free_ptr(object_path); cct_rt_obj_set_error(\"object_storage: falha ao criar objeto\"); return 0; }");
    EMIT("    if (len > 0u && fwrite(data, 1u, len, fp) != len) { fclose(fp); cct_rt_free_ptr(parent); cct_rt_free_ptr(object_path); cct_rt_obj_set_error(\"object_storage: falha ao escrever objeto\"); return 0; }");
    EMIT("    fclose(fp);");
    EMIT("    etag = cct_rt_obj_digest_bytes(data, len);");
    EMIT("    meta_path = cct_rt_obj_meta_path(object_path);");
    EMIT("    if (!cct_rt_obj_write_meta(meta_path, content_type ? content_type : \"application/octet-stream\", etag, (long long)len)) {");
    EMIT("        cct_rt_free_ptr(etag);");
    EMIT("        cct_rt_free_ptr(meta_path);");
    EMIT("        cct_rt_free_ptr(parent);");
    EMIT("        cct_rt_free_ptr(object_path);");
    EMIT("        cct_rt_obj_set_error(\"object_storage: falha ao escrever metadata do objeto\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    cct_rt_obj_copy_text(cct_rt_obj_last_content_type, sizeof(cct_rt_obj_last_content_type), content_type ? content_type : \"application/octet-stream\");");
    EMIT("    cct_rt_obj_copy_text(cct_rt_obj_last_etag, sizeof(cct_rt_obj_last_etag), etag);");
    EMIT("    cct_rt_obj_last_size_value = (long long)len;");
    EMIT("    cct_rt_free_ptr(etag);");
    EMIT("    cct_rt_free_ptr(meta_path);");
    EMIT("    cct_rt_free_ptr(parent);");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_put_text(void *ptr, const char *key, const char *content, const char *content_type) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    const unsigned char *data = (const unsigned char*)(content ? content : \"\");");
    EMIT("    size_t len = strlen((const char*)data);");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    cct_rt_obj_clear_last_meta();");
    EMIT("    return cct_rt_obj_store_bytes(client, key, data, len, content_type);");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_put_file(void *ptr, const char *key, const char *source_path, const char *content_type) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    FILE *fp = NULL;");
    EMIT("    long size = 0L;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    cct_rt_obj_clear_last_meta();");
    EMIT("    if (!source_path || !*source_path) { cct_rt_obj_set_error(\"object_storage: source_path ausente\"); return 0LL; }");
    EMIT("    fp = fopen(source_path, \"rb\");");
    EMIT("    if (!fp) { cct_rt_obj_set_error(\"object_storage: source_path inexistente\"); return 0LL; }");
    EMIT("    if (fseek(fp, 0L, SEEK_END) != 0) { fclose(fp); cct_rt_obj_set_error(\"object_storage: falha ao medir arquivo\"); return 0LL; }");
    EMIT("    size = ftell(fp);");
    EMIT("    if (size < 0L) { fclose(fp); cct_rt_obj_set_error(\"object_storage: falha ao medir arquivo\"); return 0LL; }");
    EMIT("    if (fseek(fp, 0L, SEEK_SET) != 0) { fclose(fp); cct_rt_obj_set_error(\"object_storage: falha ao reposicionar arquivo\"); return 0LL; }");
    EMIT("    data = (unsigned char*)cct_rt_alloc_or_fail((size_t)size + 1u);");
    EMIT("    if ((size_t)size > 0u && fread(data, 1u, (size_t)size, fp) != (size_t)size) { cct_rt_free_ptr(data); fclose(fp); cct_rt_obj_set_error(\"object_storage: falha ao ler arquivo\"); return 0LL; }");
    EMIT("    fclose(fp);");
    EMIT("    if (!cct_rt_obj_store_bytes(client, key, data, (size_t)size, content_type)) { cct_rt_free_ptr(data); return 0LL; }");
    EMIT("    cct_rt_free_ptr(data);");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_get_to_file(void *ptr, const char *key, const char *dest_path) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    char *object_path = NULL;");
    EMIT("    char *parent = NULL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    if (!client || !dest_path || !*dest_path || !cct_rt_obj_validate_key(key)) return 0LL;");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    if (!cct_rt_fs_exists(object_path)) { cct_rt_free_ptr(object_path); cct_rt_obj_set_error(\"object_storage: objeto inexistente\"); return 0LL; }");
    EMIT("    parent = cct_rt_obj_parent_dir(dest_path);");
    EMIT("    if (parent[0] != '\\0') cct_rt_fs_mkdir_all(parent);");
    EMIT("    cct_rt_fs_copy(object_path, dest_path);");
    EMIT("    cct_rt_free_ptr(parent);");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_exists(void *ptr, const char *key) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    char *object_path = NULL;");
    EMIT("    long long exists = 0LL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    if (!client || !cct_rt_obj_validate_key(key)) return -1LL;");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    exists = cct_rt_fs_exists(object_path) ? 1LL : 0LL;");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return exists;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_head(void *ptr, const char *key) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    char *object_path = NULL;");
    EMIT("    char *meta_path = NULL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    cct_rt_obj_clear_last_meta();");
    EMIT("    if (!client || !cct_rt_obj_validate_key(key)) return 0LL;");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    if (!cct_rt_fs_exists(object_path)) { cct_rt_free_ptr(object_path); cct_rt_obj_set_error(\"object_storage: objeto inexistente\"); return 0LL; }");
    EMIT("    meta_path = cct_rt_obj_meta_path(object_path);");
    EMIT("    if (!cct_rt_obj_read_meta(meta_path, cct_rt_obj_last_content_type, sizeof(cct_rt_obj_last_content_type), cct_rt_obj_last_etag, sizeof(cct_rt_obj_last_etag), &cct_rt_obj_last_size_value)) {");
    EMIT("        cct_rt_free_ptr(meta_path);");
    EMIT("        cct_rt_free_ptr(object_path);");
    EMIT("        cct_rt_obj_set_error(\"object_storage: metadata do objeto ausente ou invalida\");");
    EMIT("        return 0LL;");
    EMIT("    }");
    EMIT("    cct_rt_free_ptr(meta_path);");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_obj_delete(void *ptr, const char *key) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    char *object_path = NULL;");
    EMIT("    char *meta_path = NULL;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    if (!client || !cct_rt_obj_validate_key(key)) return 0LL;");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    meta_path = cct_rt_obj_meta_path(object_path);");
    EMIT("    if (cct_rt_fs_exists(object_path)) remove(object_path);");
    EMIT("    if (cct_rt_fs_exists(meta_path)) remove(meta_path);");
    EMIT("    cct_rt_free_ptr(meta_path);");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_obj_signed_url(void *ptr, const char *key, long long ttl_seconds) {");
    EMIT("    cct_rt_obj_client_t *client = (cct_rt_obj_client_t*)ptr;");
    EMIT("    char *object_path = NULL;");
    EMIT("    char *url = NULL;");
    EMIT("    time_t now = time(NULL);");
    EMIT("    time_t exp = now + (ttl_seconds > 0 ? ttl_seconds : 0LL);");
    EMIT("    struct tm tm_utc;");
    EMIT("    cct_rt_obj_clear_error();");
    EMIT("    cct_rt_obj_last_signed_expires_at[0] = '\\0';");
    EMIT("    if (!client || !cct_rt_obj_validate_key(key)) return cct_rt_obj_dup_cstr(\"\");");
    EMIT("    object_path = cct_rt_obj_object_path(client, key);");
    EMIT("    if (!cct_rt_fs_exists(object_path)) { cct_rt_free_ptr(object_path); cct_rt_obj_set_error(\"object_storage: objeto inexistente\"); return cct_rt_obj_dup_cstr(\"\"); }");
    EMIT("#ifdef _WIN32");
    EMIT("    gmtime_s(&tm_utc, &exp);");
    EMIT("#else");
    EMIT("    gmtime_r(&exp, &tm_utc);");
    EMIT("#endif");
    EMIT("    strftime(cct_rt_obj_last_signed_expires_at, sizeof(cct_rt_obj_last_signed_expires_at), \"%Y-%m-%dT%H:%M:%SZ\", &tm_utc);");
    EMIT("    {");
    EMIT("        const char *prefix = \"file://\";");
    EMIT("        const char *path = object_path;");
    EMIT("        char ttl_buf[32];");
    EMIT("        snprintf(ttl_buf, sizeof(ttl_buf), \"%lld\", ttl_seconds);");
    EMIT("        url = (char*)cct_rt_alloc_or_fail(strlen(prefix) + strlen(path) + strlen(\"?bucket=&key=&expires=&ttl=\") + strlen(client->bucket) + strlen(key) + strlen(cct_rt_obj_last_signed_expires_at) + strlen(ttl_buf) + 1u);");
    EMIT("        sprintf(url, \"%s%s?bucket=%s&key=%s&expires=%s&ttl=%s\", prefix, path, client->bucket, key, cct_rt_obj_last_signed_expires_at, ttl_buf);");
    EMIT("    }");
    EMIT("    cct_rt_free_ptr(object_path);");
    EMIT("    return url;");
    EMIT("}");

#undef EMIT
    return true;
}
