/*
 * CCT — Clavicula Turing
 * SMTP runtime helper emission
 *
 * FASE 37A: cct/mail host-runtime bridge
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "runtime.h"

bool cct_runtime_emit_mail_helpers(FILE *out) {
    if (!out) return false;

#define EMIT(line) fputs(line "\n", out)

    EMIT("#ifdef _WIN32");
    EMIT("static char *cct_rt_mail_smtp_send(const char *host, long long port, const char *username, const char *password, long long auth_kind, long long use_starttls, long long use_smtps, const char *mail_from, const char *rcpts_text, const char *mime_text) {");
    EMIT("    (void)host; (void)port; (void)username; (void)password; (void)auth_kind; (void)use_starttls; (void)use_smtps; (void)mail_from; (void)rcpts_text; (void)mime_text;");
    EMIT("    const char *msg = \"SMTP host runtime indisponivel neste target\";");
    EMIT("    size_t n = strlen(msg);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1U);");
    EMIT("    memcpy(out_s, msg, n + 1U);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("#else");
    EMIT("typedef struct {");
    EMIT("    int fd;");
    EMIT("    int use_tls;");
    EMIT("    SSL_CTX *ssl_ctx;");
    EMIT("    SSL *ssl;");
    EMIT("    char last_error[512];");
    EMIT("} cct_rt_mail_conn_t;");
    EMIT("");
    EMIT("static void cct_rt_mail_copy_error(char *dst, size_t cap, const char *msg) {");
    EMIT("    const char *src = msg ? msg : \"\";");
    EMIT("    size_t n = strlen(src);");
    EMIT("    if (cap == 0) return;");
    EMIT("    if (n >= cap) n = cap - 1U;");
    EMIT("    memcpy(dst, src, n);");
    EMIT("    dst[n] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_mail_dup_cstr(const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1U);");
    EMIT("    memcpy(out_s, text, n + 1U);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_mail_set_error(cct_rt_mail_conn_t *conn, const char *msg) {");
    EMIT("    if (!conn) return;");
    EMIT("    cct_rt_mail_copy_error(conn->last_error, sizeof(conn->last_error), msg);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_socket_close(int fd) {");
    EMIT("    if (fd < 0) return 0;");
    EMIT("    return close(fd);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_mail_conn_init(cct_rt_mail_conn_t *conn) {");
    EMIT("    if (!conn) return;");
    EMIT("    conn->fd = -1;");
    EMIT("    conn->use_tls = 0;");
    EMIT("    conn->ssl_ctx = NULL;");
    EMIT("    conn->ssl = NULL;");
    EMIT("    conn->last_error[0] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_mail_conn_close(cct_rt_mail_conn_t *conn) {");
    EMIT("    if (!conn) return;");
    EMIT("    if (conn->ssl) {");
    EMIT("        SSL_shutdown(conn->ssl);");
    EMIT("        SSL_free(conn->ssl);");
    EMIT("        conn->ssl = NULL;");
    EMIT("    }");
    EMIT("    if (conn->ssl_ctx) {");
    EMIT("        SSL_CTX_free(conn->ssl_ctx);");
    EMIT("        conn->ssl_ctx = NULL;");
    EMIT("    }");
    EMIT("    if (conn->fd >= 0) {");
    EMIT("        cct_rt_mail_socket_close(conn->fd);");
    EMIT("        conn->fd = -1;");
    EMIT("    }");
    EMIT("    conn->use_tls = 0;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_base64_raw(const unsigned char *src, size_t src_len, char *dst, size_t dst_cap) {");
    EMIT("    size_t need = ((src_len + 2U) / 3U) * 4U + 1U;");
    EMIT("    int out_len = 0;");
    EMIT("    if (!dst || dst_cap < need) return 0;");
    EMIT("    out_len = EVP_EncodeBlock((unsigned char*)dst, src, (int)src_len);");
    EMIT("    if (out_len < 0) return 0;");
    EMIT("    dst[(size_t)out_len] = '\\0';");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_base64_text(const char *src, char *dst, size_t dst_cap) {");
    EMIT("    const unsigned char *bytes = (const unsigned char*)(src ? src : \"\");");
    EMIT("    return cct_rt_mail_base64_raw(bytes, strlen((const char*)bytes), dst, dst_cap);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_base64_auth_plain(const char *username, const char *password, char *dst, size_t dst_cap) {");
    EMIT("    const char *user = username ? username : \"\";");
    EMIT("    const char *pass = password ? password : \"\";");
    EMIT("    size_t user_len = strlen(user);");
    EMIT("    size_t pass_len = strlen(pass);");
    EMIT("    size_t raw_len = 1U + user_len + 1U + pass_len;");
    EMIT("    unsigned char *raw = (unsigned char*)cct_rt_alloc_or_fail(raw_len ? raw_len : 1U);");
    EMIT("    size_t off = 0;");
    EMIT("    raw[off++] = 0U;");
    EMIT("    if (user_len > 0) memcpy(raw + off, user, user_len);");
    EMIT("    off += user_len;");
    EMIT("    raw[off++] = 0U;");
    EMIT("    if (pass_len > 0) memcpy(raw + off, pass, pass_len);");
    EMIT("    off += pass_len;");
    EMIT("    int ok = cct_rt_mail_base64_raw(raw, off, dst, dst_cap);");
    EMIT("    cct_rt_free_ptr(raw);");
    EMIT("    return ok;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_conn_read(cct_rt_mail_conn_t *conn, void *buf, size_t len) {");
    EMIT("    if (!conn || conn->fd < 0) return -1;");
    EMIT("    if (conn->use_tls) return SSL_read(conn->ssl, buf, (int)len);");
    EMIT("    return (int)recv(conn->fd, buf, len, 0);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_conn_write(cct_rt_mail_conn_t *conn, const void *buf, size_t len) {");
    EMIT("    if (!conn || conn->fd < 0) return -1;");
    EMIT("    if (conn->use_tls) return SSL_write(conn->ssl, buf, (int)len);");
    EMIT("    return (int)send(conn->fd, buf, len, 0);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_write_all(cct_rt_mail_conn_t *conn, const char *buf, size_t len) {");
    EMIT("    size_t off = 0;");
    EMIT("    while (off < len) {");
    EMIT("        int n = cct_rt_mail_conn_write(conn, buf + off, len - off);");
    EMIT("        if (n <= 0) {");
    EMIT("            cct_rt_mail_set_error(conn, \"falha ao escrever no socket SMTP\");");
    EMIT("            return 0;");
    EMIT("        }");
    EMIT("        off += (size_t)n;");
    EMIT("    }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_read_line(cct_rt_mail_conn_t *conn, char *line, size_t cap) {");
    EMIT("    size_t used = 0;");
    EMIT("    if (!line || cap == 0) return 0;");
    EMIT("    while (used + 1U < cap) {");
    EMIT("        char ch = 0;");
    EMIT("        int n = cct_rt_mail_conn_read(conn, &ch, 1U);");
    EMIT("        if (n <= 0) {");
    EMIT("            cct_rt_mail_set_error(conn, \"falha ao ler resposta SMTP\");");
    EMIT("            return 0;");
    EMIT("        }");
    EMIT("        line[used++] = ch;");
    EMIT("        if (ch == '\\n') break;");
    EMIT("    }");
    EMIT("    line[used] = '\\0';");
    EMIT("    while (used > 0 && (line[used - 1] == '\\n' || line[used - 1] == '\\r')) {");
    EMIT("        line[--used] = '\\0';");
    EMIT("    }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_read_response(cct_rt_mail_conn_t *conn, char *message, size_t message_cap) {");
    EMIT("    int code = -1;");
    EMIT("    char line[1024];");
    EMIT("    if (message && message_cap > 0) message[0] = '\\0';");
    EMIT("    for (;;) {");
    EMIT("        if (!cct_rt_mail_read_line(conn, line, sizeof(line))) return -1;");
    EMIT("        if (isdigit((unsigned char)line[0]) && isdigit((unsigned char)line[1]) && isdigit((unsigned char)line[2])) {");
    EMIT("            code = (line[0] - '0') * 100 + (line[1] - '0') * 10 + (line[2] - '0');");
    EMIT("            if (message && message_cap > 0) {");
    EMIT("                const char *text = line[3] ? line + 4 : line;");
    EMIT("                cct_rt_mail_copy_error(message, message_cap, text);");
    EMIT("            }");
    EMIT("            if (line[3] == ' ') return code;");
    EMIT("            if (line[3] == '-') continue;");
    EMIT("            return code;");
    EMIT("        }");
    EMIT("        if (message && message_cap > 0) cct_rt_mail_copy_error(message, message_cap, line);");
    EMIT("    }");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_expect_code(cct_rt_mail_conn_t *conn, int expected, const char *ctx) {");
    EMIT("    char message[512];");
    EMIT("    int code = cct_rt_mail_read_response(conn, message, sizeof(message));");
    EMIT("    if (code != expected) {");
    EMIT("        char buf[512];");
    EMIT("        snprintf(buf, sizeof(buf), \"%s: SMTP %d %s\", ctx ? ctx : \"SMTP erro\", code, message);");
    EMIT("        cct_rt_mail_set_error(conn, buf);");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_expect_class(cct_rt_mail_conn_t *conn, int klass, const char *ctx) {");
    EMIT("    char message[512];");
    EMIT("    int code = cct_rt_mail_read_response(conn, message, sizeof(message));");
    EMIT("    if (code < 0 || (code / 100) != klass) {");
    EMIT("        char buf[512];");
    EMIT("        snprintf(buf, sizeof(buf), \"%s: SMTP %d %s\", ctx ? ctx : \"SMTP erro\", code, message);");
    EMIT("        cct_rt_mail_set_error(conn, buf);");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_send_command(cct_rt_mail_conn_t *conn, const char *text) {");
    EMIT("    size_t len = strlen(text ? text : \"\");");
    EMIT("    if (!cct_rt_mail_write_all(conn, text ? text : \"\", len)) return 0;");
    EMIT("    return cct_rt_mail_write_all(conn, \"\\r\\n\", 2U);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_connect_tcp(cct_rt_mail_conn_t *conn, const char *host, long long port) {");
    EMIT("    struct addrinfo hints;");
    EMIT("    struct addrinfo *res = NULL;");
    EMIT("    struct addrinfo *it = NULL;");
    EMIT("    char port_text[32];");
    EMIT("    memset(&hints, 0, sizeof(hints));");
    EMIT("    hints.ai_family = AF_UNSPEC;");
    EMIT("    hints.ai_socktype = SOCK_STREAM;");
    EMIT("    snprintf(port_text, sizeof(port_text), \"%lld\", port);");
    EMIT("    if (getaddrinfo((host && *host) ? host : \"127.0.0.1\", port_text, &hints, &res) != 0) {");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao resolver host SMTP\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    for (it = res; it; it = it->ai_next) {");
    EMIT("        int fd = socket(it->ai_family, it->ai_socktype, it->ai_protocol);");
    EMIT("        if (fd < 0) continue;");
    EMIT("        if (connect(fd, it->ai_addr, it->ai_addrlen) == 0) {");
    EMIT("            conn->fd = fd;");
    EMIT("            freeaddrinfo(res);");
    EMIT("            return 1;");
    EMIT("        }");
    EMIT("        cct_rt_mail_socket_close(fd);");
    EMIT("    }");
    EMIT("    freeaddrinfo(res);");
    EMIT("    cct_rt_mail_set_error(conn, \"falha ao conectar ao servidor SMTP\");");
    EMIT("    return 0;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_enable_tls(cct_rt_mail_conn_t *conn, const char *host) {");
    EMIT("    SSL_CTX *ctx = NULL;");
    EMIT("    SSL *ssl = NULL;");
    EMIT("    OPENSSL_init_ssl(0, NULL);");
    EMIT("    ctx = SSL_CTX_new(TLS_client_method());");
    EMIT("    if (!ctx) {");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao criar contexto TLS SMTP\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    SSL_CTX_set_verify(ctx, SSL_VERIFY_NONE, NULL);");
    EMIT("    ssl = SSL_new(ctx);");
    EMIT("    if (!ssl) {");
    EMIT("        SSL_CTX_free(ctx);");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao criar sessao TLS SMTP\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    if (host && *host) SSL_set_tlsext_host_name(ssl, host);");
    EMIT("    SSL_set_fd(ssl, conn->fd);");
    EMIT("    if (SSL_connect(ssl) != 1) {");
    EMIT("        SSL_free(ssl);");
    EMIT("        SSL_CTX_free(ctx);");
    EMIT("        cct_rt_mail_set_error(conn, \"handshake TLS SMTP falhou\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    conn->ssl_ctx = ctx;");
    EMIT("    conn->ssl = ssl;");
    EMIT("    conn->use_tls = 1;");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_mail_get_ehlo_name(char *buf, size_t cap) {");
    EMIT("    if (!buf || cap == 0) return;");
    EMIT("    if (gethostname(buf, cap - 1U) != 0 || buf[0] == '\\0') {");
    EMIT("        cct_rt_mail_copy_error(buf, cap, \"localhost\");");
    EMIT("        return;");
    EMIT("    }");
    EMIT("    buf[cap - 1U] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_send_mail_from(cct_rt_mail_conn_t *conn, const char *mail_from) {");
    EMIT("    char cmd[1024];");
    EMIT("    snprintf(cmd, sizeof(cmd), \"MAIL FROM:<%s>\", (mail_from && *mail_from) ? mail_from : \"\");");
    EMIT("    if (!cct_rt_mail_send_command(conn, cmd)) return 0;");
    EMIT("    return cct_rt_mail_expect_class(conn, 2, \"MAIL FROM rejeitado\");");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_send_recipients(cct_rt_mail_conn_t *conn, const char *rcpts_text) {");
    EMIT("    const char *src = rcpts_text ? rcpts_text : \"\";");
    EMIT("    const char *line = src;");
    EMIT("    int count = 0;");
    EMIT("    while (*line) {");
    EMIT("        const char *end = line;");
    EMIT("        char addr[512];");
    EMIT("        size_t len = 0;");
    EMIT("        char cmd[640];");
    EMIT("        while (*end && *end != '\\n' && *end != '\\r') end++;");
    EMIT("        len = (size_t)(end - line);");
    EMIT("        if (len > 0) {");
    EMIT("            if (len >= sizeof(addr)) len = sizeof(addr) - 1U;");
    EMIT("            memcpy(addr, line, len);");
    EMIT("            addr[len] = '\\0';");
    EMIT("            snprintf(cmd, sizeof(cmd), \"RCPT TO:<%s>\", addr);");
    EMIT("            if (!cct_rt_mail_send_command(conn, cmd)) return 0;");
    EMIT("            if (!cct_rt_mail_expect_class(conn, 2, \"RCPT TO rejeitado\")) return 0;");
    EMIT("            count++;");
    EMIT("        }");
    EMIT("        while (*end == '\\n' || *end == '\\r') end++;");
    EMIT("        line = end;");
    EMIT("    }");
    EMIT("    if (count == 0) {");
    EMIT("        cct_rt_mail_set_error(conn, \"nenhum destinatario SMTP informado\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_mail_dotstuff(const char *mime_text) {");
    EMIT("    const char *src = mime_text ? mime_text : \"\";");
    EMIT("    size_t n = strlen(src);");
    EMIT("    size_t cap = n * 2U + 8U;");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(cap);");
    EMIT("    size_t i = 0;");
    EMIT("    size_t j = 0;");
    EMIT("    int at_line_start = 1;");
    EMIT("    while (i < n) {");
    EMIT("        char ch = src[i];");
    EMIT("        if (at_line_start && ch == '.') out_s[j++] = '.';");
    EMIT("        if (ch == '\\r') {");
    EMIT("            out_s[j++] = '\\r';");
    EMIT("            out_s[j++] = '\\n';");
    EMIT("            if ((i + 1U) < n && src[i + 1U] == '\\n') i++;");
    EMIT("            at_line_start = 1;");
    EMIT("        } else if (ch == '\\n') {");
    EMIT("            out_s[j++] = '\\r';");
    EMIT("            out_s[j++] = '\\n';");
    EMIT("            at_line_start = 1;");
    EMIT("        } else {");
    EMIT("            out_s[j++] = ch;");
    EMIT("            at_line_start = 0;");
    EMIT("        }");
    EMIT("        i++;");
    EMIT("    }");
    EMIT("    if (j < 2U || out_s[j - 2U] != '\\r' || out_s[j - 1U] != '\\n') {");
    EMIT("        out_s[j++] = '\\r';");
    EMIT("        out_s[j++] = '\\n';");
    EMIT("    }");
    EMIT("    out_s[j] = '\\0';");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_send_data(cct_rt_mail_conn_t *conn, const char *mime_text) {");
    EMIT("    char *payload = NULL;");
    EMIT("    if (!cct_rt_mail_send_command(conn, \"DATA\")) return 0;");
    EMIT("    if (!cct_rt_mail_expect_code(conn, 354, \"DATA rejeitado\")) return 0;");
    EMIT("    payload = cct_rt_mail_dotstuff(mime_text);");
    EMIT("    if (!cct_rt_mail_write_all(conn, payload, strlen(payload))) {");
    EMIT("        cct_rt_free_ptr(payload);");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    cct_rt_free_ptr(payload);");
    EMIT("    if (!cct_rt_mail_write_all(conn, \".\\r\\n\", 3U)) return 0;");
    EMIT("    return cct_rt_mail_expect_class(conn, 2, \"DATA final rejeitado\");");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_auth_plain(cct_rt_mail_conn_t *conn, const char *username, const char *password) {");
    EMIT("    char payload[1024];");
    EMIT("    char cmd[1200];");
    EMIT("    if (!cct_rt_mail_base64_auth_plain(username, password, payload, sizeof(payload))) {");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao codificar AUTH PLAIN\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    snprintf(cmd, sizeof(cmd), \"AUTH PLAIN %s\", payload);");
    EMIT("    if (!cct_rt_mail_send_command(conn, cmd)) return 0;");
    EMIT("    return cct_rt_mail_expect_code(conn, 235, \"AUTH PLAIN rejeitado\");");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_auth_login(cct_rt_mail_conn_t *conn, const char *username, const char *password) {");
    EMIT("    char user64[768];");
    EMIT("    char pass64[768];");
    EMIT("    if (!cct_rt_mail_base64_text(username, user64, sizeof(user64)) || !cct_rt_mail_base64_text(password, pass64, sizeof(pass64))) {");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao codificar AUTH LOGIN\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    if (!cct_rt_mail_send_command(conn, \"AUTH LOGIN\")) return 0;");
    EMIT("    if (!cct_rt_mail_expect_code(conn, 334, \"AUTH LOGIN username rejeitado\")) return 0;");
    EMIT("    if (!cct_rt_mail_send_command(conn, user64)) return 0;");
    EMIT("    if (!cct_rt_mail_expect_code(conn, 334, \"AUTH LOGIN password rejeitado\")) return 0;");
    EMIT("    if (!cct_rt_mail_send_command(conn, pass64)) return 0;");
    EMIT("    return cct_rt_mail_expect_code(conn, 235, \"AUTH LOGIN rejeitado\");");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_auth_xoauth2(cct_rt_mail_conn_t *conn, const char *username, const char *password) {");
    EMIT("    const char *user = username ? username : \"\";");
    EMIT("    const char *token = password ? password : \"\";");
    EMIT("    const char *prefix_a = \"user=\";");
    EMIT("    const char *prefix_b = \"\\x01\" \"auth=Bearer \";");
    EMIT("    const char *suffix = \"\\x01\" \"\\x01\";");
    EMIT("    size_t raw_len = strlen(prefix_a) + strlen(user) + strlen(prefix_b) + strlen(token) + strlen(suffix);");
    EMIT("    unsigned char *raw = (unsigned char*)cct_rt_alloc_or_fail(raw_len + 1U);");
    EMIT("    char payload[2048];");
    EMIT("    char cmd[2300];");
    EMIT("    size_t off = 0;");
    EMIT("    memcpy(raw + off, prefix_a, strlen(prefix_a)); off += strlen(prefix_a);");
    EMIT("    memcpy(raw + off, user, strlen(user)); off += strlen(user);");
    EMIT("    memcpy(raw + off, prefix_b, strlen(prefix_b)); off += strlen(prefix_b);");
    EMIT("    memcpy(raw + off, token, strlen(token)); off += strlen(token);");
    EMIT("    memcpy(raw + off, suffix, strlen(suffix)); off += strlen(suffix);");
    EMIT("    raw[off] = '\\0';");
    EMIT("    if (!cct_rt_mail_base64_raw(raw, off, payload, sizeof(payload))) {");
    EMIT("        cct_rt_free_ptr(raw);");
    EMIT("        cct_rt_mail_set_error(conn, \"falha ao codificar AUTH XOAUTH2\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    cct_rt_free_ptr(raw);");
    EMIT("    snprintf(cmd, sizeof(cmd), \"AUTH XOAUTH2 %s\", payload);");
    EMIT("    if (!cct_rt_mail_send_command(conn, cmd)) return 0;");
    EMIT("    return cct_rt_mail_expect_code(conn, 235, \"AUTH XOAUTH2 rejeitado\");");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_mail_authenticate(cct_rt_mail_conn_t *conn, long long auth_kind, const char *username, const char *password) {");
    EMIT("    if (auth_kind == 0) return 1;");
    EMIT("    if (!(username && *username) || !(password && *password)) {");
    EMIT("        cct_rt_mail_set_error(conn, \"credenciais SMTP ausentes\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    if (auth_kind == 1) return cct_rt_mail_auth_plain(conn, username, password);");
    EMIT("    if (auth_kind == 2) return cct_rt_mail_auth_login(conn, username, password);");
    EMIT("    if (auth_kind == 3) return cct_rt_mail_auth_xoauth2(conn, username, password);");
    EMIT("    cct_rt_mail_set_error(conn, \"modo de autenticacao SMTP desconhecido\");");
    EMIT("    return 0;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_mail_smtp_send(const char *host, long long port, const char *username, const char *password, long long auth_kind, long long use_starttls, long long use_smtps, const char *mail_from, const char *rcpts_text, const char *mime_text) {");
    EMIT("    cct_rt_mail_conn_t conn;");
    EMIT("    char ehlo_host[256];");
    EMIT("    char cmd[512];");
    EMIT("    cct_rt_mail_conn_init(&conn);");
    EMIT("    if (!(mail_from && *mail_from)) return cct_rt_mail_dup_cstr(\"MAIL FROM ausente\");");
    EMIT("    if (!rcpts_text || !*rcpts_text) return cct_rt_mail_dup_cstr(\"nenhum destinatario SMTP informado\");");
    EMIT("    if (port <= 0) port = use_smtps ? 465LL : (use_starttls ? 587LL : 25LL);");
    EMIT("    if (!cct_rt_mail_connect_tcp(&conn, host, port)) goto fail;");
    EMIT("    if (use_smtps) {");
    EMIT("        if (!cct_rt_mail_enable_tls(&conn, host)) goto fail;");
    EMIT("    }");
    EMIT("    if (!cct_rt_mail_expect_code(&conn, 220, \"banner SMTP invalido\")) goto fail;");
    EMIT("    cct_rt_mail_get_ehlo_name(ehlo_host, sizeof(ehlo_host));");
    EMIT("    snprintf(cmd, sizeof(cmd), \"EHLO %s\", ehlo_host);");
    EMIT("    if (!cct_rt_mail_send_command(&conn, cmd)) goto fail;");
    EMIT("    if (!cct_rt_mail_expect_class(&conn, 2, \"EHLO rejeitado\")) goto fail;");
    EMIT("    if (use_starttls) {");
    EMIT("        if (!cct_rt_mail_send_command(&conn, \"STARTTLS\")) goto fail;");
    EMIT("        if (!cct_rt_mail_expect_code(&conn, 220, \"STARTTLS rejeitado\")) goto fail;");
    EMIT("        if (!cct_rt_mail_enable_tls(&conn, host)) goto fail;");
    EMIT("        snprintf(cmd, sizeof(cmd), \"EHLO %s\", ehlo_host);");
    EMIT("        if (!cct_rt_mail_send_command(&conn, cmd)) goto fail;");
    EMIT("        if (!cct_rt_mail_expect_class(&conn, 2, \"EHLO apos STARTTLS rejeitado\")) goto fail;");
    EMIT("    }");
    EMIT("    if (!cct_rt_mail_authenticate(&conn, auth_kind, username, password)) goto fail;");
    EMIT("    if (!cct_rt_mail_send_mail_from(&conn, mail_from)) goto fail;");
    EMIT("    if (!cct_rt_mail_send_recipients(&conn, rcpts_text)) goto fail;");
    EMIT("    if (!cct_rt_mail_send_data(&conn, mime_text)) goto fail;");
    EMIT("    cct_rt_mail_send_command(&conn, \"QUIT\");");
    EMIT("    cct_rt_mail_expect_code(&conn, 221, \"QUIT rejeitado\");");
    EMIT("    cct_rt_mail_conn_close(&conn);");
    EMIT("    return cct_rt_mail_dup_cstr(\"\");");
    EMIT("fail:");
    EMIT("    cct_rt_mail_conn_close(&conn);");
    EMIT("    return cct_rt_mail_dup_cstr(conn.last_error);");
    EMIT("}");
    EMIT("#endif");

#undef EMIT
    return true;
}
