/*
 * CCT — Clavicula Turing
 * ZIP archive runtime helper emission
 *
 * FASE 40B: cct/archive_zip host-runtime bridge
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "runtime.h"

bool cct_runtime_emit_archive_zip_helpers(FILE *out) {
    if (!out) return false;

#define EMIT(line) fputs(line "\n", out)

    EMIT("typedef struct {");
    EMIT("    char *name;");
    EMIT("    unsigned char *data;");
    EMIT("    size_t size;");
    EMIT("    uint32_t crc32;");
    EMIT("    uint32_t local_offset;");
    EMIT("    int is_dir;");
    EMIT("} cct_rt_zip_entry_t;");
    EMIT("");
    EMIT("typedef struct {");
    EMIT("    char *archive_path;");
    EMIT("    cct_rt_zip_entry_t *entries;");
    EMIT("    size_t count;");
    EMIT("    size_t capacity;");
    EMIT("    int write_mode;");
    EMIT("} cct_rt_zip_handle_t;");
    EMIT("");
    EMIT("static char cct_rt_zip_last_error_buf[512];");
    EMIT("static uint32_t cct_rt_zip_crc32_table[256];");
    EMIT("static int cct_rt_zip_crc32_ready = 0;");
    EMIT("");
    EMIT("static void cct_rt_zip_copy_text(char *dst, size_t cap, const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    if (cap == 0u) return;");
    EMIT("    if (n >= cap) n = cap - 1u;");
    EMIT("    memcpy(dst, text, n);");
    EMIT("    dst[n] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_set_error(const char *msg) {");
    EMIT("    cct_rt_zip_copy_text(cct_rt_zip_last_error_buf, sizeof(cct_rt_zip_last_error_buf), msg);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_clear_error(void) {");
    EMIT("    cct_rt_zip_last_error_buf[0] = '\\0';");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_dup_cstr(const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);");
    EMIT("    memcpy(out_s, text, n + 1u);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_last_error(void) {");
    EMIT("    return cct_rt_zip_dup_cstr(cct_rt_zip_last_error_buf);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_crc32_init(void) {");
    EMIT("    if (cct_rt_zip_crc32_ready) return;");
    EMIT("    for (uint32_t i = 0u; i < 256u; i++) {");
    EMIT("        uint32_t c = i;");
    EMIT("        for (int j = 0; j < 8; j++) c = (c & 1u) ? (0xEDB88320u ^ (c >> 1)) : (c >> 1);");
    EMIT("        cct_rt_zip_crc32_table[i] = c;");
    EMIT("    }");
    EMIT("    cct_rt_zip_crc32_ready = 1;");
    EMIT("}");
    EMIT("");
    EMIT("static uint32_t cct_rt_zip_crc32_buf(const unsigned char *data, size_t len) {");
    EMIT("    uint32_t crc = 0xFFFFFFFFu;");
    EMIT("    cct_rt_zip_crc32_init();");
    EMIT("    for (size_t i = 0u; i < len; i++) crc = (crc >> 8) ^ cct_rt_zip_crc32_table[(crc ^ data[i]) & 0xFFu];");
    EMIT("    return crc ^ 0xFFFFFFFFu;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_write_u16(FILE *fp, uint16_t value) {");
    EMIT("    unsigned char buf[2];");
    EMIT("    buf[0] = (unsigned char)(value & 0xFFu);");
    EMIT("    buf[1] = (unsigned char)((value >> 8) & 0xFFu);");
    EMIT("    if (fwrite(buf, 1u, 2u, fp) != 2u) cct_rt_fail(\"zip write_u16 failed\");");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_write_u32(FILE *fp, uint32_t value) {");
    EMIT("    unsigned char buf[4];");
    EMIT("    buf[0] = (unsigned char)(value & 0xFFu);");
    EMIT("    buf[1] = (unsigned char)((value >> 8) & 0xFFu);");
    EMIT("    buf[2] = (unsigned char)((value >> 16) & 0xFFu);");
    EMIT("    buf[3] = (unsigned char)((value >> 24) & 0xFFu);");
    EMIT("    if (fwrite(buf, 1u, 4u, fp) != 4u) cct_rt_fail(\"zip write_u32 failed\");");
    EMIT("}");
    EMIT("");
    EMIT("static uint16_t cct_rt_zip_le16(const unsigned char *buf) {");
    EMIT("    return (uint16_t)((uint16_t)buf[0] | ((uint16_t)buf[1] << 8));");
    EMIT("}");
    EMIT("");
    EMIT("static uint32_t cct_rt_zip_le32(const unsigned char *buf) {");
    EMIT("    return (uint32_t)buf[0] | ((uint32_t)buf[1] << 8) | ((uint32_t)buf[2] << 16) | ((uint32_t)buf[3] << 24);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_has_segment(const char *name, const char *segment) {");
    EMIT("    const char *start = name;");
    EMIT("    const char *slash = NULL;");
    EMIT("    size_t seg_len = strlen(segment);");
    EMIT("    if (!name || !segment) return 0;");
    EMIT("    while (*start) {");
    EMIT("        slash = strchr(start, '/');");
    EMIT("        size_t part_len = slash ? (size_t)(slash - start) : strlen(start);");
    EMIT("        if (part_len == seg_len && memcmp(start, segment, seg_len) == 0) return 1;");
    EMIT("        if (!slash) break;");
    EMIT("        start = slash + 1;");
    EMIT("    }");
    EMIT("    return 0;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_validate_entry_name(const char *name) {");
    EMIT("    size_t len = name ? strlen(name) : 0u;");
    EMIT("    if (!name || len == 0u) { cct_rt_zip_set_error(\"zip: entry_name ausente\"); return 0; }");
    EMIT("    if (name[0] == '/' || name[0] == '\\\\') { cct_rt_zip_set_error(\"zip: entry_name absoluto rejeitado\"); return 0; }");
    EMIT("    if (strchr(name, '\\\\')) { cct_rt_zip_set_error(\"zip: entry_name com barra invertida rejeitado\"); return 0; }");
    EMIT("    if (len >= 2u && isalpha((unsigned char)name[0]) && name[1] == ':') { cct_rt_zip_set_error(\"zip: entry_name com drive absoluto rejeitado\"); return 0; }");
    EMIT("    if (cct_rt_zip_has_segment(name, \"..\") || cct_rt_zip_has_segment(name, \".\")) { cct_rt_zip_set_error(\"zip: entry_name com path traversal rejeitado\"); return 0; }");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static unsigned char *cct_rt_zip_read_file_bytes(const char *path, size_t *out_len) {");
    EMIT("    FILE *fp = NULL;");
    EMIT("    long size = 0;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    if (out_len) *out_len = 0u;");
    EMIT("    fp = fopen(path, \"rb\");");
    EMIT("    if (!fp) return NULL;");
    EMIT("    if (fseek(fp, 0L, SEEK_END) != 0) { fclose(fp); return NULL; }");
    EMIT("    size = ftell(fp);");
    EMIT("    if (size < 0) { fclose(fp); return NULL; }");
    EMIT("    if (fseek(fp, 0L, SEEK_SET) != 0) { fclose(fp); return NULL; }");
    EMIT("    data = (unsigned char*)cct_rt_alloc_or_fail((size_t)size + 1u);");
    EMIT("    if ((size_t)size > 0u && fread(data, 1u, (size_t)size, fp) != (size_t)size) {");
    EMIT("        cct_rt_free_ptr(data);");
    EMIT("        fclose(fp);");
    EMIT("        return NULL;");
    EMIT("    }");
    EMIT("    fclose(fp);");
    EMIT("    if (out_len) *out_len = (size_t)size;");
    EMIT("    return data;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_free_entry(cct_rt_zip_entry_t *entry) {");
    EMIT("    if (!entry) return;");
    EMIT("    if (entry->name) cct_rt_free_ptr(entry->name);");
    EMIT("    if (entry->data) cct_rt_free_ptr(entry->data);");
    EMIT("    entry->name = NULL;");
    EMIT("    entry->data = NULL;");
    EMIT("    entry->size = 0u;");
    EMIT("    entry->crc32 = 0u;");
    EMIT("    entry->local_offset = 0u;");
    EMIT("    entry->is_dir = 0;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_free_handle(cct_rt_zip_handle_t *handle) {");
    EMIT("    if (!handle) return;");
    EMIT("    if (handle->archive_path) cct_rt_free_ptr(handle->archive_path);");
    EMIT("    for (size_t i = 0u; i < handle->count; i++) cct_rt_zip_free_entry(&handle->entries[i]);");
    EMIT("    if (handle->entries) cct_rt_free_ptr(handle->entries);");
    EMIT("    cct_rt_free_ptr(handle);");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_entry_index(cct_rt_zip_handle_t *handle, const char *name) {");
    EMIT("    if (!handle || !name) return -1;");
    EMIT("    for (size_t i = 0u; i < handle->count; i++) {");
    EMIT("        if (handle->entries[i].name && strcmp(handle->entries[i].name, name) == 0) return (int)i;");
    EMIT("    }");
    EMIT("    return -1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_reserve(cct_rt_zip_handle_t *handle, size_t need) {");
    EMIT("    if (!handle) return 0;");
    EMIT("    if (need <= handle->capacity) return 1;");
    EMIT("    size_t new_cap = handle->capacity ? handle->capacity * 2u : 8u;");
    EMIT("    while (new_cap < need) new_cap *= 2u;");
    EMIT("    cct_rt_zip_entry_t *entries = (cct_rt_zip_entry_t*)realloc(handle->entries, new_cap * sizeof(cct_rt_zip_entry_t));");
    EMIT("    if (!entries) { cct_rt_zip_set_error(\"zip: allocation failed\"); return 0; }");
    EMIT("    for (size_t i = handle->capacity; i < new_cap; i++) memset(&entries[i], 0, sizeof(cct_rt_zip_entry_t));");
    EMIT("    handle->entries = entries;");
    EMIT("    handle->capacity = new_cap;");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_push_entry(cct_rt_zip_handle_t *handle, const char *name, const unsigned char *data, size_t len, int is_dir) {");
    EMIT("    cct_rt_zip_entry_t *entry = NULL;");
    EMIT("    if (!handle || !name) return 0;");
    EMIT("    if (cct_rt_zip_entry_index(handle, name) >= 0) { cct_rt_zip_set_error(\"zip: entry_name duplicado\"); return 0; }");
    EMIT("    if (!cct_rt_zip_reserve(handle, handle->count + 1u)) return 0;");
    EMIT("    entry = &handle->entries[handle->count++];");
    EMIT("    memset(entry, 0, sizeof(*entry));");
    EMIT("    entry->name = cct_rt_zip_dup_cstr(name);");
    EMIT("    entry->is_dir = is_dir ? 1 : 0;");
    EMIT("    entry->size = len;");
    EMIT("    if (len > 0u) {");
    EMIT("        entry->data = (unsigned char*)cct_rt_alloc_or_fail(len);");
    EMIT("        memcpy(entry->data, data, len);");
    EMIT("    }");
    EMIT("    entry->crc32 = cct_rt_zip_crc32_buf(data ? data : (const unsigned char*)\"\", len);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_write_archive(cct_rt_zip_handle_t *handle) {");
    EMIT("    FILE *fp = NULL;");
    EMIT("    uint32_t central_offset = 0u;");
    EMIT("    uint32_t central_size = 0u;");
    EMIT("    if (!handle || !handle->archive_path) return 0;");
    EMIT("    fp = fopen(handle->archive_path, \"wb\");");
    EMIT("    if (!fp) { cct_rt_zip_set_error(\"zip: falha ao criar arquivo zip\"); return 0; }");
    EMIT("    for (size_t i = 0u; i < handle->count; i++) {");
    EMIT("        cct_rt_zip_entry_t *entry = &handle->entries[i];");
    EMIT("        size_t name_len = strlen(entry->name ? entry->name : \"\");");
    EMIT("        long pos = ftell(fp);");
    EMIT("        if (pos < 0L || (unsigned long)pos > 0xFFFFFFFFul) { fclose(fp); cct_rt_zip_set_error(\"zip: archive grande demais\"); return 0; }");
    EMIT("        entry->local_offset = (uint32_t)pos;");
    EMIT("        cct_rt_zip_write_u32(fp, 0x04034b50u);");
    EMIT("        cct_rt_zip_write_u16(fp, 20u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u32(fp, entry->crc32);");
    EMIT("        cct_rt_zip_write_u32(fp, (uint32_t)entry->size);");
    EMIT("        cct_rt_zip_write_u32(fp, (uint32_t)entry->size);");
    EMIT("        cct_rt_zip_write_u16(fp, (uint16_t)name_len);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        if (name_len > 0u && fwrite(entry->name, 1u, name_len, fp) != name_len) { fclose(fp); cct_rt_zip_set_error(\"zip: falha ao escrever nome local\"); return 0; }");
    EMIT("        if (entry->size > 0u && fwrite(entry->data, 1u, entry->size, fp) != entry->size) { fclose(fp); cct_rt_zip_set_error(\"zip: falha ao escrever dados de entry\"); return 0; }");
    EMIT("    }");
    EMIT("    { long pos = ftell(fp); if (pos < 0L || (unsigned long)pos > 0xFFFFFFFFul) { fclose(fp); cct_rt_zip_set_error(\"zip: archive grande demais\"); return 0; } central_offset = (uint32_t)pos; }");
    EMIT("    for (size_t i = 0u; i < handle->count; i++) {");
    EMIT("        cct_rt_zip_entry_t *entry = &handle->entries[i];");
    EMIT("        size_t name_len = strlen(entry->name ? entry->name : \"\");");
    EMIT("        cct_rt_zip_write_u32(fp, 0x02014b50u);");
    EMIT("        cct_rt_zip_write_u16(fp, 20u);");
    EMIT("        cct_rt_zip_write_u16(fp, 20u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u32(fp, entry->crc32);");
    EMIT("        cct_rt_zip_write_u32(fp, (uint32_t)entry->size);");
    EMIT("        cct_rt_zip_write_u32(fp, (uint32_t)entry->size);");
    EMIT("        cct_rt_zip_write_u16(fp, (uint16_t)name_len);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u16(fp, 0u);");
    EMIT("        cct_rt_zip_write_u32(fp, entry->is_dir ? 16u : 0u);");
    EMIT("        cct_rt_zip_write_u32(fp, entry->local_offset);");
    EMIT("        if (name_len > 0u && fwrite(entry->name, 1u, name_len, fp) != name_len) { fclose(fp); cct_rt_zip_set_error(\"zip: falha ao escrever nome central\"); return 0; }");
    EMIT("    }");
    EMIT("    { long pos = ftell(fp); if (pos < 0L || (unsigned long)pos > 0xFFFFFFFFul) { fclose(fp); cct_rt_zip_set_error(\"zip: archive grande demais\"); return 0; } central_size = (uint32_t)pos - central_offset; }");
    EMIT("    cct_rt_zip_write_u32(fp, 0x06054b50u);");
    EMIT("    cct_rt_zip_write_u16(fp, 0u);");
    EMIT("    cct_rt_zip_write_u16(fp, 0u);");
    EMIT("    cct_rt_zip_write_u16(fp, (uint16_t)handle->count);");
    EMIT("    cct_rt_zip_write_u16(fp, (uint16_t)handle->count);");
    EMIT("    cct_rt_zip_write_u32(fp, central_size);");
    EMIT("    cct_rt_zip_write_u32(fp, central_offset);");
    EMIT("    cct_rt_zip_write_u16(fp, 0u);");
    EMIT("    fclose(fp);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_parse_eocd(FILE *fp, uint32_t *central_offset, uint16_t *entry_count) {");
    EMIT("    long size = 0L;");
    EMIT("    long window = 0L;");
    EMIT("    unsigned char *buf = NULL;");
    EMIT("    if (!fp || !central_offset || !entry_count) return 0;");
    EMIT("    if (fseek(fp, 0L, SEEK_END) != 0) return 0;");
    EMIT("    size = ftell(fp);");
    EMIT("    if (size < 22L) return 0;");
    EMIT("    window = size < 66000L ? size : 66000L;");
    EMIT("    if (fseek(fp, size - window, SEEK_SET) != 0) return 0;");
    EMIT("    buf = (unsigned char*)cct_rt_alloc_or_fail((size_t)window);");
    EMIT("    if (fread(buf, 1u, (size_t)window, fp) != (size_t)window) { cct_rt_free_ptr(buf); return 0; }");
    EMIT("    for (long i = window - 22L; i >= 0L; i--) {");
    EMIT("        if (buf[i] == 0x50u && buf[i + 1L] == 0x4Bu && buf[i + 2L] == 0x05u && buf[i + 3L] == 0x06u) {");
    EMIT("            *entry_count = cct_rt_zip_le16(buf + i + 10L);");
    EMIT("            *central_offset = cct_rt_zip_le32(buf + i + 16L);");
    EMIT("            cct_rt_free_ptr(buf);");
    EMIT("            return 1;");
    EMIT("        }");
    EMIT("    }");
    EMIT("    cct_rt_free_ptr(buf);");
    EMIT("    return 0;");
    EMIT("}");
    EMIT("");
    EMIT("static void *cct_rt_zip_create(const char *path) {");
    EMIT("    cct_rt_zip_handle_t *handle = NULL;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!path || !*path) { cct_rt_zip_set_error(\"zip: archive_path ausente\"); return NULL; }");
    EMIT("    handle = (cct_rt_zip_handle_t*)cct_rt_alloc_or_fail(sizeof(cct_rt_zip_handle_t));");
    EMIT("    memset(handle, 0, sizeof(*handle));");
    EMIT("    handle->archive_path = cct_rt_zip_dup_cstr(path);");
    EMIT("    handle->write_mode = 1;");
    EMIT("    return handle;");
    EMIT("}");
    EMIT("");
    EMIT("static void *cct_rt_zip_open(const char *path) {");
    EMIT("    FILE *fp = NULL;");
    EMIT("    uint32_t central_offset = 0u;");
    EMIT("    uint16_t entry_count = 0u;");
    EMIT("    cct_rt_zip_handle_t *handle = NULL;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!path || !*path) { cct_rt_zip_set_error(\"zip: archive_path ausente\"); return NULL; }");
    EMIT("    fp = fopen(path, \"rb\");");
    EMIT("    if (!fp) { cct_rt_zip_set_error(\"zip: archive inexistente\"); return NULL; }");
    EMIT("    if (!cct_rt_zip_parse_eocd(fp, &central_offset, &entry_count)) { fclose(fp); cct_rt_zip_set_error(\"zip: EOCD invalido ou ausente\"); return NULL; }");
    EMIT("    handle = (cct_rt_zip_handle_t*)cct_rt_alloc_or_fail(sizeof(cct_rt_zip_handle_t));");
    EMIT("    memset(handle, 0, sizeof(*handle));");
    EMIT("    handle->archive_path = cct_rt_zip_dup_cstr(path);");
    EMIT("    handle->write_mode = 0;");
    EMIT("    if (!cct_rt_zip_reserve(handle, (size_t)entry_count)) { fclose(fp); cct_rt_zip_free_handle(handle); return NULL; }");
    EMIT("    if (fseek(fp, (long)central_offset, SEEK_SET) != 0) { fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: central directory invalido\"); return NULL; }");
    EMIT("    for (uint16_t i = 0u; i < entry_count; i++) {");
    EMIT("        unsigned char hdr[46];");
    EMIT("        uint16_t name_len = 0u;");
    EMIT("        uint16_t extra_len = 0u;");
    EMIT("        uint16_t comment_len = 0u;");
    EMIT("        uint16_t method = 0u;");
    EMIT("        uint32_t uncomp_size = 0u;");
    EMIT("        uint32_t local_offset = 0u;");
    EMIT("        char *name = NULL;");
    EMIT("        if (fread(hdr, 1u, sizeof(hdr), fp) != sizeof(hdr)) { fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: central directory truncado\"); return NULL; }");
    EMIT("        if (cct_rt_zip_le32(hdr) != 0x02014b50u) { fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: assinatura central invalida\"); return NULL; }");
    EMIT("        method = cct_rt_zip_le16(hdr + 10u);");
    EMIT("        if (method != 0u) { fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: apenas entries STORE sao suportadas atualmente\"); return NULL; }");
    EMIT("        uncomp_size = cct_rt_zip_le32(hdr + 24u);");
    EMIT("        name_len = cct_rt_zip_le16(hdr + 28u);");
    EMIT("        extra_len = cct_rt_zip_le16(hdr + 30u);");
    EMIT("        comment_len = cct_rt_zip_le16(hdr + 32u);");
    EMIT("        local_offset = cct_rt_zip_le32(hdr + 42u);");
    EMIT("        name = (char*)cct_rt_alloc_or_fail((size_t)name_len + 1u);");
    EMIT("        if (name_len > 0u && fread(name, 1u, (size_t)name_len, fp) != (size_t)name_len) { cct_rt_free_ptr(name); fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: nome central truncado\"); return NULL; }");
    EMIT("        name[name_len] = '\\0';");
    EMIT("        if (extra_len > 0u && fseek(fp, (long)extra_len, SEEK_CUR) != 0) { cct_rt_free_ptr(name); fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: extra field invalido\"); return NULL; }");
    EMIT("        if (comment_len > 0u && fseek(fp, (long)comment_len, SEEK_CUR) != 0) { cct_rt_free_ptr(name); fclose(fp); cct_rt_zip_free_handle(handle); cct_rt_zip_set_error(\"zip: comment field invalido\"); return NULL; }");
    EMIT("        handle->entries[handle->count].name = name;");
    EMIT("        handle->entries[handle->count].size = (size_t)uncomp_size;");
    EMIT("        handle->entries[handle->count].crc32 = cct_rt_zip_le32(hdr + 16u);");
    EMIT("        handle->entries[handle->count].local_offset = local_offset;");
    EMIT("        handle->entries[handle->count].is_dir = (name_len > 0u && name[name_len - 1u] == '/') ? 1 : 0;");
    EMIT("        handle->count++;");
    EMIT("    }");
    EMIT("    fclose(fp);");
    EMIT("    return handle;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_zip_close(void *ptr) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle) return;");
    EMIT("    if (handle->write_mode && !cct_rt_zip_write_archive(handle)) { cct_rt_zip_free_handle(handle); return; }");
    EMIT("    cct_rt_zip_free_handle(handle);");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_add_file(void *ptr, const char *source_path, const char *entry_name) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    size_t len = 0u;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle || !handle->write_mode) { cct_rt_zip_set_error(\"zip: handle invalido para escrita\"); return 0LL; }");
    EMIT("    if (!cct_rt_zip_validate_entry_name(entry_name)) return 0LL;");
    EMIT("    data = cct_rt_zip_read_file_bytes(source_path, &len);");
    EMIT("    if (!data && len == 0u) { cct_rt_zip_set_error(\"zip: falha ao ler source_path\"); return 0LL; }");
    EMIT("    if (!cct_rt_zip_push_entry(handle, entry_name, data, len, 0)) { if (data) cct_rt_free_ptr(data); return 0LL; }");
    EMIT("    if (data) cct_rt_free_ptr(data);");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_add_text(void *ptr, const char *entry_name, const char *content) {");
    EMIT("    const unsigned char *data = (const unsigned char*)(content ? content : \"\");");
    EMIT("    size_t len = strlen((const char*)data);");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle || !handle->write_mode) { cct_rt_zip_set_error(\"zip: handle invalido para escrita\"); return 0LL; }");
    EMIT("    if (!cct_rt_zip_validate_entry_name(entry_name)) return 0LL;");
    EMIT("    return cct_rt_zip_push_entry(handle, entry_name, data, len, 0) ? 1LL : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_entry_count(void *ptr) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    return handle ? (long long)handle->count : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_entry_name(void *ptr, long long index) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle || index < 0LL || (size_t)index >= handle->count) return cct_rt_zip_dup_cstr(\"\");");
    EMIT("    return cct_rt_zip_dup_cstr(handle->entries[index].name);");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_entry_size(void *ptr, long long index) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    if (!handle || index < 0LL || (size_t)index >= handle->count) return 0LL;");
    EMIT("    return (long long)handle->entries[index].size;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_entry_is_dir(void *ptr, long long index) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    if (!handle || index < 0LL || (size_t)index >= handle->count) return 0LL;");
    EMIT("    return handle->entries[index].is_dir ? 1LL : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static unsigned char *cct_rt_zip_entry_read_data(cct_rt_zip_handle_t *handle, cct_rt_zip_entry_t *entry, size_t *out_len) {");
    EMIT("    FILE *fp = NULL;");
    EMIT("    unsigned char hdr[30];");
    EMIT("    uint16_t name_len = 0u;");
    EMIT("    uint16_t extra_len = 0u;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    if (out_len) *out_len = 0u;");
    EMIT("    if (!handle || !entry) return NULL;");
    EMIT("    if (handle->write_mode) {");
    EMIT("        if (out_len) *out_len = entry->size;");
    EMIT("        if (entry->size == 0u) return (unsigned char*)cct_rt_alloc_or_fail(1u);");
    EMIT("        data = (unsigned char*)cct_rt_alloc_or_fail(entry->size);");
    EMIT("        memcpy(data, entry->data, entry->size);");
    EMIT("        return data;");
    EMIT("    }");
    EMIT("    fp = fopen(handle->archive_path, \"rb\");");
    EMIT("    if (!fp) return NULL;");
    EMIT("    if (fseek(fp, (long)entry->local_offset, SEEK_SET) != 0) { fclose(fp); return NULL; }");
    EMIT("    if (fread(hdr, 1u, sizeof(hdr), fp) != sizeof(hdr)) { fclose(fp); return NULL; }");
    EMIT("    if (cct_rt_zip_le32(hdr) != 0x04034b50u) { fclose(fp); return NULL; }");
    EMIT("    if (cct_rt_zip_le16(hdr + 8u) != 0u) { fclose(fp); return NULL; }");
    EMIT("    name_len = cct_rt_zip_le16(hdr + 26u);");
    EMIT("    extra_len = cct_rt_zip_le16(hdr + 28u);");
    EMIT("    if (fseek(fp, (long)name_len + (long)extra_len, SEEK_CUR) != 0) { fclose(fp); return NULL; }");
    EMIT("    data = (unsigned char*)cct_rt_alloc_or_fail(entry->size ? entry->size : 1u);");
    EMIT("    if (entry->size > 0u && fread(data, 1u, entry->size, fp) != entry->size) { cct_rt_free_ptr(data); fclose(fp); return NULL; }");
    EMIT("    fclose(fp);");
    EMIT("    if (out_len) *out_len = entry->size;");
    EMIT("    return data;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_read_text(void *ptr, const char *entry_name) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    int idx = -1;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    size_t len = 0u;");
    EMIT("    char *out_s = NULL;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle) { cct_rt_zip_set_error(\"zip: handle invalido\"); return cct_rt_zip_dup_cstr(\"\"); }");
    EMIT("    idx = cct_rt_zip_entry_index(handle, entry_name);");
    EMIT("    if (idx < 0) { cct_rt_zip_set_error(\"zip: entry nao encontrada\"); return cct_rt_zip_dup_cstr(\"\"); }");
    EMIT("    if (handle->entries[idx].is_dir) { cct_rt_zip_set_error(\"zip: entry de diretorio nao pode ser lida como texto\"); return cct_rt_zip_dup_cstr(\"\"); }");
    EMIT("    data = cct_rt_zip_entry_read_data(handle, &handle->entries[idx], &len);");
    EMIT("    if (!data && len == 0u) { cct_rt_zip_set_error(\"zip: falha ao ler entry\"); return cct_rt_zip_dup_cstr(\"\"); }");
    EMIT("    out_s = (char*)cct_rt_alloc_or_fail(len + 1u);");
    EMIT("    if (len > 0u) memcpy(out_s, data, len);");
    EMIT("    out_s[len] = '\\0';");
    EMIT("    if (data) cct_rt_free_ptr(data);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_parent_dir(const char *path) {");
    EMIT("    const char *slash = NULL;");
    EMIT("    size_t len = 0u;");
    EMIT("    char *out_s = NULL;");
    EMIT("    if (!path) return cct_rt_zip_dup_cstr(\"\");");
    EMIT("    slash = strrchr(path, '/');");
    EMIT("    if (!slash) return cct_rt_zip_dup_cstr(\"\");");
    EMIT("    len = (size_t)(slash - path);");
    EMIT("    out_s = (char*)cct_rt_alloc_or_fail(len + 1u);");
    EMIT("    memcpy(out_s, path, len);");
    EMIT("    out_s[len] = '\\0';");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_zip_join_path(const char *base, const char *name) {");
    EMIT("    size_t a = strlen(base ? base : \"\");");
    EMIT("    size_t b = strlen(name ? name : \"\");");
    EMIT("    int need_sep = (a > 0u && base[a - 1u] != '/');");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(a + (need_sep ? 1u : 0u) + b + 1u);");
    EMIT("    memcpy(out_s, base ? base : \"\", a);");
    EMIT("    if (need_sep) out_s[a++] = '/';");
    EMIT("    memcpy(out_s + a, name ? name : \"\", b);");
    EMIT("    out_s[a + b] = '\\0';");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_zip_extract_one(cct_rt_zip_handle_t *handle, cct_rt_zip_entry_t *entry, const char *output_dir, int overwrite) {");
    EMIT("    char *target = NULL;");
    EMIT("    char *parent = NULL;");
    EMIT("    unsigned char *data = NULL;");
    EMIT("    size_t len = 0u;");
    EMIT("    FILE *fp = NULL;");
    EMIT("    if (!handle || !entry || !output_dir) return 0;");
    EMIT("    if (!cct_rt_zip_validate_entry_name(entry->name)) return 0;");
    EMIT("    target = cct_rt_zip_join_path(output_dir, entry->name);");
    EMIT("    if (entry->is_dir) {");
    EMIT("        cct_rt_fs_mkdir_all(target);");
    EMIT("        cct_rt_free_ptr(target);");
    EMIT("        return 1;");
    EMIT("    }");
    EMIT("    parent = cct_rt_zip_parent_dir(target);");
    EMIT("    if (parent[0] != '\\0') cct_rt_fs_mkdir_all(parent);");
    EMIT("    if (!overwrite && cct_rt_fs_exists(target)) {");
    EMIT("        cct_rt_free_ptr(parent);");
    EMIT("        cct_rt_free_ptr(target);");
    EMIT("        cct_rt_zip_set_error(\"zip: destino ja existe e overwrite=false\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    data = cct_rt_zip_entry_read_data(handle, entry, &len);");
    EMIT("    if (!data && len == 0u) {");
    EMIT("        cct_rt_free_ptr(parent);");
    EMIT("        cct_rt_free_ptr(target);");
    EMIT("        cct_rt_zip_set_error(\"zip: falha ao ler entry para extracao\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    fp = fopen(target, \"wb\");");
    EMIT("    if (!fp) {");
    EMIT("        if (data) cct_rt_free_ptr(data);");
    EMIT("        cct_rt_free_ptr(parent);");
    EMIT("        cct_rt_free_ptr(target);");
    EMIT("        cct_rt_zip_set_error(\"zip: falha ao criar arquivo extraido\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    if (len > 0u && fwrite(data, 1u, len, fp) != len) {");
    EMIT("        fclose(fp);");
    EMIT("        if (data) cct_rt_free_ptr(data);");
    EMIT("        cct_rt_free_ptr(parent);");
    EMIT("        cct_rt_free_ptr(target);");
    EMIT("        cct_rt_zip_set_error(\"zip: falha ao escrever arquivo extraido\");");
    EMIT("        return 0;");
    EMIT("    }");
    EMIT("    fclose(fp);");
    EMIT("    if (data) cct_rt_free_ptr(data);");
    EMIT("    cct_rt_free_ptr(parent);");
    EMIT("    cct_rt_free_ptr(target);");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_extract_all(void *ptr, const char *output_dir, long long overwrite) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle) { cct_rt_zip_set_error(\"zip: handle invalido\"); return 0LL; }");
    EMIT("    if (!output_dir || !*output_dir) { cct_rt_zip_set_error(\"zip: output_dir ausente\"); return 0LL; }");
    EMIT("    cct_rt_fs_mkdir_all(output_dir);");
    EMIT("    for (size_t i = 0u; i < handle->count; i++) if (!cct_rt_zip_extract_one(handle, &handle->entries[i], output_dir, overwrite ? 1 : 0)) return 0LL;");
    EMIT("    return 1LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_zip_extract_entry(void *ptr, const char *entry_name, const char *output_dir, long long overwrite) {");
    EMIT("    cct_rt_zip_handle_t *handle = (cct_rt_zip_handle_t*)ptr;");
    EMIT("    int idx = -1;");
    EMIT("    cct_rt_zip_clear_error();");
    EMIT("    if (!handle) { cct_rt_zip_set_error(\"zip: handle invalido\"); return 0LL; }");
    EMIT("    idx = cct_rt_zip_entry_index(handle, entry_name);");
    EMIT("    if (idx < 0) { cct_rt_zip_set_error(\"zip: entry nao encontrada\"); return 0LL; }");
    EMIT("    cct_rt_fs_mkdir_all(output_dir);");
    EMIT("    return cct_rt_zip_extract_one(handle, &handle->entries[idx], output_dir, overwrite ? 1 : 0) ? 1LL : 0LL;");
    EMIT("}");

#undef EMIT
    return true;
}
