/*
 * CCT — Clavicula Turing
 * Runtime instrumentation helper emission
 *
 * FASE 38A: cct/instrument host-runtime bridge
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "runtime.h"

bool cct_runtime_emit_instrument_helpers(FILE *out) {
    if (!out) return false;

#define EMIT(line) fputs(line "\n", out)

    EMIT("typedef struct {");
    EMIT("    char *key;");
    EMIT("    char *value;");
    EMIT("} cct_rt_instr_attr_t;");
    EMIT("");
    EMIT("typedef struct {");
    EMIT("    long long span_id;");
    EMIT("    long long parent_id;");
    EMIT("    char *name;");
    EMIT("    char *category;");
    EMIT("    long long start_us;");
    EMIT("    long long end_us;");
    EMIT("    int closed;");
    EMIT("    cct_rt_instr_attr_t *attrs;");
    EMIT("    size_t attr_count;");
    EMIT("    size_t attr_cap;");
    EMIT("} cct_rt_instr_span_t;");
    EMIT("");
    EMIT("static int cct_rt_instr_enabled = 0;");
    EMIT("static long long cct_rt_instr_mode_value = 0;");
    EMIT("static long long cct_rt_instr_next_span_id = 1;");
    EMIT("static cct_rt_instr_span_t *cct_rt_instr_spans = NULL;");
    EMIT("static size_t cct_rt_instr_span_count = 0;");
    EMIT("static size_t cct_rt_instr_span_cap = 0;");
    EMIT("static long long cct_rt_instr_active_stack[64];");
    EMIT("static size_t cct_rt_instr_active_depth = 0;");
    EMIT("");
    EMIT("static char *cct_rt_instr_dup(const char *src) {");
    EMIT("    const char *text = src ? src : \"\";");
    EMIT("    size_t n = strlen(text);");
    EMIT("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1U);");
    EMIT("    memcpy(out_s, text, n + 1U);");
    EMIT("    return out_s;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_now_us(void) {");
    EMIT("    return cct_rt_time_now_ns() / 1000LL;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_span_release(cct_rt_instr_span_t *span) {");
    EMIT("    size_t i = 0;");
    EMIT("    if (!span) return;");
    EMIT("    if (span->name) cct_rt_free_ptr(span->name);");
    EMIT("    if (span->category) cct_rt_free_ptr(span->category);");
    EMIT("    for (i = 0; i < span->attr_count; i++) {");
    EMIT("        if (span->attrs[i].key) cct_rt_free_ptr(span->attrs[i].key);");
    EMIT("        if (span->attrs[i].value) cct_rt_free_ptr(span->attrs[i].value);");
    EMIT("    }");
    EMIT("    if (span->attrs) cct_rt_free_ptr(span->attrs);");
    EMIT("    memset(span, 0, sizeof(*span));");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_reset_state(void) {");
    EMIT("    size_t i = 0;");
    EMIT("    for (i = 0; i < cct_rt_instr_span_count; i++) cct_rt_instr_span_release(&cct_rt_instr_spans[i]);");
    EMIT("    if (cct_rt_instr_spans) cct_rt_free_ptr(cct_rt_instr_spans);");
    EMIT("    cct_rt_instr_spans = NULL;");
    EMIT("    cct_rt_instr_span_count = 0;");
    EMIT("    cct_rt_instr_span_cap = 0;");
    EMIT("    cct_rt_instr_active_depth = 0;");
    EMIT("    cct_rt_instr_next_span_id = 1;");
    EMIT("}");
    EMIT("");
    EMIT("static cct_rt_instr_span_t *cct_rt_instr_append_span(void) {");
    EMIT("    cct_rt_instr_span_t *slot = NULL;");
    EMIT("    if (cct_rt_instr_span_count >= 4096U) return NULL;");
    EMIT("    if (cct_rt_instr_span_count == cct_rt_instr_span_cap) {");
    EMIT("        size_t next_cap = cct_rt_instr_span_cap ? cct_rt_instr_span_cap * 2U : 16U;");
    EMIT("        if (next_cap > 4096U) next_cap = 4096U;");
    EMIT("        cct_rt_instr_spans = (cct_rt_instr_span_t*)cct_rt_mem_realloc(cct_rt_instr_spans, (long long)(next_cap * sizeof(cct_rt_instr_span_t)));");
    EMIT("        memset(cct_rt_instr_spans + cct_rt_instr_span_cap, 0, (next_cap - cct_rt_instr_span_cap) * sizeof(cct_rt_instr_span_t));");
    EMIT("        cct_rt_instr_span_cap = next_cap;");
    EMIT("    }");
    EMIT("    slot = &cct_rt_instr_spans[cct_rt_instr_span_count++];");
    EMIT("    memset(slot, 0, sizeof(*slot));");
    EMIT("    return slot;");
    EMIT("}");
    EMIT("");
    EMIT("static cct_rt_instr_span_t *cct_rt_instr_find_span(long long span_id) {");
    EMIT("    size_t i = 0;");
    EMIT("    for (i = 0; i < cct_rt_instr_span_count; i++) {");
    EMIT("        if (cct_rt_instr_spans[i].span_id == span_id) return &cct_rt_instr_spans[i];");
    EMIT("    }");
    EMIT("    return NULL;");
    EMIT("}");
    EMIT("");
    EMIT("static cct_rt_instr_span_t *cct_rt_instr_find_closed_by_index(long long index) {");
    EMIT("    long long seen = 0;");
    EMIT("    size_t i = 0;");
    EMIT("    if (index < 0) return NULL;");
    EMIT("    for (i = 0; i < cct_rt_instr_span_count; i++) {");
    EMIT("        if (!cct_rt_instr_spans[i].closed) continue;");
    EMIT("        if (seen == index) return &cct_rt_instr_spans[i];");
    EMIT("        seen += 1;");
    EMIT("    }");
    EMIT("    return NULL;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_stack_push(long long span_id) {");
    EMIT("    if (cct_rt_instr_active_depth >= (sizeof(cct_rt_instr_active_stack) / sizeof(cct_rt_instr_active_stack[0]))) return;");
    EMIT("    cct_rt_instr_active_stack[cct_rt_instr_active_depth++] = span_id;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_stack_remove(long long span_id) {");
    EMIT("    size_t i = 0;");
    EMIT("    if (cct_rt_instr_active_depth == 0) return;");
    EMIT("    for (i = cct_rt_instr_active_depth; i > 0; i--) {");
    EMIT("        size_t idx = i - 1U;");
    EMIT("        if (cct_rt_instr_active_stack[idx] != span_id) continue;");
    EMIT("        memmove(&cct_rt_instr_active_stack[idx], &cct_rt_instr_active_stack[idx + 1U], (cct_rt_instr_active_depth - idx - 1U) * sizeof(long long));");
    EMIT("        cct_rt_instr_active_depth -= 1U;");
    EMIT("        return;");
    EMIT("    }");
    EMIT("}");
    EMIT("");
    EMIT("static int cct_rt_instr_span_add_attr(cct_rt_instr_span_t *span, const char *key, const char *value) {");
    EMIT("    if (!span) return 0;");
    EMIT("    if (span->attr_count == span->attr_cap) {");
    EMIT("        size_t next_cap = span->attr_cap ? span->attr_cap * 2U : 4U;");
    EMIT("        span->attrs = (cct_rt_instr_attr_t*)cct_rt_mem_realloc(span->attrs, (long long)(next_cap * sizeof(cct_rt_instr_attr_t)));");
    EMIT("        memset(span->attrs + span->attr_cap, 0, (next_cap - span->attr_cap) * sizeof(cct_rt_instr_attr_t));");
    EMIT("        span->attr_cap = next_cap;");
    EMIT("    }");
    EMIT("    span->attrs[span->attr_count].key = cct_rt_instr_dup(key);");
    EMIT("    span->attrs[span->attr_count].value = cct_rt_instr_dup(value);");
    EMIT("    span->attr_count += 1U;");
    EMIT("    return 1;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_is_enabled(void) {");
    EMIT("    return cct_rt_instr_enabled ? 1LL : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_enable(long long mode) {");
    EMIT("    cct_rt_instr_mode_value = mode < 0 ? 0 : mode;");
    EMIT("    cct_rt_instr_enabled = cct_rt_instr_mode_value != 0;");
    EMIT("    if (!cct_rt_instr_enabled) cct_rt_instr_active_depth = 0;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_disable(void) {");
    EMIT("    cct_rt_instr_enabled = 0;");
    EMIT("    cct_rt_instr_mode_value = 0;");
    EMIT("    cct_rt_instr_active_depth = 0;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_mode(void) {");
    EMIT("    return cct_rt_instr_mode_value;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_span_begin(const char *category, const char *name) {");
    EMIT("    cct_rt_instr_span_t *span = NULL;");
    EMIT("    if (!cct_rt_instr_enabled) return 0LL;");
    EMIT("    span = cct_rt_instr_append_span();");
    EMIT("    if (!span) return 0LL;");
    EMIT("    span->span_id = cct_rt_instr_next_span_id++;");
    EMIT("    span->parent_id = cct_rt_instr_active_depth ? cct_rt_instr_active_stack[cct_rt_instr_active_depth - 1U] : 0LL;");
    EMIT("    span->category = cct_rt_instr_dup(category);");
    EMIT("    span->name = cct_rt_instr_dup(name);");
    EMIT("    span->start_us = cct_rt_instr_now_us();");
    EMIT("    span->end_us = 0LL;");
    EMIT("    span->closed = 0;");
    EMIT("    cct_rt_instr_stack_push(span->span_id);");
    EMIT("    return span->span_id;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_span_end(long long span_id) {");
    EMIT("    cct_rt_instr_span_t *span = NULL;");
    EMIT("    long long end_us = 0;");
    EMIT("    if (!cct_rt_instr_enabled || span_id == 0LL) return;");
    EMIT("    span = cct_rt_instr_find_span(span_id);");
    EMIT("    if (!span || span->closed) return;");
    EMIT("    end_us = cct_rt_instr_now_us();");
    EMIT("    if (end_us <= span->start_us) end_us = span->start_us + 1LL;");
    EMIT("    span->end_us = end_us;");
    EMIT("    span->closed = 1;");
    EMIT("    cct_rt_instr_stack_remove(span_id);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_span_attr(long long span_id, const char *key, const char *value) {");
    EMIT("    cct_rt_instr_span_t *span = NULL;");
    EMIT("    if (!cct_rt_instr_enabled || span_id == 0LL) return;");
    EMIT("    span = cct_rt_instr_find_span(span_id);");
    EMIT("    if (!span) return;");
    EMIT("    cct_rt_instr_span_add_attr(span, key, value);");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_event(const char *kind, const char *name) {");
    EMIT("    cct_rt_instr_span_t *span = NULL;");
    EMIT("    long long now_us = 0;");
    EMIT("    if (!cct_rt_instr_enabled) return;");
    EMIT("    span = cct_rt_instr_append_span();");
    EMIT("    if (!span) return;");
    EMIT("    now_us = cct_rt_instr_now_us();");
    EMIT("    span->span_id = cct_rt_instr_next_span_id++;");
    EMIT("    span->parent_id = cct_rt_instr_active_depth ? cct_rt_instr_active_stack[cct_rt_instr_active_depth - 1U] : 0LL;");
    EMIT("    span->category = cct_rt_instr_dup(kind);");
    EMIT("    span->name = cct_rt_instr_dup(name);");
    EMIT("    span->start_us = now_us;");
    EMIT("    span->end_us = now_us + 1LL;");
    EMIT("    span->closed = 1;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_count(void) {");
    EMIT("    long long total = 0;");
    EMIT("    size_t i = 0;");
    EMIT("    for (i = 0; i < cct_rt_instr_span_count; i++) {");
    EMIT("        if (cct_rt_instr_spans[i].closed) total += 1LL;");
    EMIT("    }");
    EMIT("    return total;");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_buffer_clear(void) {");
    EMIT("    cct_rt_instr_reset_state();");
    EMIT("}");
    EMIT("");
    EMIT("static void cct_rt_instr_buffer_discard_closed(void) {");
    EMIT("    size_t i = 0;");
    EMIT("    size_t write_idx = 0;");
    EMIT("    for (i = 0; i < cct_rt_instr_span_count; i++) {");
    EMIT("        if (cct_rt_instr_spans[i].closed) {");
    EMIT("            cct_rt_instr_span_release(&cct_rt_instr_spans[i]);");
    EMIT("            continue;");
    EMIT("        }");
    EMIT("        if (write_idx != i) {");
    EMIT("            cct_rt_instr_spans[write_idx] = cct_rt_instr_spans[i];");
    EMIT("            memset(&cct_rt_instr_spans[i], 0, sizeof(cct_rt_instr_spans[i]));");
    EMIT("        }");
    EMIT("        write_idx += 1U;");
    EMIT("    }");
    EMIT("    cct_rt_instr_span_count = write_idx;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_span_id(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return span ? span->span_id : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_parent_id(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return span ? span->parent_id : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_instr_buffer_name(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return cct_rt_instr_dup(span ? span->name : \"\");");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_instr_buffer_category(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return cct_rt_instr_dup(span ? span->category : \"\");");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_start_us(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return span ? span->start_us : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_end_us(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return span ? span->end_us : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_closed(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return (span && span->closed) ? 1LL : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static long long cct_rt_instr_buffer_attr_count(long long index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    return span ? (long long)span->attr_count : 0LL;");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_instr_buffer_attr_key(long long index, long long attr_index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    if (!span || attr_index < 0 || (size_t)attr_index >= span->attr_count) return cct_rt_instr_dup(\"\");");
    EMIT("    return cct_rt_instr_dup(span->attrs[attr_index].key);");
    EMIT("}");
    EMIT("");
    EMIT("static char *cct_rt_instr_buffer_attr_value(long long index, long long attr_index) {");
    EMIT("    cct_rt_instr_span_t *span = cct_rt_instr_find_closed_by_index(index);");
    EMIT("    if (!span || attr_index < 0 || (size_t)attr_index >= span->attr_count) return cct_rt_instr_dup(\"\");");
    EMIT("    return cct_rt_instr_dup(span->attrs[attr_index].value);");
    EMIT("}");

#undef EMIT
    return true;
}
