/*
 * CCT — Clavicula Turing
 * Runtime TOML Helper Emission
 *
 * FASE 32E: cct/toml host-runtime bridge
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "runtime.h"

bool cct_runtime_emit_toml_helpers(FILE *out) {
    if (!out) return false;

    fputs("typedef enum {\n", out);
    fputs("    CCT_RT_TOML_NONE = 0,\n", out);
    fputs("    CCT_RT_TOML_STRING = 1,\n", out);
    fputs("    CCT_RT_TOML_INTEGER = 2,\n", out);
    fputs("    CCT_RT_TOML_REAL = 3,\n", out);
    fputs("    CCT_RT_TOML_BOOLEAN = 4,\n", out);
    fputs("    CCT_RT_TOML_DATE = 5,\n", out);
    fputs("    CCT_RT_TOML_DATETIME = 6,\n", out);
    fputs("    CCT_RT_TOML_ARRAY_STRING = 7,\n", out);
    fputs("    CCT_RT_TOML_ARRAY_INTEGER = 8,\n", out);
    fputs("    CCT_RT_TOML_ARRAY_REAL = 9,\n", out);
    fputs("    CCT_RT_TOML_ARRAY_BOOLEAN = 10,\n", out);
    fputs("    CCT_RT_TOML_TABLE = 13\n", out);
    fputs("} cct_rt_toml_kind_t;\n\n", out);

    fputs("typedef struct {\n", out);
    fputs("    char *key;\n", out);
    fputs("    int kind;\n", out);
    fputs("    char *text;\n", out);
    fputs("    size_t array_len;\n", out);
    fputs("    char **array_items;\n", out);
    fputs("} cct_rt_toml_entry_t;\n\n", out);

    fputs("typedef struct {\n", out);
    fputs("    size_t len;\n", out);
    fputs("    size_t cap;\n", out);
    fputs("    cct_rt_toml_entry_t *entries;\n", out);
    fputs("} cct_rt_toml_storage_t;\n\n", out);

    fputs("typedef struct {\n", out);
    fputs("    cct_rt_toml_storage_t *storage;\n", out);
    fputs("    char *prefix;\n", out);
    fputs("} cct_rt_toml_doc_t;\n\n", out);

    fputs("static char cct_rt_toml_last_error_buf[256] = {0};\n\n", out);

    fputs("static void cct_rt_toml_clear_error(void) {\n", out);
    fputs("    cct_rt_toml_last_error_buf[0] = '\\0';\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_set_error(const char *msg) {\n", out);
    fputs("    snprintf(cct_rt_toml_last_error_buf, sizeof(cct_rt_toml_last_error_buf), \"%s\", (msg && *msg) ? msg : \"toml failure\");\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_last_error(void) {\n", out);
    fputs("    return cct_rt_toml_last_error_buf;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_dup(const char *s) {\n", out);
    fputs("    size_t n = s ? strlen(s) : 0u;\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);\n", out);
    fputs("    if (n > 0u) memcpy(out_s, s, n);\n", out);
    fputs("    out_s[n] = '\\0';\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_dup_n(const char *s, size_t n) {\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);\n", out);
    fputs("    if (n > 0u) memcpy(out_s, s, n);\n", out);
    fputs("    out_s[n] = '\\0';\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_trim_copy(const char *s) {\n", out);
    fputs("    const char *start = s ? s : \"\";\n", out);
    fputs("    while (*start && isspace((unsigned char)*start)) start++;\n", out);
    fputs("    const char *end = start + strlen(start);\n", out);
    fputs("    while (end > start && isspace((unsigned char)end[-1])) end--;\n", out);
    fputs("    return cct_rt_toml_dup_n(start, (size_t)(end - start));\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_is_date_text(const char *s) {\n", out);
    fputs("    if (!s || strlen(s) != 10u) return 0;\n", out);
    fputs("    return isdigit((unsigned char)s[0]) && isdigit((unsigned char)s[1]) && isdigit((unsigned char)s[2]) && isdigit((unsigned char)s[3]) &&\n", out);
    fputs("           s[4] == '-' && isdigit((unsigned char)s[5]) && isdigit((unsigned char)s[6]) &&\n", out);
    fputs("           s[7] == '-' && isdigit((unsigned char)s[8]) && isdigit((unsigned char)s[9]);\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_is_datetime_text(const char *s) {\n", out);
    fputs("    size_t n = s ? strlen(s) : 0u;\n", out);
    fputs("    if (n != 20u && n != 25u) return 0;\n", out);
    fputs("    if (!(isdigit((unsigned char)s[0]) && isdigit((unsigned char)s[1]) && isdigit((unsigned char)s[2]) && isdigit((unsigned char)s[3]))) return 0;\n", out);
    fputs("    if (s[4] != '-' || s[7] != '-' || s[10] != 'T' || s[13] != ':' || s[16] != ':') return 0;\n", out);
    fputs("    if (!(isdigit((unsigned char)s[5]) && isdigit((unsigned char)s[6]) && isdigit((unsigned char)s[8]) && isdigit((unsigned char)s[9]) && isdigit((unsigned char)s[11]) && isdigit((unsigned char)s[12]) && isdigit((unsigned char)s[14]) && isdigit((unsigned char)s[15]) && isdigit((unsigned char)s[17]) && isdigit((unsigned char)s[18]))) return 0;\n", out);
    fputs("    if (n == 20u) return s[19] == 'Z';\n", out);
    fputs("    return (s[19] == '+' || s[19] == '-') && isdigit((unsigned char)s[20]) && isdigit((unsigned char)s[21]) && s[22] == ':' && isdigit((unsigned char)s[23]) && isdigit((unsigned char)s[24]);\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_remove_underscores(const char *s) {\n", out);
    fputs("    size_t n = s ? strlen(s) : 0u;\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);\n", out);
    fputs("    size_t j = 0u;\n", out);
    fputs("    for (size_t i = 0; i < n; i++) if (s[i] != '_') out_s[j++] = s[i];\n", out);
    fputs("    out_s[j] = '\\0';\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_unescape_basic_string(const char *s) {\n", out);
    fputs("    size_t n = s ? strlen(s) : 0u;\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(n + 1u);\n", out);
    fputs("    size_t j = 0u;\n", out);
    fputs("    for (size_t i = 0; i < n; i++) {\n", out);
    fputs("        if (s[i] == '\\\\' && i + 1u < n) {\n", out);
    fputs("            i++;\n", out);
    fputs("            switch (s[i]) {\n", out);
    fputs("                case 'n': out_s[j++] = '\\n'; break;\n", out);
    fputs("                case 'r': out_s[j++] = '\\r'; break;\n", out);
    fputs("                case 't': out_s[j++] = '\\t'; break;\n", out);
    fputs("                case '\"': out_s[j++] = '\"'; break;\n", out);
    fputs("                case '\\\\': out_s[j++] = '\\\\'; break;\n", out);
    fputs("                default: out_s[j++] = s[i]; break;\n", out);
    fputs("            }\n", out);
    fputs("        } else {\n", out);
    fputs("            out_s[j++] = s[i];\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    out_s[j] = '\\0';\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_strip_comment(const char *line) {\n", out);
    fputs("    size_t n = line ? strlen(line) : 0u;\n", out);
    fputs("    int in_basic = 0;\n", out);
    fputs("    int in_literal = 0;\n", out);
    fputs("    int bracket_depth = 0;\n", out);
    fputs("    for (size_t i = 0; i < n; i++) {\n", out);
    fputs("        char ch = line[i];\n", out);
    fputs("        if (ch == '\\\\' && in_basic && i + 1u < n) { i++; continue; }\n", out);
    fputs("        if (!in_literal && ch == '\"') { in_basic = !in_basic; continue; }\n", out);
    fputs("        if (!in_basic && ch == '\\'') { in_literal = !in_literal; continue; }\n", out);
    fputs("        if (!in_basic && !in_literal) {\n", out);
    fputs("            if (ch == '[') bracket_depth++;\n", out);
    fputs("            else if (ch == ']' && bracket_depth > 0) bracket_depth--;\n", out);
    fputs("            else if (ch == '#' && bracket_depth == 0) return cct_rt_toml_dup_n(line, i);\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    return cct_rt_toml_dup(line ? line : \"\");\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_join_key(const char *prefix, const char *key) {\n", out);
    fputs("    const char *p = prefix ? prefix : \"\";\n", out);
    fputs("    const char *k = key ? key : \"\";\n", out);
    fputs("    if (!p[0]) return cct_rt_toml_dup(k);\n", out);
    fputs("    if (!k[0]) return cct_rt_toml_dup(p);\n", out);
    fputs("    size_t pn = strlen(p), kn = strlen(k);\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(pn + 1u + kn + 1u);\n", out);
    fputs("    memcpy(out_s, p, pn);\n", out);
    fputs("    out_s[pn] = '.';\n", out);
    fputs("    memcpy(out_s + pn + 1u, k, kn);\n", out);
    fputs("    out_s[pn + 1u + kn] = '\\0';\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    fputs("static cct_rt_toml_storage_t *cct_rt_toml_storage_new(void) {\n", out);
    fputs("    cct_rt_toml_storage_t *st = (cct_rt_toml_storage_t*)cct_rt_alloc_or_fail(sizeof(cct_rt_toml_storage_t));\n", out);
    fputs("    st->len = 0u;\n", out);
    fputs("    st->cap = 8u;\n", out);
    fputs("    st->entries = (cct_rt_toml_entry_t*)calloc(st->cap, sizeof(cct_rt_toml_entry_t));\n", out);
    fputs("    if (!st->entries) cct_rt_fail(\"toml storage alloc failed\");\n", out);
    fputs("    return st;\n", out);
    fputs("}\n\n", out);

    fputs("static cct_rt_toml_doc_t *cct_rt_toml_doc_new(cct_rt_toml_storage_t *storage, const char *prefix) {\n", out);
    fputs("    cct_rt_toml_doc_t *doc = (cct_rt_toml_doc_t*)cct_rt_alloc_or_fail(sizeof(cct_rt_toml_doc_t));\n", out);
    fputs("    doc->storage = storage;\n", out);
    fputs("    doc->prefix = cct_rt_toml_dup(prefix ? prefix : \"\");\n", out);
    fputs("    return doc;\n", out);
    fputs("}\n\n", out);

    fputs("static cct_rt_toml_entry_t *cct_rt_toml_find_entry(cct_rt_toml_storage_t *storage, const char *key) {\n", out);
    fputs("    if (!storage || !key) return NULL;\n", out);
    fputs("    for (size_t i = 0; i < storage->len; i++) if (strcmp(storage->entries[i].key, key) == 0) return &storage->entries[i];\n", out);
    fputs("    return NULL;\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_storage_reserve(cct_rt_toml_storage_t *storage, size_t needed) {\n", out);
    fputs("    if (needed <= storage->cap) return;\n", out);
    fputs("    while (storage->cap < needed) storage->cap *= 2u;\n", out);
    fputs("    storage->entries = (cct_rt_toml_entry_t*)realloc(storage->entries, storage->cap * sizeof(cct_rt_toml_entry_t));\n", out);
    fputs("    if (!storage->entries) cct_rt_fail(\"toml storage realloc failed\");\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_set_scalar(cct_rt_toml_storage_t *storage, const char *key, int kind, const char *text) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_find_entry(storage, key);\n", out);
    fputs("    if (!entry) {\n", out);
    fputs("        cct_rt_toml_storage_reserve(storage, storage->len + 1u);\n", out);
    fputs("        entry = &storage->entries[storage->len++];\n", out);
    fputs("        memset(entry, 0, sizeof(*entry));\n", out);
    fputs("        entry->key = cct_rt_toml_dup(key);\n", out);
    fputs("    }\n", out);
    fputs("    entry->kind = kind;\n", out);
    fputs("    entry->text = cct_rt_toml_dup(text ? text : \"\");\n", out);
    fputs("    entry->array_len = 0u;\n", out);
    fputs("    entry->array_items = NULL;\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_set_array(cct_rt_toml_storage_t *storage, const char *key, int kind, char **items, size_t item_count) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_find_entry(storage, key);\n", out);
    fputs("    if (!entry) {\n", out);
    fputs("        cct_rt_toml_storage_reserve(storage, storage->len + 1u);\n", out);
    fputs("        entry = &storage->entries[storage->len++];\n", out);
    fputs("        memset(entry, 0, sizeof(*entry));\n", out);
    fputs("        entry->key = cct_rt_toml_dup(key);\n", out);
    fputs("    }\n", out);
    fputs("    entry->kind = kind;\n", out);
    fputs("    entry->text = NULL;\n", out);
    fputs("    entry->array_len = item_count;\n", out);
    fputs("    entry->array_items = items;\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_parse_scalar_text(const char *value, int *out_kind, char **out_text) {\n", out);
    fputs("    char *trim = cct_rt_toml_trim_copy(value);\n", out);
    fputs("    size_t n = strlen(trim);\n", out);
    fputs("    if (n >= 2u && trim[0] == '\"' && trim[n - 1u] == '\"') {\n", out);
    fputs("        *out_kind = CCT_RT_TOML_STRING;\n", out);
    fputs("        *out_text = cct_rt_toml_unescape_basic_string(cct_rt_toml_dup_n(trim + 1, n - 2u));\n", out);
    fputs("        return 1;\n", out);
    fputs("    }\n", out);
    fputs("    if (n >= 2u && trim[0] == '\\'' && trim[n - 1u] == '\\'') {\n", out);
    fputs("        *out_kind = CCT_RT_TOML_STRING;\n", out);
    fputs("        *out_text = cct_rt_toml_dup_n(trim + 1, n - 2u);\n", out);
    fputs("        return 1;\n", out);
    fputs("    }\n", out);
    fputs("    if (strcmp(trim, \"true\") == 0 || strcmp(trim, \"false\") == 0) {\n", out);
    fputs("        *out_kind = CCT_RT_TOML_BOOLEAN;\n", out);
    fputs("        *out_text = cct_rt_toml_dup(trim);\n", out);
    fputs("        return 1;\n", out);
    fputs("    }\n", out);
    fputs("    if (cct_rt_toml_is_datetime_text(trim)) {\n", out);
    fputs("        *out_kind = CCT_RT_TOML_DATETIME;\n", out);
    fputs("        *out_text = cct_rt_toml_dup(trim);\n", out);
    fputs("        return 1;\n", out);
    fputs("    }\n", out);
    fputs("    if (cct_rt_toml_is_date_text(trim)) {\n", out);
    fputs("        *out_kind = CCT_RT_TOML_DATE;\n", out);
    fputs("        *out_text = cct_rt_toml_dup(trim);\n", out);
    fputs("        return 1;\n", out);
    fputs("    }\n", out);
    fputs("    char *numeric = cct_rt_toml_remove_underscores(trim);\n", out);
    fputs("    char *endptr = NULL;\n", out);
    fputs("    if (strchr(numeric, '.') || strchr(numeric, 'e') || strchr(numeric, 'E')) {\n", out);
    fputs("        (void)strtod(numeric, &endptr);\n", out);
    fputs("        if (endptr && *endptr == '\\0') {\n", out);
    fputs("            *out_kind = CCT_RT_TOML_REAL;\n", out);
    fputs("            *out_text = cct_rt_toml_dup(numeric);\n", out);
    fputs("            return 1;\n", out);
    fputs("        }\n", out);
    fputs("    } else {\n", out);
    fputs("        (void)strtoll(numeric, &endptr, 10);\n", out);
    fputs("        if (endptr && *endptr == '\\0') {\n", out);
    fputs("            *out_kind = CCT_RT_TOML_INTEGER;\n", out);
    fputs("            *out_text = cct_rt_toml_dup(numeric);\n", out);
    fputs("            return 1;\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    cct_rt_toml_set_error(\"toml valor invalido\");\n", out);
    fputs("    return 0;\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_parse_array(const char *value, int *out_kind, char ***out_items, size_t *out_count) {\n", out);
    fputs("    char *trim = cct_rt_toml_trim_copy(value);\n", out);
    fputs("    size_t n = strlen(trim);\n", out);
    fputs("    if (n < 2u || trim[0] != '[' || trim[n - 1u] != ']') return 0;\n", out);
    fputs("    char *inner = cct_rt_toml_dup_n(trim + 1, n - 2u);\n", out);
    fputs("    size_t cap = 4u;\n", out);
    fputs("    size_t len = 0u;\n", out);
    fputs("    char **items = (char**)calloc(cap, sizeof(char*));\n", out);
    fputs("    if (!items) cct_rt_fail(\"toml array alloc failed\");\n", out);
    fputs("    size_t start = 0u;\n", out);
    fputs("    int in_basic = 0;\n", out);
    fputs("    int in_literal = 0;\n", out);
    fputs("    int depth = 0;\n", out);
    fputs("    int item_kind = 0;\n", out);
    fputs("    size_t inner_len = strlen(inner);\n", out);
    fputs("    for (size_t i = 0; i <= inner_len; i++) {\n", out);
    fputs("        char ch = (i < inner_len) ? inner[i] : ',';\n", out);
    fputs("        if (ch == '\\\\' && in_basic && i + 1u < inner_len) { i++; continue; }\n", out);
    fputs("        if (!in_literal && ch == '\"') { in_basic = !in_basic; continue; }\n", out);
    fputs("        if (!in_basic && ch == '\\'') { in_literal = !in_literal; continue; }\n", out);
    fputs("        if (!in_basic && !in_literal) {\n", out);
    fputs("            if (ch == '[') depth++;\n", out);
    fputs("            else if (ch == ']' && depth > 0) depth--;\n", out);
    fputs("            else if (ch == ',' && depth == 0) {\n", out);
    fputs("                char *item_text = cct_rt_toml_dup_n(inner + start, i - start);\n", out);
    fputs("                char *item_trim = cct_rt_toml_trim_copy(item_text);\n", out);
    fputs("                if (strlen(item_trim) > 0u) {\n", out);
    fputs("                    int scalar_kind = 0;\n", out);
    fputs("                    char *scalar_text = NULL;\n", out);
    fputs("                    if (!cct_rt_toml_parse_scalar_text(item_trim, &scalar_kind, &scalar_text)) return 0;\n", out);
    fputs("                    if (scalar_kind == CCT_RT_TOML_DATE || scalar_kind == CCT_RT_TOML_DATETIME) {\n", out);
    fputs("                        cct_rt_toml_set_error(\"toml arrays de datas ainda nao suportadas\");\n", out);
    fputs("                        return 0;\n", out);
    fputs("                    }\n", out);
    fputs("                    if (item_kind == 0) item_kind = scalar_kind;\n", out);
    fputs("                    if (item_kind != scalar_kind) {\n", out);
    fputs("                        cct_rt_toml_set_error(\"toml arrays heterogeneos nao suportados\");\n", out);
    fputs("                        return 0;\n", out);
    fputs("                    }\n", out);
    fputs("                    if (len == cap) {\n", out);
    fputs("                        cap *= 2u;\n", out);
    fputs("                        items = (char**)realloc(items, cap * sizeof(char*));\n", out);
    fputs("                        if (!items) cct_rt_fail(\"toml array realloc failed\");\n", out);
    fputs("                    }\n", out);
    fputs("                    items[len++] = scalar_text;\n", out);
    fputs("                }\n", out);
    fputs("                start = i + 1u;\n", out);
    fputs("            }\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    if (item_kind == 0) item_kind = CCT_RT_TOML_ARRAY_STRING;\n", out);
    fputs("    if (item_kind == CCT_RT_TOML_STRING) *out_kind = CCT_RT_TOML_ARRAY_STRING;\n", out);
    fputs("    else if (item_kind == CCT_RT_TOML_INTEGER) *out_kind = CCT_RT_TOML_ARRAY_INTEGER;\n", out);
    fputs("    else if (item_kind == CCT_RT_TOML_REAL) *out_kind = CCT_RT_TOML_ARRAY_REAL;\n", out);
    fputs("    else if (item_kind == CCT_RT_TOML_BOOLEAN) *out_kind = CCT_RT_TOML_ARRAY_BOOLEAN;\n", out);
    fputs("    else return 0;\n", out);
    fputs("    *out_items = items;\n", out);
    fputs("    *out_count = len;\n", out);
    fputs("    return 1;\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_split_key_value(const char *line, char **out_key, char **out_value) {\n", out);
    fputs("    int in_basic = 0;\n", out);
    fputs("    int in_literal = 0;\n", out);
    fputs("    int bracket_depth = 0;\n", out);
    fputs("    size_t n = line ? strlen(line) : 0u;\n", out);
    fputs("    for (size_t i = 0; i < n; i++) {\n", out);
    fputs("        char ch = line[i];\n", out);
    fputs("        if (ch == '\\\\' && in_basic && i + 1u < n) { i++; continue; }\n", out);
    fputs("        if (!in_literal && ch == '\"') { in_basic = !in_basic; continue; }\n", out);
    fputs("        if (!in_basic && ch == '\\'') { in_literal = !in_literal; continue; }\n", out);
    fputs("        if (!in_basic && !in_literal) {\n", out);
    fputs("            if (ch == '[') bracket_depth++;\n", out);
    fputs("            else if (ch == ']' && bracket_depth > 0) bracket_depth--;\n", out);
    fputs("            else if (ch == '=' && bracket_depth == 0) {\n", out);
    fputs("                *out_key = cct_rt_toml_trim_copy(cct_rt_toml_dup_n(line, i));\n", out);
    fputs("                *out_value = cct_rt_toml_trim_copy(line + i + 1u);\n", out);
    fputs("                return 1;\n", out);
    fputs("            }\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    return 0;\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_parse_from_string(const char *content) {\n", out);
    fputs("    cct_rt_toml_clear_error();\n", out);
    fputs("    cct_rt_toml_storage_t *storage = cct_rt_toml_storage_new();\n", out);
    fputs("    cct_rt_toml_doc_t *doc = cct_rt_toml_doc_new(storage, \"\");\n", out);
    fputs("    char *section = cct_rt_toml_dup(\"\");\n", out);
    fputs("    const char *cursor = content ? content : \"\";\n", out);
    fputs("    while (*cursor) {\n", out);
    fputs("        const char *line_end = strchr(cursor, '\\n');\n", out);
    fputs("        size_t line_len = line_end ? (size_t)(line_end - cursor) : strlen(cursor);\n", out);
    fputs("        char *raw_line = cct_rt_toml_dup_n(cursor, line_len);\n", out);
    fputs("        char *line = cct_rt_toml_strip_comment(raw_line);\n", out);
    fputs("        char *trim = cct_rt_toml_trim_copy(line);\n", out);
    fputs("        if (trim[0] != '\\0') {\n", out);
    fputs("            size_t trim_len = strlen(trim);\n", out);
    fputs("            if (trim[0] == '[' && trim[trim_len - 1u] == ']') {\n", out);
    fputs("                section = cct_rt_toml_trim_copy(cct_rt_toml_dup_n(trim + 1, trim_len - 2u));\n", out);
    fputs("            } else {\n", out);
    fputs("                char *key = NULL;\n", out);
    fputs("                char *value = NULL;\n", out);
    fputs("                if (!cct_rt_toml_split_key_value(trim, &key, &value)) {\n", out);
    fputs("                    cct_rt_toml_set_error(\"toml linha invalida\");\n", out);
    fputs("                    return 0LL;\n", out);
    fputs("                }\n", out);
    fputs("                if (strncmp(value, \"\\\"\\\"\\\"\", 3) == 0) {\n", out);
    fputs("                    char *builder = cct_rt_toml_dup(value);\n", out);
    fputs("                    while (1) {\n", out);
    fputs("                        char *close = strstr(builder + 3, \"\\\"\\\"\\\"\");\n", out);
    fputs("                        if (close) break;\n", out);
    fputs("                        if (!line_end) { cct_rt_toml_set_error(\"toml string multiline sem fechamento\"); return 0LL; }\n", out);
    fputs("                        cursor = line_end + 1u;\n", out);
    fputs("                        line_end = strchr(cursor, '\\n');\n", out);
    fputs("                        line_len = line_end ? (size_t)(line_end - cursor) : strlen(cursor);\n", out);
    fputs("                        char *extra = cct_rt_toml_dup_n(cursor, line_len);\n", out);
    fputs("                        size_t old_len = strlen(builder);\n", out);
    fputs("                        size_t extra_len = strlen(extra);\n", out);
    fputs("                        builder = (char*)realloc(builder, old_len + 1u + extra_len + 1u);\n", out);
    fputs("                        if (!builder) cct_rt_fail(\"toml multiline realloc failed\");\n", out);
    fputs("                        builder[old_len] = '\\n';\n", out);
    fputs("                        memcpy(builder + old_len + 1u, extra, extra_len + 1u);\n", out);
    fputs("                    }\n", out);
    fputs("                    char *close = strstr(builder + 3, \"\\\"\\\"\\\"\");\n", out);
    fputs("                    char *payload = cct_rt_toml_dup_n(builder + 3, (size_t)(close - (builder + 3)));\n", out);
    fputs("                    value = cct_rt_toml_dup(payload);\n", out);
    fputs("                    char *full_key = cct_rt_toml_join_key(section, key);\n", out);
    fputs("                    cct_rt_toml_set_scalar(storage, full_key, CCT_RT_TOML_STRING, payload);\n", out);
    fputs("                } else {\n", out);
    fputs("                    char *full_key = cct_rt_toml_join_key(section, key);\n", out);
    fputs("                    int array_kind = 0;\n", out);
    fputs("                    char **array_items = NULL;\n", out);
    fputs("                    size_t array_len = 0u;\n", out);
    fputs("                    if (cct_rt_toml_parse_array(value, &array_kind, &array_items, &array_len)) {\n", out);
    fputs("                        cct_rt_toml_set_array(storage, full_key, array_kind, array_items, array_len);\n", out);
    fputs("                    } else {\n", out);
    fputs("                        int scalar_kind = 0;\n", out);
    fputs("                        char *scalar_text = NULL;\n", out);
    fputs("                        if (!cct_rt_toml_parse_scalar_text(value, &scalar_kind, &scalar_text)) return 0LL;\n", out);
    fputs("                        cct_rt_toml_set_scalar(storage, full_key, scalar_kind, scalar_text);\n", out);
    fputs("                    }\n", out);
    fputs("                }\n", out);
    fputs("            }\n", out);
    fputs("        }\n", out);
    fputs("        if (!line_end) break;\n", out);
    fputs("        cursor = line_end + 1u;\n", out);
    fputs("    }\n", out);
    fputs("    return (long long)(intptr_t)doc;\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_parse(const char *content) {\n", out);
    fputs("    return cct_rt_toml_parse_from_string(content);\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_parse_file(const char *path) {\n", out);
    fputs("    FILE *fp = fopen(path ? path : \"\", \"rb\");\n", out);
    fputs("    if (!fp) {\n", out);
    fputs("        cct_rt_toml_set_error(\"toml nao conseguiu abrir arquivo\");\n", out);
    fputs("        return 0LL;\n", out);
    fputs("    }\n", out);
    fputs("    if (fseek(fp, 0, SEEK_END) != 0) { fclose(fp); cct_rt_toml_set_error(\"toml nao conseguiu posicionar arquivo\"); return 0LL; }\n", out);
    fputs("    long size = ftell(fp);\n", out);
    fputs("    if (size < 0) { fclose(fp); cct_rt_toml_set_error(\"toml nao conseguiu medir arquivo\"); return 0LL; }\n", out);
    fputs("    if (fseek(fp, 0, SEEK_SET) != 0) { fclose(fp); cct_rt_toml_set_error(\"toml nao conseguiu ler arquivo\"); return 0LL; }\n", out);
    fputs("    char *buf = (char*)cct_rt_alloc_or_fail((size_t)size + 1u);\n", out);
    fputs("    size_t got = fread(buf, 1u, (size_t)size, fp);\n", out);
    fputs("    fclose(fp);\n", out);
    fputs("    buf[got] = '\\0';\n", out);
    fputs("    return cct_rt_toml_parse_from_string(buf);\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_doc_resolve_key(cct_rt_toml_doc_t *doc, const char *key) {\n", out);
    fputs("    return cct_rt_toml_join_key((doc && doc->prefix) ? doc->prefix : \"\", key ? key : \"\");\n", out);
    fputs("}\n\n", out);

    fputs("static cct_rt_toml_entry_t *cct_rt_toml_doc_entry(cct_rt_toml_doc_t *doc, const char *key) {\n", out);
    fputs("    if (!doc || !doc->storage) return NULL;\n", out);
    fputs("    char *full_key = cct_rt_toml_doc_resolve_key(doc, key);\n", out);
    fputs("    return cct_rt_toml_find_entry(doc->storage, full_key);\n", out);
    fputs("}\n\n", out);

    fputs("static int cct_rt_toml_type(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_doc_t *doc = (cct_rt_toml_doc_t*)(intptr_t)doc_handle;\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry(doc, key);\n", out);
    fputs("    if (entry) return entry->kind;\n", out);
    fputs("    char *full_key = cct_rt_toml_doc_resolve_key(doc, key);\n", out);
    fputs("    size_t prefix_len = strlen(full_key);\n", out);
    fputs("    for (size_t i = 0; doc && doc->storage && i < doc->storage->len; i++) {\n", out);
    fputs("        if (strncmp(doc->storage->entries[i].key, full_key, prefix_len) == 0 && doc->storage->entries[i].key[prefix_len] == '.') return CCT_RT_TOML_TABLE;\n", out);
    fputs("    }\n", out);
    fputs("    return CCT_RT_TOML_NONE;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_get_string(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    return (entry && entry->text) ? cct_rt_toml_dup(entry->text) : cct_rt_toml_dup(\"\");\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_get_int(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    return (entry && entry->text) ? strtoll(entry->text, NULL, 10) : 0LL;\n", out);
    fputs("}\n\n", out);

    fputs("static double cct_rt_toml_get_real(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    return (entry && entry->text) ? strtod(entry->text, NULL) : 0.0;\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_get_bool(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    return (entry && entry->text && strcmp(entry->text, \"true\") == 0) ? 1LL : 0LL;\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_get_subdoc(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_doc_t *doc = (cct_rt_toml_doc_t*)(intptr_t)doc_handle;\n", out);
    fputs("    char *full_key = cct_rt_toml_doc_resolve_key(doc, key);\n", out);
    fputs("    return (long long)(intptr_t)cct_rt_toml_doc_new(doc ? doc->storage : NULL, full_key);\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_array_len(long long doc_handle, const char *key) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    return entry ? (long long)entry->array_len : -1LL;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_array_item_string(long long doc_handle, const char *key, long long index) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    if (!entry || index < 0 || (size_t)index >= entry->array_len) return cct_rt_toml_dup(\"\");\n", out);
    fputs("    return cct_rt_toml_dup(entry->array_items[index]);\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_array_item_int(long long doc_handle, const char *key, long long index) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    if (!entry || index < 0 || (size_t)index >= entry->array_len) return 0LL;\n", out);
    fputs("    return strtoll(entry->array_items[index], NULL, 10);\n", out);
    fputs("}\n\n", out);

    fputs("static double cct_rt_toml_array_item_real(long long doc_handle, const char *key, long long index) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    if (!entry || index < 0 || (size_t)index >= entry->array_len) return 0.0;\n", out);
    fputs("    return strtod(entry->array_items[index], NULL);\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_array_item_bool(long long doc_handle, const char *key, long long index) {\n", out);
    fputs("    cct_rt_toml_entry_t *entry = cct_rt_toml_doc_entry((cct_rt_toml_doc_t*)(intptr_t)doc_handle, key);\n", out);
    fputs("    if (!entry || index < 0 || (size_t)index >= entry->array_len) return 0LL;\n", out);
    fputs("    return strcmp(entry->array_items[index], \"true\") == 0 ? 1LL : 0LL;\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_expand_env_text(const char *text) {\n", out);
    fputs("    char *result = cct_rt_toml_dup(text ? text : \"\");\n", out);
    fputs("    while (1) {\n", out);
    fputs("        char *start = strstr(result, \"${\");\n", out);
    fputs("        if (!start) break;\n", out);
    fputs("        char *end = strchr(start + 2, '}');\n", out);
    fputs("        if (!end) break;\n", out);
    fputs("        char *name = cct_rt_toml_dup_n(start + 2, (size_t)(end - (start + 2)));\n", out);
    fputs("        const char *value = getenv(name);\n", out);
    fputs("        size_t before_len = (size_t)(start - result);\n", out);
    fputs("        size_t value_len = strlen(value ? value : \"\");\n", out);
    fputs("        size_t after_len = strlen(end + 1);\n", out);
    fputs("        char *merged = (char*)cct_rt_alloc_or_fail(before_len + value_len + after_len + 1u);\n", out);
    fputs("        memcpy(merged, result, before_len);\n", out);
    fputs("        if (value_len > 0u) memcpy(merged + before_len, value, value_len);\n", out);
    fputs("        memcpy(merged + before_len + value_len, end + 1, after_len + 1u);\n", out);
    fputs("        result = merged;\n", out);
    fputs("    }\n", out);
    fputs("    return result;\n", out);
    fputs("}\n\n", out);

    fputs("static long long cct_rt_toml_expand_env(long long doc_handle) {\n", out);
    fputs("    cct_rt_toml_doc_t *doc = (cct_rt_toml_doc_t*)(intptr_t)doc_handle;\n", out);
    fputs("    cct_rt_toml_storage_t *storage = cct_rt_toml_storage_new();\n", out);
    fputs("    for (size_t i = 0; doc && doc->storage && i < doc->storage->len; i++) {\n", out);
    fputs("        cct_rt_toml_entry_t *entry = &doc->storage->entries[i];\n", out);
    fputs("        if (entry->kind == CCT_RT_TOML_STRING) {\n", out);
    fputs("            char *expanded = cct_rt_toml_expand_env_text(entry->text);\n", out);
    fputs("            cct_rt_toml_set_scalar(storage, entry->key, entry->kind, expanded);\n", out);
    fputs("        } else if (entry->kind == CCT_RT_TOML_ARRAY_STRING) {\n", out);
    fputs("            char **items = (char**)calloc(entry->array_len ? entry->array_len : 1u, sizeof(char*));\n", out);
    fputs("            if (!items) cct_rt_fail(\"toml expand env alloc failed\");\n", out);
    fputs("            for (size_t j = 0; j < entry->array_len; j++) items[j] = cct_rt_toml_expand_env_text(entry->array_items[j]);\n", out);
    fputs("            cct_rt_toml_set_array(storage, entry->key, entry->kind, items, entry->array_len);\n", out);
    fputs("        } else if (entry->array_len > 0u) {\n", out);
    fputs("            char **items = (char**)calloc(entry->array_len ? entry->array_len : 1u, sizeof(char*));\n", out);
    fputs("            if (!items) cct_rt_fail(\"toml expand env alloc failed\");\n", out);
    fputs("            for (size_t j = 0; j < entry->array_len; j++) items[j] = cct_rt_toml_dup(entry->array_items[j]);\n", out);
    fputs("            cct_rt_toml_set_array(storage, entry->key, entry->kind, items, entry->array_len);\n", out);
    fputs("        } else {\n", out);
    fputs("            cct_rt_toml_set_scalar(storage, entry->key, entry->kind, entry->text ? entry->text : \"\");\n", out);
    fputs("        }\n", out);
    fputs("    }\n", out);
    fputs("    return (long long)(intptr_t)cct_rt_toml_doc_new(storage, (doc && doc->prefix) ? doc->prefix : \"\");\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_append(char **buffer, size_t *len, size_t *cap, const char *text) {\n", out);
    fputs("    size_t add = strlen(text ? text : \"\");\n", out);
    fputs("    while (*len + add + 1u > *cap) {\n", out);
    fputs("        *cap *= 2u;\n", out);
    fputs("        *buffer = (char*)realloc(*buffer, *cap);\n", out);
    fputs("        if (!*buffer) cct_rt_fail(\"toml stringify realloc failed\");\n", out);
    fputs("    }\n", out);
    fputs("    memcpy(*buffer + *len, text ? text : \"\", add);\n", out);
    fputs("    *len += add;\n", out);
    fputs("    (*buffer)[*len] = '\\0';\n", out);
    fputs("}\n\n", out);

    fputs("static void cct_rt_toml_append_escaped_string(char **buffer, size_t *len, size_t *cap, const char *text) {\n", out);
    fputs("    cct_rt_toml_append(buffer, len, cap, \"\\\"\");\n", out);
    fputs("    for (const unsigned char *p = (const unsigned char*)(text ? text : \"\"); *p; ++p) {\n", out);
    fputs("        char tmp[3] = {0, 0, 0};\n", out);
    fputs("        if (*p == '\\n') cct_rt_toml_append(buffer, len, cap, \"\\\\n\");\n", out);
    fputs("        else if (*p == '\\r') cct_rt_toml_append(buffer, len, cap, \"\\\\r\");\n", out);
    fputs("        else if (*p == '\\t') cct_rt_toml_append(buffer, len, cap, \"\\\\t\");\n", out);
    fputs("        else if (*p == '\\\\') cct_rt_toml_append(buffer, len, cap, \"\\\\\\\\\");\n", out);
    fputs("        else if (*p == '\"') cct_rt_toml_append(buffer, len, cap, \"\\\\\\\"\");\n", out);
    fputs("        else { tmp[0] = (char)*p; cct_rt_toml_append(buffer, len, cap, tmp); }\n", out);
    fputs("    }\n", out);
    fputs("    cct_rt_toml_append(buffer, len, cap, \"\\\"\");\n", out);
    fputs("}\n\n", out);

    fputs("static char *cct_rt_toml_stringify(long long doc_handle) {\n", out);
    fputs("    cct_rt_toml_doc_t *doc = (cct_rt_toml_doc_t*)(intptr_t)doc_handle;\n", out);
    fputs("    size_t cap = 512u;\n", out);
    fputs("    size_t len = 0u;\n", out);
    fputs("    char *out_s = (char*)cct_rt_alloc_or_fail(cap);\n", out);
    fputs("    out_s[0] = '\\0';\n", out);
    fputs("    const char *active_prefix = (doc && doc->prefix) ? doc->prefix : \"\";\n", out);
    fputs("    size_t active_prefix_len = strlen(active_prefix);\n", out);
    fputs("    char *current_table = cct_rt_toml_dup(\"__root__\");\n", out);
    fputs("    for (size_t i = 0; doc && doc->storage && i < doc->storage->len; i++) {\n", out);
    fputs("        cct_rt_toml_entry_t *entry = &doc->storage->entries[i];\n", out);
    fputs("        if (active_prefix_len > 0u) {\n", out);
    fputs("            if (strncmp(entry->key, active_prefix, active_prefix_len) != 0) continue;\n", out);
    fputs("            if (entry->key[active_prefix_len] != '\\0' && entry->key[active_prefix_len] != '.') continue;\n", out);
    fputs("        }\n", out);
    fputs("        const char *relative = entry->key + active_prefix_len;\n", out);
    fputs("        if (*relative == '.') relative++;\n", out);
    fputs("        const char *last_dot = strrchr(relative, '.');\n", out);
    fputs("        char *table = NULL;\n", out);
    fputs("        const char *leaf = relative;\n", out);
    fputs("        if (last_dot) {\n", out);
    fputs("            table = cct_rt_toml_dup_n(relative, (size_t)(last_dot - relative));\n", out);
    fputs("            leaf = last_dot + 1;\n", out);
    fputs("        } else {\n", out);
    fputs("            table = cct_rt_toml_dup(\"\");\n", out);
    fputs("        }\n", out);
    fputs("        if (strcmp(table, current_table) != 0) {\n", out);
    fputs("            current_table = table;\n", out);
    fputs("            if (table[0]) {\n", out);
    fputs("                cct_rt_toml_append(&out_s, &len, &cap, \"\\n[\");\n", out);
    fputs("                cct_rt_toml_append(&out_s, &len, &cap, table);\n", out);
    fputs("                cct_rt_toml_append(&out_s, &len, &cap, \"]\\n\");\n", out);
    fputs("            }\n", out);
    fputs("        }\n", out);
    fputs("        cct_rt_toml_append(&out_s, &len, &cap, leaf);\n", out);
    fputs("        cct_rt_toml_append(&out_s, &len, &cap, \" = \");\n", out);
    fputs("        if (entry->kind == CCT_RT_TOML_STRING) cct_rt_toml_append_escaped_string(&out_s, &len, &cap, entry->text);\n", out);
    fputs("        else if (entry->kind == CCT_RT_TOML_ARRAY_STRING) {\n", out);
    fputs("            cct_rt_toml_append(&out_s, &len, &cap, \"[\");\n", out);
    fputs("            for (size_t j = 0; j < entry->array_len; j++) {\n", out);
    fputs("                if (j > 0u) cct_rt_toml_append(&out_s, &len, &cap, \", \");\n", out);
    fputs("                cct_rt_toml_append_escaped_string(&out_s, &len, &cap, entry->array_items[j]);\n", out);
    fputs("            }\n", out);
    fputs("            cct_rt_toml_append(&out_s, &len, &cap, \"]\");\n", out);
    fputs("        } else if (entry->kind >= CCT_RT_TOML_ARRAY_STRING && entry->kind <= CCT_RT_TOML_ARRAY_BOOLEAN) {\n", out);
    fputs("            cct_rt_toml_append(&out_s, &len, &cap, \"[\");\n", out);
    fputs("            for (size_t j = 0; j < entry->array_len; j++) {\n", out);
    fputs("                if (j > 0u) cct_rt_toml_append(&out_s, &len, &cap, \", \");\n", out);
    fputs("                cct_rt_toml_append(&out_s, &len, &cap, entry->array_items[j]);\n", out);
    fputs("            }\n", out);
    fputs("            cct_rt_toml_append(&out_s, &len, &cap, \"]\");\n", out);
    fputs("        } else if (entry->text) {\n", out);
    fputs("            cct_rt_toml_append(&out_s, &len, &cap, entry->text);\n", out);
    fputs("        }\n", out);
    fputs("        cct_rt_toml_append(&out_s, &len, &cap, \"\\n\");\n", out);
    fputs("    }\n", out);
    fputs("    return out_s;\n", out);
    fputs("}\n\n", out);

    return true;
}
