/* generated by cct bootstrap codegen */

#include <string.h>
#include <stdlib.h>
void *cct_rt_option_some(const void *value_ptr, size_t value_size);
void *cct_rt_option_none(size_t value_size);
long long cct_rt_option_is_some(const void *opt_ptr);
long long cct_rt_option_is_none(const void *opt_ptr);
void *cct_rt_option_unwrap_ptr(void *opt_ptr);
void *cct_rt_option_expect_ptr(void *opt_ptr, const char *message);
void cct_rt_option_free(void *opt_ptr);
void *cct_rt_result_ok(const void *value_ptr, size_t ok_size, size_t err_size);
void *cct_rt_result_err(const void *err_ptr, size_t ok_size, size_t err_size);
long long cct_rt_result_is_ok(const void *res_ptr);
long long cct_rt_result_is_err(const void *res_ptr);
void *cct_rt_result_unwrap_ptr(void *res_ptr);
void *cct_rt_result_unwrap_err_ptr(void *res_ptr);
void *cct_rt_result_expect_ptr(void *res_ptr, const char *message);
void cct_rt_result_free(void *res_ptr);
void *cct_rt_map_init(long long key_size, long long value_size);
void cct_rt_map_free(void *map_ptr);
void cct_rt_map_insert(void *map_ptr, const void *key_ptr, const void *value_ptr);
long long cct_rt_map_remove(void *map_ptr, const void *key_ptr);
void *cct_rt_map_get_ptr(void *map_ptr, const void *key_ptr);
long long cct_rt_map_contains(void *map_ptr, const void *key_ptr);
long long cct_rt_map_len(void *map_ptr);
long long cct_rt_map_is_empty(void *map_ptr);
long long cct_rt_map_capacity(void *map_ptr);
void cct_rt_map_clear(void *map_ptr);
void cct_rt_map_reserve(void *map_ptr, long long additional);
void *cct_rt_map_copy(void *map_ptr);
void *cct_rt_map_keys(void *map_ptr, long long key_size);
void *cct_rt_map_values(void *map_ptr, long long value_size);
void cct_rt_map_merge(void *dest_ptr, void *src_ptr);
void *cct_rt_map_iter_begin(void *map_ptr);
long long cct_rt_map_iter_next(void *iter_ptr, void **key_out, void **value_out);
void cct_rt_map_iter_end(void *iter_ptr);
void *cct_rt_set_init(long long item_size);
void cct_rt_set_free(void *set_ptr);
long long cct_rt_set_insert(void *set_ptr, const void *item_ptr);
long long cct_rt_set_remove(void *set_ptr, const void *item_ptr);
long long cct_rt_set_contains(void *set_ptr, const void *item_ptr);
long long cct_rt_set_len(void *set_ptr);
long long cct_rt_set_is_empty(void *set_ptr);
void cct_rt_set_clear(void *set_ptr);
void *cct_rt_set_union(void *a_ptr, void *b_ptr, long long item_size);
void *cct_rt_set_intersection(void *a_ptr, void *b_ptr, long long item_size);
void *cct_rt_set_difference(void *a_ptr, void *b_ptr, long long item_size);
void *cct_rt_set_symmetric_difference(void *a_ptr, void *b_ptr, long long item_size);
long long cct_rt_set_is_subset(void *a_ptr, void *b_ptr, long long item_size);
long long cct_rt_set_equals(void *a_ptr, void *b_ptr, long long item_size);
void *cct_rt_set_copy(void *set_ptr, long long item_size);
void *cct_rt_set_to_fluxus(void *set_ptr, long long item_size);
void cct_rt_set_reserve(void *set_ptr, long long additional);
long long cct_rt_set_capacity(void *set_ptr);
void *cct_rt_set_iter_begin(void *set_ptr);
long long cct_rt_set_iter_next(void *iter_ptr, void **item_out);
void cct_rt_set_iter_end(void *iter_ptr);
void cct_rt_args_init(int argc, char **argv);

static char cct_boot_str_0[] = "EOF";
static char cct_boot_str_1[] = "INVALID";
static char cct_boot_str_2[] = "IDENTIFIER";
static char cct_boot_str_3[] = "INTEGER";
static char cct_boot_str_4[] = "REAL";
static char cct_boot_str_5[] = "STRING";
static char cct_boot_str_6[] = "INCIPIT";
static char cct_boot_str_7[] = "EXPLICIT";
static char cct_boot_str_8[] = "RITUALE";
static char cct_boot_str_9[] = "EVOCA";
static char cct_boot_str_10[] = "VINCIRE";
static char cct_boot_str_11[] = "DIMITTE";
static char cct_boot_str_12[] = "CIRCULUS";
static char cct_boot_str_13[] = "CONIURA";
static char cct_boot_str_14[] = "CODEX";
static char cct_boot_str_15[] = "SIGILLUM";
static char cct_boot_str_16[] = "PACTUM";
static char cct_boot_str_17[] = "ORDO";
static char cct_boot_str_18[] = "ARCANUM";
static char cct_boot_str_19[] = "GENUS";
static char cct_boot_str_20[] = "ADVOCARE";
static char cct_boot_str_21[] = "CONSTANS";
static char cct_boot_str_22[] = "FIN";
static char cct_boot_str_23[] = "SI";
static char cct_boot_str_24[] = "ALITER";
static char cct_boot_str_25[] = "QUANDO";
static char cct_boot_str_26[] = "CASO";
static char cct_boot_str_27[] = "SENAO";
static char cct_boot_str_28[] = "DUM";
static char cct_boot_str_29[] = "DONEC";
static char cct_boot_str_30[] = "REPETE";
static char cct_boot_str_31[] = "ITERUM";
static char cct_boot_str_32[] = "PRO";
static char cct_boot_str_33[] = "FRANGE";
static char cct_boot_str_34[] = "RECEDE";
static char cct_boot_str_35[] = "REDDE";
static char cct_boot_str_36[] = "TRANSITUS";
static char cct_boot_str_37[] = "TEMPTA";
static char cct_boot_str_38[] = "CAPE";
static char cct_boot_str_39[] = "SEMPER";
static char cct_boot_str_40[] = "IACE";
static char cct_boot_str_41[] = "FRACTUM";
static char cct_boot_str_42[] = "ET";
static char cct_boot_str_43[] = "VEL";
static char cct_boot_str_44[] = "NON";
static char cct_boot_str_45[] = "ET_BIT";
static char cct_boot_str_46[] = "VEL_BIT";
static char cct_boot_str_47[] = "XOR";
static char cct_boot_str_48[] = "NON_BIT";
static char cct_boot_str_49[] = "SINISTER";
static char cct_boot_str_50[] = "DEXTER";
static char cct_boot_str_51[] = "REX";
static char cct_boot_str_52[] = "DUX";
static char cct_boot_str_53[] = "COMES";
static char cct_boot_str_54[] = "MILES";
static char cct_boot_str_55[] = "UMBRA";
static char cct_boot_str_56[] = "FLAMMA";
static char cct_boot_str_57[] = "VERBUM";
static char cct_boot_str_58[] = "VERUM";
static char cct_boot_str_59[] = "FALSUM";
static char cct_boot_str_60[] = "NIHIL";
static char cct_boot_str_61[] = "SPECULUM";
static char cct_boot_str_62[] = "SERIES";
static char cct_boot_str_63[] = "FLUXUS";
static char cct_boot_str_64[] = "VOLATILE";
static char cct_boot_str_65[] = "OBSECRO";
static char cct_boot_str_66[] = "ANUR";
static char cct_boot_str_67[] = "MENSURA";
static char cct_boot_str_68[] = "MOLDE";
static char cct_boot_str_69[] = "DE";
static char cct_boot_str_70[] = "AD";
static char cct_boot_str_71[] = "IN";
static char cct_boot_str_72[] = "GRADUS";
static char cct_boot_str_73[] = "PLUS";
static char cct_boot_str_74[] = "MINUS";
static char cct_boot_str_75[] = "STAR";
static char cct_boot_str_76[] = "STAR_STAR";
static char cct_boot_str_77[] = "SLASH";
static char cct_boot_str_78[] = "SLASH_SLASH";
static char cct_boot_str_79[] = "PERCENT";
static char cct_boot_str_80[] = "PERCENT_PERCENT";
static char cct_boot_str_81[] = "EQ_EQ";
static char cct_boot_str_82[] = "BANG_EQ";
static char cct_boot_str_83[] = "LESS";
static char cct_boot_str_84[] = "LESS_EQ";
static char cct_boot_str_85[] = "GREATER";
static char cct_boot_str_86[] = "GREATER_EQ";
static char cct_boot_str_87[] = "EQ";
static char cct_boot_str_88[] = "PLUS_PLUS";
static char cct_boot_str_89[] = "MINUS_MINUS";
static char cct_boot_str_90[] = "LPAREN";
static char cct_boot_str_91[] = "RPAREN";
static char cct_boot_str_92[] = "LBRACE";
static char cct_boot_str_93[] = "RBRACE";
static char cct_boot_str_94[] = "LBRACKET";
static char cct_boot_str_95[] = "RBRACKET";
static char cct_boot_str_96[] = "COMMA";
static char cct_boot_str_97[] = "DOT";
static char cct_boot_str_98[] = "COLON";
static char cct_boot_str_99[] = "SEMICOLON";
static char cct_boot_str_100[] = "QUESTION";
static char cct_boot_str_101[] = "UNKNOWN";
static char cct_boot_str_102[] = "examples/cadastro_sqlite_app/data";
static char cct_boot_str_103[] = "examples/cadastro_sqlite_app/data/alunos.sqlite";
static char cct_boot_str_104[] = "'";
static char cct_boot_str_105[] = "''";
static char cct_boot_str_106[] = "CREATE TABLE IF NOT EXISTS alunos(id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, classe TEXT NOT NULL, media REAL NOT NULL);";
static char cct_boot_str_107[] = "SELECT id, nome, classe, media FROM alunos ORDER BY id;";
static char cct_boot_str_108[] = "%";
static char cct_boot_str_109[] = "SELECT id, nome, classe, media FROM alunos WHERE nome LIKE ";
static char cct_boot_str_110[] = " ORDER BY id;";
static char cct_boot_str_111[] = "SELECT id, nome, classe, media FROM alunos WHERE classe = ";
static char cct_boot_str_112[] = "SELECT COUNT(*) FROM alunos;";
static char cct_boot_str_113[] = "SELECT COUNT(*) FROM alunos WHERE id = ";
static char cct_boot_str_114[] = "INSERT INTO alunos(nome, classe, media) VALUES(?1, ?2, ?3);";
static char cct_boot_str_115[] = "UPDATE alunos SET media = ?1 WHERE id = ?2;";
static char cct_boot_str_116[] = "DELETE FROM alunos WHERE id = ?1;";
static char cct_boot_str_117[] = " nao pode ser vazio";
static char cct_boot_str_118[] = "media invalida";
static char cct_boot_str_119[] = "media deve estar entre 0.0 e 10.0";
static char cct_boot_str_120[] = "id invalido";
static char cct_boot_str_121[] = "id deve ser positivo";
static char cct_boot_str_122[] = "nome";
static char cct_boot_str_123[] = "classe";
static char cct_boot_str_124[] = "falha ao cadastrar: ";
static char cct_boot_str_125[] = "ok: aluno cadastrado";
static char cct_boot_str_126[] = "aluno nao encontrado";
static char cct_boot_str_127[] = "falha ao atualizar: ";
static char cct_boot_str_128[] = "ok: media atualizada";
static char cct_boot_str_129[] = "falha ao remover: ";
static char cct_boot_str_130[] = "ok: aluno removido";
static char cct_boot_str_131[] = "erro: ";
static char cct_boot_str_132[] = "-";
static char cct_boot_str_133[] = "ID   | NOME                     | CLASSE       | MEDIA";
static char cct_boot_str_134[] = " | ";
static char cct_boot_str_135[] = "(nenhum registro)";
static char cct_boot_str_136[] = "";
static char cct_boot_str_137[] = "Cadastro SQLite de Alunos";
static char cct_boot_str_138[] = "1 - cadastrar aluno";
static char cct_boot_str_139[] = "2 - listar alunos";
static char cct_boot_str_140[] = "3 - buscar por nome";
static char cct_boot_str_141[] = "4 - listar por classe";
static char cct_boot_str_142[] = "5 - atualizar media";
static char cct_boot_str_143[] = "6 - remover aluno";
static char cct_boot_str_144[] = "7 - mostrar total de alunos";
static char cct_boot_str_145[] = "0 - sair";
static char cct_boot_str_146[] = "nome> ";
static char cct_boot_str_147[] = "classe> ";
static char cct_boot_str_148[] = "media> ";
static char cct_boot_str_149[] = "erro: nome nao pode ser vazio";
static char cct_boot_str_150[] = "erro: classe nao pode ser vazia";
static char cct_boot_str_151[] = "id> ";
static char cct_boot_str_152[] = "nova media> ";
static char cct_boot_str_153[] = "total=";
static char cct_boot_str_154[] = "opcao> ";
static char cct_boot_str_155[] = "1";
static char cct_boot_str_156[] = "2";
static char cct_boot_str_157[] = "3";
static char cct_boot_str_158[] = "4";
static char cct_boot_str_159[] = "5";
static char cct_boot_str_160[] = "6";
static char cct_boot_str_161[] = "7";
static char cct_boot_str_162[] = "0";
static char cct_boot_str_163[] = "erro: opcao invalida";

typedef struct cct_boot_sig_SourceLocation cct_boot_sig_SourceLocation;
typedef struct cct_boot_sig_Aluno cct_boot_sig_Aluno;

typedef enum cct_boot_ord_TokenKind
{
  cct_boot_ord_TokenKind__TK_EOF,
  cct_boot_ord_TokenKind__TK_INVALID,
  cct_boot_ord_TokenKind__TK_IDENTIFIER,
  cct_boot_ord_TokenKind__TK_INTEGER,
  cct_boot_ord_TokenKind__TK_REAL,
  cct_boot_ord_TokenKind__TK_STRING,
  cct_boot_ord_TokenKind__TK_INCIPIT,
  cct_boot_ord_TokenKind__TK_EXPLICIT,
  cct_boot_ord_TokenKind__TK_RITUALE,
  cct_boot_ord_TokenKind__TK_EVOCA,
  cct_boot_ord_TokenKind__TK_VINCIRE,
  cct_boot_ord_TokenKind__TK_DIMITTE,
  cct_boot_ord_TokenKind__TK_CIRCULUS,
  cct_boot_ord_TokenKind__TK_CONIURA,
  cct_boot_ord_TokenKind__TK_CODEX,
  cct_boot_ord_TokenKind__TK_SIGILLUM,
  cct_boot_ord_TokenKind__TK_PACTUM,
  cct_boot_ord_TokenKind__TK_ORDO,
  cct_boot_ord_TokenKind__TK_ARCANUM,
  cct_boot_ord_TokenKind__TK_GENUS,
  cct_boot_ord_TokenKind__TK_ADVOCARE,
  cct_boot_ord_TokenKind__TK_CONSTANS,
  cct_boot_ord_TokenKind__TK_FIN,
  cct_boot_ord_TokenKind__TK_SI,
  cct_boot_ord_TokenKind__TK_ALITER,
  cct_boot_ord_TokenKind__TK_QUANDO,
  cct_boot_ord_TokenKind__TK_CASO,
  cct_boot_ord_TokenKind__TK_SENAO,
  cct_boot_ord_TokenKind__TK_DUM,
  cct_boot_ord_TokenKind__TK_DONEC,
  cct_boot_ord_TokenKind__TK_REPETE,
  cct_boot_ord_TokenKind__TK_ITERUM,
  cct_boot_ord_TokenKind__TK_PRO,
  cct_boot_ord_TokenKind__TK_FRANGE,
  cct_boot_ord_TokenKind__TK_RECEDE,
  cct_boot_ord_TokenKind__TK_REDDE,
  cct_boot_ord_TokenKind__TK_TRANSITUS,
  cct_boot_ord_TokenKind__TK_TEMPTA,
  cct_boot_ord_TokenKind__TK_CAPE,
  cct_boot_ord_TokenKind__TK_SEMPER,
  cct_boot_ord_TokenKind__TK_IACE,
  cct_boot_ord_TokenKind__TK_FRACTUM,
  cct_boot_ord_TokenKind__TK_ET,
  cct_boot_ord_TokenKind__TK_VEL,
  cct_boot_ord_TokenKind__TK_NON,
  cct_boot_ord_TokenKind__TK_ET_BIT,
  cct_boot_ord_TokenKind__TK_VEL_BIT,
  cct_boot_ord_TokenKind__TK_XOR,
  cct_boot_ord_TokenKind__TK_NON_BIT,
  cct_boot_ord_TokenKind__TK_SINISTER,
  cct_boot_ord_TokenKind__TK_DEXTER,
  cct_boot_ord_TokenKind__TK_REX,
  cct_boot_ord_TokenKind__TK_DUX,
  cct_boot_ord_TokenKind__TK_COMES,
  cct_boot_ord_TokenKind__TK_MILES,
  cct_boot_ord_TokenKind__TK_UMBRA,
  cct_boot_ord_TokenKind__TK_FLAMMA,
  cct_boot_ord_TokenKind__TK_VERBUM,
  cct_boot_ord_TokenKind__TK_VERUM,
  cct_boot_ord_TokenKind__TK_FALSUM,
  cct_boot_ord_TokenKind__TK_NIHIL,
  cct_boot_ord_TokenKind__TK_SPECULUM,
  cct_boot_ord_TokenKind__TK_SERIES,
  cct_boot_ord_TokenKind__TK_FLUXUS,
  cct_boot_ord_TokenKind__TK_VOLATILE,
  cct_boot_ord_TokenKind__TK_OBSECRO,
  cct_boot_ord_TokenKind__TK_ANUR,
  cct_boot_ord_TokenKind__TK_MENSURA,
  cct_boot_ord_TokenKind__TK_MOLDE,
  cct_boot_ord_TokenKind__TK_DE,
  cct_boot_ord_TokenKind__TK_AD,
  cct_boot_ord_TokenKind__TK_IN,
  cct_boot_ord_TokenKind__TK_GRADUS,
  cct_boot_ord_TokenKind__TK_PLUS,
  cct_boot_ord_TokenKind__TK_MINUS,
  cct_boot_ord_TokenKind__TK_STAR,
  cct_boot_ord_TokenKind__TK_STAR_STAR,
  cct_boot_ord_TokenKind__TK_SLASH,
  cct_boot_ord_TokenKind__TK_SLASH_SLASH,
  cct_boot_ord_TokenKind__TK_PERCENT,
  cct_boot_ord_TokenKind__TK_PERCENT_PERCENT,
  cct_boot_ord_TokenKind__TK_EQ_EQ,
  cct_boot_ord_TokenKind__TK_BANG_EQ,
  cct_boot_ord_TokenKind__TK_LESS,
  cct_boot_ord_TokenKind__TK_LESS_EQ,
  cct_boot_ord_TokenKind__TK_GREATER,
  cct_boot_ord_TokenKind__TK_GREATER_EQ,
  cct_boot_ord_TokenKind__TK_EQ,
  cct_boot_ord_TokenKind__TK_PLUS_PLUS,
  cct_boot_ord_TokenKind__TK_MINUS_MINUS,
  cct_boot_ord_TokenKind__TK_LPAREN,
  cct_boot_ord_TokenKind__TK_RPAREN,
  cct_boot_ord_TokenKind__TK_LBRACE,
  cct_boot_ord_TokenKind__TK_RBRACE,
  cct_boot_ord_TokenKind__TK_LBRACKET,
  cct_boot_ord_TokenKind__TK_RBRACKET,
  cct_boot_ord_TokenKind__TK_COMMA,
  cct_boot_ord_TokenKind__TK_DOT,
  cct_boot_ord_TokenKind__TK_COLON,
  cct_boot_ord_TokenKind__TK_SEMICOLON,
  cct_boot_ord_TokenKind__TK_QUESTION
} cct_boot_ord_TokenKind;

struct cct_boot_sig_SourceLocation
{
  char* filename;
  long long line;
  long long column;
};

struct cct_boot_sig_Aluno
{
  long long id;
  char* nome;
  char* classe;
  double media;
};

char* cct_boot_rit_token_kind_to_string_0(cct_boot_ord_TokenKind kind);
long long cct_boot_rit_argc_1(void);
char* cct_boot_rit_arg_2(long long i);
void cct_boot_rit_print_3(char* s);
void cct_boot_rit_println_4(char* s);
void cct_boot_rit_eprint_5(char* s);
void cct_boot_rit_eprintln_6(char* s);
void cct_boot_rit_flush_7(void);
void cct_boot_rit_flush_err_8(void);
char cct_boot_rit_read_char_9(void);
char* cct_boot_rit_read_line_10(void);
char* cct_boot_rit_read_line_prompt_11(char* prompt);
char* cct_boot_rit_read_all_stdin_12(void);
int cct_boot_rit_is_tty_13(void);
char* cct_boot_rit_path_join_14(char* a, char* b);
char* cct_boot_rit_path_basename_15(char* p);
char* cct_boot_rit_path_dirname_16(char* p);
char* cct_boot_rit_path_ext_17(char* p);
char* cct_boot_rit_stem_18(char* p);
char* cct_boot_rit_normalize_19(char* p);
int cct_boot_rit_is_absolute_20(char* p);
int cct_boot_rit_is_relative_21(char* p);
char* cct_boot_rit_resolve_22(char* p);
char* cct_boot_rit_relative_to_23(char* path, char* base);
char* cct_boot_rit_with_ext_24(char* p, char* extension);
char* cct_boot_rit_without_ext_25(char* p);
char* cct_boot_rit_parent_26(char* p);
char* cct_boot_rit_home_dir_27(void);
char* cct_boot_rit_temp_dir_28(void);
void* cct_boot_rit_split_path_29(char* p);
long long cct_boot_rit_len_30(char* s);
int cct_boot_rit_char_is_digit_31(char c);
int cct_boot_rit_char_is_alpha_32(char c);
int cct_boot_rit_char_is_alnum_33(char c);
int cct_boot_rit_char_is_whitespace_34(char c);
char cct_boot_rit_char_to_upper_35(char c);
char cct_boot_rit_char_to_lower_36(char c);
char* cct_boot_rit_concat_37(char* a, char* b);
long long cct_boot_rit_compare_38(char* a, char* b);
char* cct_boot_rit_substring_39(char* s, long long inicio, long long fim);
char* cct_boot_rit_verbum_dup_40(char* s);
unsigned long long cct_boot_rit_verbum_hash_fnv1a_41(char* s);
char* cct_boot_rit_trim_42(char* s);
long long cct_boot_rit_find_43(char* s, char* sub);
char cct_boot_rit_char_at_44(char* s, long long i);
char* cct_boot_rit_from_char_45(char c);
int cct_boot_rit_contains_46(char* s, char* sub);
int cct_boot_rit_starts_with_47(char* s, char* prefix);
int cct_boot_rit_ends_with_48(char* s, char* suffix);
char* cct_boot_rit_strip_prefix_49(char* s, char* prefix);
char* cct_boot_rit_strip_suffix_50(char* s, char* suffix);
char* cct_boot_rit_replace_51(char* s, char* de, char* para);
char* cct_boot_rit_replace_all_52(char* s, char* de, char* para);
char* cct_boot_rit_to_upper_53(char* s);
char* cct_boot_rit_to_lower_54(char* s);
char* cct_boot_rit_trim_left_55(char* s);
char* cct_boot_rit_trim_right_56(char* s);
char* cct_boot_rit_trim_char_57(char* s, char c);
char* cct_boot_rit_repeat_58(char* s, long long n);
char* cct_boot_rit_pad_left_59(char* s, long long width, char fill);
char* cct_boot_rit_pad_right_60(char* s, long long width, char fill);
char* cct_boot_rit_center_61(char* s, long long width, char fill);
long long cct_boot_rit_last_find_62(char* s, char* sub);
long long cct_boot_rit_find_from_63(char* s, char* sub, long long offset);
long long cct_boot_rit_count_occurrences_64(char* s, char* sub);
char* cct_boot_rit_reverse_65(char* s);
int cct_boot_rit_is_empty_66(char* s);
int cct_boot_rit_equals_ignore_case_67(char* a, char* b);
char* cct_boot_rit_slice_68(char* s, long long inicio, long long comprimento);
int cct_boot_rit_is_ascii_69(char* s);
void* cct_boot_rit_split_70(char* s, char* sep);
void* cct_boot_rit_split_char_71(char* s, char c);
char* cct_boot_rit_join_72(void* parts, char* sep);
void* cct_boot_rit_lines_73(char* s);
void* cct_boot_rit_words_74(char* s);
void* cct_boot_rit_builder_init_75(void);
void cct_boot_rit_builder_append_76(void* b, char* s);
void cct_boot_rit_builder_append_char_77(void* b, char c);
void cct_boot_rit_builder_append_int_78(void* b, long long v);
void cct_boot_rit_builder_append_bool_79(void* b, int v);
void cct_boot_rit_builder_append_real_80(void* b, double v);
char* cct_boot_rit_builder_to_verbum_81(void* b);
long long cct_boot_rit_builder_len_82(void* b);
void cct_boot_rit_builder_clear_83(void* b);
void cct_boot_rit_builder_free_84(void* b);
void* cct_boot_rit_writer_init_85(void);
void cct_boot_rit_writer_indent_86(void* w);
void cct_boot_rit_writer_dedent_87(void* w);
void cct_boot_rit_writer_write_88(void* w, char* s);
void cct_boot_rit_writer_writeln_89(void* w, char* s);
void cct_boot_rit_writer_write_int_90(void* w, long long v);
void cct_boot_rit_writer_writeln_int_91(void* w, long long v);
void cct_boot_rit_writer_write_bool_92(void* w, int v);
char* cct_boot_rit_writer_to_verbum_93(void* w);
void cct_boot_rit_writer_free_94(void* w);
char* cct_boot_rit_stringify_int_95(long long n);
char* cct_boot_rit_stringify_real_96(double x);
char* cct_boot_rit_stringify_bool_97(int b);
char* cct_boot_rit_stringify_hex_98(long long n);
char* cct_boot_rit_format_pair_99(char* label, char* value);
char* cct_boot_rit_format_1_100(char* tmpl, char* a);
char* cct_boot_rit_format_2_101(char* tmpl, char* a, char* b);
char* cct_boot_rit_format_3_102(char* tmpl, char* a, char* b, char* c);
char* cct_boot_rit_format_4_103(char* tmpl, char* a, char* b, char* c, char* d);
char* cct_boot_rit_repeat_char_104(char c, long long n);
long long cct_boot_rit_parse_int_105(char* s);
double cct_boot_rit_parse_real_106(char* s);
int cct_boot_rit_parse_bool_107(char* s);
void* cct_boot_rit_try_int_108(char* s);
void* cct_boot_rit_try_real_109(char* s);
void* cct_boot_rit_try_bool_110(char* s);
long long cct_boot_rit_parse_int_hex_111(char* s);
void* cct_boot_rit_try_int_hex_112(char* s);
long long cct_boot_rit_parse_int_radix_113(char* s, long long radix);
void* cct_boot_rit_try_int_radix_114(char* s, long long radix);
void* cct_boot_rit_parse_lines_115(char* s);
void* cct_boot_rit_parse_csv_line_116(char* s);
void* cct_boot_rit_parse_csv_line_sep_117(char* s, char sep);
int cct_boot_rit_is_int_118(char* s);
int cct_boot_rit_is_real_119(char* s);
void cct_boot_rit_diag_error_120(cct_boot_sig_SourceLocation* loc, char* msg);
void cct_boot_rit_diag_warn_121(cct_boot_sig_SourceLocation* loc, char* msg);
char* cct_boot_rit_read_all_122(char* path);
void cct_boot_rit_write_all_123(char* path, char* content);
void cct_boot_rit_append_all_124(char* path, char* content);
void cct_boot_rit_mkdir_125(char* path);
void cct_boot_rit_mkdir_all_126(char* path);
void cct_boot_rit_delete_file_127(char* path);
void cct_boot_rit_delete_dir_128(char* path);
int cct_boot_rit_is_file_129(char* path);
int cct_boot_rit_is_dir_130(char* path);
int cct_boot_rit_exists_131(char* path);
long long cct_boot_rit_size_132(char* path);
void* cct_boot_rit_read_lines_133(char* path);
long long cct_boot_rit_run_134(char* cmd);
char* cct_boot_rit_run_capture_135(char* cmd);
char* cct_boot_rit_run_capture_err_136(char* cmd);
char* cct_boot_rit_run_with_input_137(char* cmd, char* input);
long long cct_boot_rit_run_env_138(char* cmd, void* env_pairs);
long long cct_boot_rit_run_timeout_139(char* cmd, long long timeout_ms);
char* cct_boot_rit_getenv_140(char* name);
int cct_boot_rit_has_env_141(char* name);
char* cct_boot_rit_cwd_142(void);
void* cct_boot_rit_db_open_143(char* path);
void cct_boot_rit_db_close_144(void* db);
void cct_boot_rit_db_exec_145(void* db, char* sql);
char* cct_boot_rit_db_last_error_146(void* db);
void* cct_boot_rit_db_query_147(void* db, char* sql);
int cct_boot_rit_rows_next_148(void* rows);
char* cct_boot_rit_rows_get_text_149(void* rows, long long col);
long long cct_boot_rit_rows_get_int_150(void* rows, long long col);
double cct_boot_rit_rows_get_real_151(void* rows, long long col);
void cct_boot_rit_rows_close_152(void* rows);
void* cct_boot_rit_db_prepare_153(void* db, char* sql);
void cct_boot_rit_stmt_bind_text_154(void* stmt, long long idx, char* v);
void cct_boot_rit_stmt_bind_int_155(void* stmt, long long idx, long long v);
void cct_boot_rit_stmt_bind_real_156(void* stmt, long long idx, double v);
int cct_boot_rit_stmt_step_157(void* stmt);
void cct_boot_rit_stmt_reset_158(void* stmt);
void cct_boot_rit_stmt_finalize_159(void* stmt);
void cct_boot_rit_db_begin_160(void* db);
void cct_boot_rit_db_commit_161(void* db);
void cct_boot_rit_db_rollback_162(void* db);
long long cct_boot_rit_db_scalar_int_163(void* db, char* sql);
char* cct_boot_rit_db_scalar_text_164(void* db, char* sql);
long long* cct_boot_rit_alloc_165(long long tamanho);
void cct_boot_rit_free_166(long long* ptr);
long long* cct_boot_rit_realloc_167(long long* ptr, long long novo_tamanho);
void cct_boot_rit_copy_168(long long* dest, long long* src, long long tamanho);
void cct_boot_rit_set_169(long long* ptr, long long valor, long long tamanho);
void cct_boot_rit_zero_170(long long* ptr, long long tamanho);
long long cct_boot_rit_mem_compare_171(long long* a, long long* b, long long tamanho);
void* cct_boot_rit_fluxus_init_172(long long elem_size);
void cct_boot_rit_fluxus_free_173(void* flux);
void cct_boot_rit_fluxus_push_174(void* flux, void* elem);
void cct_boot_rit_fluxus_pop_175(void* flux, void* out);
long long cct_boot_rit_fluxus_len_176(void* flux);
void* cct_boot_rit_fluxus_get_177(void* flux, long long idx);
void cct_boot_rit_fluxus_clear_178(void* flux);
void cct_boot_rit_fluxus_reserve_179(void* flux, long long cap);
long long cct_boot_rit_fluxus_capacity_180(void* flux);
void* cct_boot_rit_fluxus_peek_181(void* flux);
void cct_boot_rit_fluxus_set_182(void* flux, long long idx, void* elem);
void cct_boot_rit_fluxus_remove_183(void* flux, long long idx);
void cct_boot_rit_fluxus_insert_184(void* flux, long long idx, void* elem);
int cct_boot_rit_fluxus_contains_185(void* flux, void* elem);
int cct_boot_rit_fluxus_is_empty_186(void* flux);
void cct_boot_rit_fluxus_reverse_187(void* flux);
void cct_boot_rit_fluxus_sort_int_188(void* flux);
void cct_boot_rit_fluxus_sort_verbum_189(void* flux);
void* cct_boot_rit_fluxus_to_ptr_190(void* flux);
double cct_boot_rit_sqrt_real_191(double x);
double cct_boot_rit_cbrt_real_192(double x);
double cct_boot_rit_pow_real_193(double base, double exp);
double cct_boot_rit_abs_real_194(double x);
long long cct_boot_rit_floor_real_195(double x);
long long cct_boot_rit_ceil_real_196(double x);
long long cct_boot_rit_round_real_197(double x);
double cct_boot_rit_sin_real_198(double x);
double cct_boot_rit_cos_real_199(double x);
double cct_boot_rit_tan_real_200(double x);
double cct_boot_rit_log_real_201(double x);
double cct_boot_rit_exp_real_202(double x);
char* cct_boot_rit_aluno_data_dir_203(void);
char* cct_boot_rit_aluno_db_path_204(void);
void cct_boot_rit_aluno_ensure_storage_205(void);
void cct_boot_rit_aluno_reset_default_db_206(void);
char* cct_boot_rit_sql_quote_text_207(char* value);
void* cct_boot_rit_aluno_open_default_208(void);
void cct_boot_rit_aluno_init_schema_209(void* db);
cct_boot_sig_Aluno cct_boot_rit_aluno_from_rows_210(void* rows);
void* cct_boot_rit_aluno_query_all_211(void* db);
void* cct_boot_rit_aluno_query_by_nome_212(void* db, char* termo);
void* cct_boot_rit_aluno_query_by_classe_213(void* db, char* classe);
long long cct_boot_rit_aluno_count_214(void* db);
int cct_boot_rit_aluno_exists_id_215(void* db, long long id);
int cct_boot_rit_aluno_insert_216(void* db, char* nome, char* classe, double media);
int cct_boot_rit_aluno_update_media_217(void* db, long long id, double media);
int cct_boot_rit_aluno_delete_218(void* db, long long id);
void* cct_boot_rit_validar_texto_obrigatorio_219(char* campo, char* bruto);
void* cct_boot_rit_validar_media_220(char* bruto);
void* cct_boot_rit_validar_id_221(char* bruto);
void* cct_boot_rit_app_cadastrar_222(void* db, char* nome_txt, char* classe_txt, char* media_txt);
void* cct_boot_rit_app_atualizar_media_223(void* db, char* id_txt, char* media_txt);
void* cct_boot_rit_app_remover_224(void* db, char* id_txt);
void cct_boot_rit_ui_print_result_message_225(void* res);
void cct_boot_rit_ui_print_separator_226(void);
void cct_boot_rit_ui_print_header_227(void);
void cct_boot_rit_ui_print_aluno_228(cct_boot_sig_Aluno aluno);
long long cct_boot_rit_ui_print_rows_229(void* rows);
void cct_boot_rit_ui_show_menu_230(void);
void cct_boot_rit_ui_handle_cadastrar_231(void* db);
void cct_boot_rit_ui_handle_listar_232(void* db);
void cct_boot_rit_ui_handle_busca_nome_233(void* db);
void cct_boot_rit_ui_handle_listar_classe_234(void* db);
void cct_boot_rit_ui_handle_atualizar_media_235(void* db);
void cct_boot_rit_ui_handle_remover_236(void* db);
void cct_boot_rit_ui_handle_total_237(void* db);
void cct_boot_rit_ui_run_238(void* db);
long long cct_boot_rit_main_239(void);
void* cct_boot_rit_Err__VERBUM__VERBUM(char* error);
void* cct_boot_rit_Ok__VERBUM__VERBUM(char* value);
int cct_boot_rit_option_is_some__UMBRA(void* opt);
void cct_boot_rit_option_free__UMBRA(void* opt);
void* cct_boot_rit_Err__UMBRA__VERBUM(char* error);
double cct_boot_rit_option_unwrap__UMBRA(void* opt);
void* cct_boot_rit_Ok__UMBRA__VERBUM(double value);
int cct_boot_rit_option_is_some__REX(void* opt);
void cct_boot_rit_option_free__REX(void* opt);
void* cct_boot_rit_Err__REX__VERBUM(char* error);
long long cct_boot_rit_option_unwrap__REX(void* opt);
void* cct_boot_rit_Ok__REX__VERBUM(long long value);
int cct_boot_rit_result_is_err__VERBUM__VERBUM(void* res);
char* cct_boot_rit_result_unwrap__VERBUM__VERBUM(void* res);
void cct_boot_rit_result_free__VERBUM__VERBUM(void* res);
int cct_boot_rit_result_is_err__UMBRA__VERBUM(void* res);
char* cct_boot_rit_result_unwrap_err__UMBRA__VERBUM(void* res);
void cct_boot_rit_result_free__UMBRA__VERBUM(void* res);
double cct_boot_rit_result_unwrap__UMBRA__VERBUM(void* res);
int cct_boot_rit_result_is_err__REX__VERBUM(void* res);
char* cct_boot_rit_result_unwrap_err__REX__VERBUM(void* res);
void cct_boot_rit_result_free__REX__VERBUM(void* res);
long long cct_boot_rit_result_unwrap__REX__VERBUM(void* res);
int cct_boot_rit_result_is_ok__VERBUM__VERBUM(void* res);
char* cct_boot_rit_result_unwrap_err__VERBUM__VERBUM(void* res);

char* cct_boot_rit_token_kind_to_string_0(cct_boot_ord_TokenKind kind)
{
  if (kind == cct_boot_ord_TokenKind__TK_EOF)
  {
    return cct_boot_str_0;
  }
  if (kind == cct_boot_ord_TokenKind__TK_INVALID)
  {
    return cct_boot_str_1;
  }
  if (kind == cct_boot_ord_TokenKind__TK_IDENTIFIER)
  {
    return cct_boot_str_2;
  }
  if (kind == cct_boot_ord_TokenKind__TK_INTEGER)
  {
    return cct_boot_str_3;
  }
  if (kind == cct_boot_ord_TokenKind__TK_REAL)
  {
    return cct_boot_str_4;
  }
  if (kind == cct_boot_ord_TokenKind__TK_STRING)
  {
    return cct_boot_str_5;
  }
  if (kind == cct_boot_ord_TokenKind__TK_INCIPIT)
  {
    return cct_boot_str_6;
  }
  if (kind == cct_boot_ord_TokenKind__TK_EXPLICIT)
  {
    return cct_boot_str_7;
  }
  if (kind == cct_boot_ord_TokenKind__TK_RITUALE)
  {
    return cct_boot_str_8;
  }
  if (kind == cct_boot_ord_TokenKind__TK_EVOCA)
  {
    return cct_boot_str_9;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VINCIRE)
  {
    return cct_boot_str_10;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DIMITTE)
  {
    return cct_boot_str_11;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CIRCULUS)
  {
    return cct_boot_str_12;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CONIURA)
  {
    return cct_boot_str_13;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CODEX)
  {
    return cct_boot_str_14;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SIGILLUM)
  {
    return cct_boot_str_15;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PACTUM)
  {
    return cct_boot_str_16;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ORDO)
  {
    return cct_boot_str_17;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ARCANUM)
  {
    return cct_boot_str_18;
  }
  if (kind == cct_boot_ord_TokenKind__TK_GENUS)
  {
    return cct_boot_str_19;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ADVOCARE)
  {
    return cct_boot_str_20;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CONSTANS)
  {
    return cct_boot_str_21;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FIN)
  {
    return cct_boot_str_22;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SI)
  {
    return cct_boot_str_23;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ALITER)
  {
    return cct_boot_str_24;
  }
  if (kind == cct_boot_ord_TokenKind__TK_QUANDO)
  {
    return cct_boot_str_25;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CASO)
  {
    return cct_boot_str_26;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SENAO)
  {
    return cct_boot_str_27;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DUM)
  {
    return cct_boot_str_28;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DONEC)
  {
    return cct_boot_str_29;
  }
  if (kind == cct_boot_ord_TokenKind__TK_REPETE)
  {
    return cct_boot_str_30;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ITERUM)
  {
    return cct_boot_str_31;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PRO)
  {
    return cct_boot_str_32;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FRANGE)
  {
    return cct_boot_str_33;
  }
  if (kind == cct_boot_ord_TokenKind__TK_RECEDE)
  {
    return cct_boot_str_34;
  }
  if (kind == cct_boot_ord_TokenKind__TK_REDDE)
  {
    return cct_boot_str_35;
  }
  if (kind == cct_boot_ord_TokenKind__TK_TRANSITUS)
  {
    return cct_boot_str_36;
  }
  if (kind == cct_boot_ord_TokenKind__TK_TEMPTA)
  {
    return cct_boot_str_37;
  }
  if (kind == cct_boot_ord_TokenKind__TK_CAPE)
  {
    return cct_boot_str_38;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SEMPER)
  {
    return cct_boot_str_39;
  }
  if (kind == cct_boot_ord_TokenKind__TK_IACE)
  {
    return cct_boot_str_40;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FRACTUM)
  {
    return cct_boot_str_41;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ET)
  {
    return cct_boot_str_42;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VEL)
  {
    return cct_boot_str_43;
  }
  if (kind == cct_boot_ord_TokenKind__TK_NON)
  {
    return cct_boot_str_44;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ET_BIT)
  {
    return cct_boot_str_45;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VEL_BIT)
  {
    return cct_boot_str_46;
  }
  if (kind == cct_boot_ord_TokenKind__TK_XOR)
  {
    return cct_boot_str_47;
  }
  if (kind == cct_boot_ord_TokenKind__TK_NON_BIT)
  {
    return cct_boot_str_48;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SINISTER)
  {
    return cct_boot_str_49;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DEXTER)
  {
    return cct_boot_str_50;
  }
  if (kind == cct_boot_ord_TokenKind__TK_REX)
  {
    return cct_boot_str_51;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DUX)
  {
    return cct_boot_str_52;
  }
  if (kind == cct_boot_ord_TokenKind__TK_COMES)
  {
    return cct_boot_str_53;
  }
  if (kind == cct_boot_ord_TokenKind__TK_MILES)
  {
    return cct_boot_str_54;
  }
  if (kind == cct_boot_ord_TokenKind__TK_UMBRA)
  {
    return cct_boot_str_55;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FLAMMA)
  {
    return cct_boot_str_56;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VERBUM)
  {
    return cct_boot_str_57;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VERUM)
  {
    return cct_boot_str_58;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FALSUM)
  {
    return cct_boot_str_59;
  }
  if (kind == cct_boot_ord_TokenKind__TK_NIHIL)
  {
    return cct_boot_str_60;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SPECULUM)
  {
    return cct_boot_str_61;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SERIES)
  {
    return cct_boot_str_62;
  }
  if (kind == cct_boot_ord_TokenKind__TK_FLUXUS)
  {
    return cct_boot_str_63;
  }
  if (kind == cct_boot_ord_TokenKind__TK_VOLATILE)
  {
    return cct_boot_str_64;
  }
  if (kind == cct_boot_ord_TokenKind__TK_OBSECRO)
  {
    return cct_boot_str_65;
  }
  if (kind == cct_boot_ord_TokenKind__TK_ANUR)
  {
    return cct_boot_str_66;
  }
  if (kind == cct_boot_ord_TokenKind__TK_MENSURA)
  {
    return cct_boot_str_67;
  }
  if (kind == cct_boot_ord_TokenKind__TK_MOLDE)
  {
    return cct_boot_str_68;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DE)
  {
    return cct_boot_str_69;
  }
  if (kind == cct_boot_ord_TokenKind__TK_AD)
  {
    return cct_boot_str_70;
  }
  if (kind == cct_boot_ord_TokenKind__TK_IN)
  {
    return cct_boot_str_71;
  }
  if (kind == cct_boot_ord_TokenKind__TK_GRADUS)
  {
    return cct_boot_str_72;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PLUS)
  {
    return cct_boot_str_73;
  }
  if (kind == cct_boot_ord_TokenKind__TK_MINUS)
  {
    return cct_boot_str_74;
  }
  if (kind == cct_boot_ord_TokenKind__TK_STAR)
  {
    return cct_boot_str_75;
  }
  if (kind == cct_boot_ord_TokenKind__TK_STAR_STAR)
  {
    return cct_boot_str_76;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SLASH)
  {
    return cct_boot_str_77;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SLASH_SLASH)
  {
    return cct_boot_str_78;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PERCENT)
  {
    return cct_boot_str_79;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PERCENT_PERCENT)
  {
    return cct_boot_str_80;
  }
  if (kind == cct_boot_ord_TokenKind__TK_EQ_EQ)
  {
    return cct_boot_str_81;
  }
  if (kind == cct_boot_ord_TokenKind__TK_BANG_EQ)
  {
    return cct_boot_str_82;
  }
  if (kind == cct_boot_ord_TokenKind__TK_LESS)
  {
    return cct_boot_str_83;
  }
  if (kind == cct_boot_ord_TokenKind__TK_LESS_EQ)
  {
    return cct_boot_str_84;
  }
  if (kind == cct_boot_ord_TokenKind__TK_GREATER)
  {
    return cct_boot_str_85;
  }
  if (kind == cct_boot_ord_TokenKind__TK_GREATER_EQ)
  {
    return cct_boot_str_86;
  }
  if (kind == cct_boot_ord_TokenKind__TK_EQ)
  {
    return cct_boot_str_87;
  }
  if (kind == cct_boot_ord_TokenKind__TK_PLUS_PLUS)
  {
    return cct_boot_str_88;
  }
  if (kind == cct_boot_ord_TokenKind__TK_MINUS_MINUS)
  {
    return cct_boot_str_89;
  }
  if (kind == cct_boot_ord_TokenKind__TK_LPAREN)
  {
    return cct_boot_str_90;
  }
  if (kind == cct_boot_ord_TokenKind__TK_RPAREN)
  {
    return cct_boot_str_91;
  }
  if (kind == cct_boot_ord_TokenKind__TK_LBRACE)
  {
    return cct_boot_str_92;
  }
  if (kind == cct_boot_ord_TokenKind__TK_RBRACE)
  {
    return cct_boot_str_93;
  }
  if (kind == cct_boot_ord_TokenKind__TK_LBRACKET)
  {
    return cct_boot_str_94;
  }
  if (kind == cct_boot_ord_TokenKind__TK_RBRACKET)
  {
    return cct_boot_str_95;
  }
  if (kind == cct_boot_ord_TokenKind__TK_COMMA)
  {
    return cct_boot_str_96;
  }
  if (kind == cct_boot_ord_TokenKind__TK_DOT)
  {
    return cct_boot_str_97;
  }
  if (kind == cct_boot_ord_TokenKind__TK_COLON)
  {
    return cct_boot_str_98;
  }
  if (kind == cct_boot_ord_TokenKind__TK_SEMICOLON)
  {
    return cct_boot_str_99;
  }
  if (kind == cct_boot_ord_TokenKind__TK_QUESTION)
  {
    return cct_boot_str_100;
  }
  return cct_boot_str_101;
}

char* cct_boot_rit_aluno_data_dir_203(void)
{
  return cct_boot_str_102;
}

char* cct_boot_rit_aluno_db_path_204(void)
{
  return cct_boot_str_103;
}

void cct_boot_rit_aluno_ensure_storage_205(void)
{
  cct_boot_rit_mkdir_all_126(cct_boot_rit_aluno_data_dir_203());
  return;
}

void cct_boot_rit_aluno_reset_default_db_206(void)
{
  char* path = cct_boot_rit_aluno_db_path_204();
  if (cct_boot_rit_exists_131(path))
  {
    cct_boot_rit_delete_file_127(path);
  }
  return;
}

char* cct_boot_rit_sql_quote_text_207(char* value)
{
  char* escaped = cct_boot_rit_replace_all_52(value, cct_boot_str_104, cct_boot_str_105);
  return cct_boot_rit_concat_37(cct_boot_rit_concat_37(cct_boot_str_104, escaped), cct_boot_str_104);
}

void* cct_boot_rit_aluno_open_default_208(void)
{
  cct_boot_rit_aluno_ensure_storage_205();
  return cct_boot_rit_db_open_143(cct_boot_rit_aluno_db_path_204());
}

void cct_boot_rit_aluno_init_schema_209(void* db)
{
  cct_boot_rit_db_exec_145(db, cct_boot_str_106);
  return;
}

cct_boot_sig_Aluno cct_boot_rit_aluno_from_rows_210(void* rows)
{
  cct_boot_sig_Aluno aluno;
  aluno.id = cct_boot_rit_rows_get_int_150(rows, 0);
  aluno.nome = cct_boot_rit_rows_get_text_149(rows, 1);
  aluno.classe = cct_boot_rit_rows_get_text_149(rows, 2);
  aluno.media = cct_boot_rit_rows_get_real_151(rows, 3);
  return aluno;
}

void* cct_boot_rit_aluno_query_all_211(void* db)
{
  return cct_boot_rit_db_query_147(db, cct_boot_str_107);
}

void* cct_boot_rit_aluno_query_by_nome_212(void* db, char* termo)
{
  char* pattern = cct_boot_rit_concat_37(cct_boot_str_108, termo);
  pattern = cct_boot_rit_concat_37(pattern, cct_boot_str_108);
  char* sql = cct_boot_str_109;
  sql = cct_boot_rit_concat_37(sql, cct_boot_rit_sql_quote_text_207(pattern));
  sql = cct_boot_rit_concat_37(sql, cct_boot_str_110);
  return cct_boot_rit_db_query_147(db, sql);
}

void* cct_boot_rit_aluno_query_by_classe_213(void* db, char* classe)
{
  char* sql = cct_boot_str_111;
  sql = cct_boot_rit_concat_37(sql, cct_boot_rit_sql_quote_text_207(classe));
  sql = cct_boot_rit_concat_37(sql, cct_boot_str_110);
  return cct_boot_rit_db_query_147(db, sql);
}

long long cct_boot_rit_aluno_count_214(void* db)
{
  return cct_boot_rit_db_scalar_int_163(db, cct_boot_str_112);
}

int cct_boot_rit_aluno_exists_id_215(void* db, long long id)
{
  char* sql = cct_boot_rit_concat_37(cct_boot_str_113, cct_boot_rit_stringify_int_95(id));
  return (cct_boot_rit_db_scalar_int_163(db, sql) > 0);
}

int cct_boot_rit_aluno_insert_216(void* db, char* nome, char* classe, double media)
{
  void* stmt = cct_boot_rit_db_prepare_153(db, cct_boot_str_114);
  cct_boot_rit_db_begin_160(db);
  cct_boot_rit_stmt_bind_text_154(stmt, 1, nome);
  cct_boot_rit_stmt_bind_text_154(stmt, 2, classe);
  cct_boot_rit_stmt_bind_real_156(stmt, 3, media);
  if (!cct_boot_rit_stmt_step_157(stmt))
  {
    cct_boot_rit_stmt_finalize_159(stmt);
    cct_boot_rit_db_rollback_162(db);
    return 0;
  }
  cct_boot_rit_stmt_finalize_159(stmt);
  cct_boot_rit_db_commit_161(db);
  return 1;
}

int cct_boot_rit_aluno_update_media_217(void* db, long long id, double media)
{
  void* stmt = cct_boot_rit_db_prepare_153(db, cct_boot_str_115);
  cct_boot_rit_db_begin_160(db);
  cct_boot_rit_stmt_bind_real_156(stmt, 1, media);
  cct_boot_rit_stmt_bind_int_155(stmt, 2, id);
  if (!cct_boot_rit_stmt_step_157(stmt))
  {
    cct_boot_rit_stmt_finalize_159(stmt);
    cct_boot_rit_db_rollback_162(db);
    return 0;
  }
  cct_boot_rit_stmt_finalize_159(stmt);
  cct_boot_rit_db_commit_161(db);
  return 1;
}

int cct_boot_rit_aluno_delete_218(void* db, long long id)
{
  void* stmt = cct_boot_rit_db_prepare_153(db, cct_boot_str_116);
  cct_boot_rit_db_begin_160(db);
  cct_boot_rit_stmt_bind_int_155(stmt, 1, id);
  if (!cct_boot_rit_stmt_step_157(stmt))
  {
    cct_boot_rit_stmt_finalize_159(stmt);
    cct_boot_rit_db_rollback_162(db);
    return 0;
  }
  cct_boot_rit_stmt_finalize_159(stmt);
  cct_boot_rit_db_commit_161(db);
  return 1;
}

void* cct_boot_rit_validar_texto_obrigatorio_219(char* campo, char* bruto)
{
  char* valor = cct_boot_rit_trim_42(bruto);
  if (cct_boot_rit_len_30(valor) == 0)
  {
    char* msg = cct_boot_rit_concat_37(campo, cct_boot_str_117);
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  return cct_boot_rit_Ok__VERBUM__VERBUM(valor);
}

void* cct_boot_rit_validar_media_220(char* bruto)
{
  char* valor = cct_boot_rit_trim_42(bruto);
  void* opt = cct_boot_rit_try_real_109(valor);
  if (!cct_boot_rit_option_is_some__UMBRA(opt))
  {
    cct_boot_rit_option_free__UMBRA(opt);
    return cct_boot_rit_Err__UMBRA__VERBUM(cct_boot_str_118);
  }
  double media = cct_boot_rit_option_unwrap__UMBRA(opt);
  cct_boot_rit_option_free__UMBRA(opt);
  if ((media < 0.0) || (media > 10.0))
  {
    return cct_boot_rit_Err__UMBRA__VERBUM(cct_boot_str_119);
  }
  return cct_boot_rit_Ok__UMBRA__VERBUM(media);
}

void* cct_boot_rit_validar_id_221(char* bruto)
{
  char* valor = cct_boot_rit_trim_42(bruto);
  void* opt = cct_boot_rit_try_int_108(valor);
  if (!cct_boot_rit_option_is_some__REX(opt))
  {
    cct_boot_rit_option_free__REX(opt);
    return cct_boot_rit_Err__REX__VERBUM(cct_boot_str_120);
  }
  long long id = cct_boot_rit_option_unwrap__REX(opt);
  cct_boot_rit_option_free__REX(opt);
  if (id <= 0)
  {
    return cct_boot_rit_Err__REX__VERBUM(cct_boot_str_121);
  }
  return cct_boot_rit_Ok__REX__VERBUM(id);
}

void* cct_boot_rit_app_cadastrar_222(void* db, char* nome_txt, char* classe_txt, char* media_txt)
{
  void* nome_res = cct_boot_rit_validar_texto_obrigatorio_219(cct_boot_str_122, nome_txt);
  if (cct_boot_rit_result_is_err__VERBUM__VERBUM(nome_res))
  {
    return nome_res;
  }
  char* nome = cct_boot_rit_result_unwrap__VERBUM__VERBUM(nome_res);
  cct_boot_rit_result_free__VERBUM__VERBUM(nome_res);
  void* classe_res = cct_boot_rit_validar_texto_obrigatorio_219(cct_boot_str_123, classe_txt);
  if (cct_boot_rit_result_is_err__VERBUM__VERBUM(classe_res))
  {
    return classe_res;
  }
  char* classe = cct_boot_rit_result_unwrap__VERBUM__VERBUM(classe_res);
  cct_boot_rit_result_free__VERBUM__VERBUM(classe_res);
  void* media_res = cct_boot_rit_validar_media_220(media_txt);
  if (cct_boot_rit_result_is_err__UMBRA__VERBUM(media_res))
  {
    char* msg = cct_boot_rit_result_unwrap_err__UMBRA__VERBUM(media_res);
    cct_boot_rit_result_free__UMBRA__VERBUM(media_res);
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  double media = cct_boot_rit_result_unwrap__UMBRA__VERBUM(media_res);
  cct_boot_rit_result_free__UMBRA__VERBUM(media_res);
  if (!cct_boot_rit_aluno_insert_216(db, nome, classe, media))
  {
    char* msg = cct_boot_rit_concat_37(cct_boot_str_124, cct_boot_rit_db_last_error_146(db));
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  return cct_boot_rit_Ok__VERBUM__VERBUM(cct_boot_str_125);
}

void* cct_boot_rit_app_atualizar_media_223(void* db, char* id_txt, char* media_txt)
{
  void* id_res = cct_boot_rit_validar_id_221(id_txt);
  if (cct_boot_rit_result_is_err__REX__VERBUM(id_res))
  {
    char* msg = cct_boot_rit_result_unwrap_err__REX__VERBUM(id_res);
    cct_boot_rit_result_free__REX__VERBUM(id_res);
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  long long id = cct_boot_rit_result_unwrap__REX__VERBUM(id_res);
  cct_boot_rit_result_free__REX__VERBUM(id_res);
  void* media_res = cct_boot_rit_validar_media_220(media_txt);
  if (cct_boot_rit_result_is_err__UMBRA__VERBUM(media_res))
  {
    char* msg = cct_boot_rit_result_unwrap_err__UMBRA__VERBUM(media_res);
    cct_boot_rit_result_free__UMBRA__VERBUM(media_res);
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  double media = cct_boot_rit_result_unwrap__UMBRA__VERBUM(media_res);
  cct_boot_rit_result_free__UMBRA__VERBUM(media_res);
  if (!cct_boot_rit_aluno_exists_id_215(db, id))
  {
    return cct_boot_rit_Err__VERBUM__VERBUM(cct_boot_str_126);
  }
  if (!cct_boot_rit_aluno_update_media_217(db, id, media))
  {
    char* msg = cct_boot_rit_concat_37(cct_boot_str_127, cct_boot_rit_db_last_error_146(db));
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  return cct_boot_rit_Ok__VERBUM__VERBUM(cct_boot_str_128);
}

void* cct_boot_rit_app_remover_224(void* db, char* id_txt)
{
  void* id_res = cct_boot_rit_validar_id_221(id_txt);
  if (cct_boot_rit_result_is_err__REX__VERBUM(id_res))
  {
    char* msg = cct_boot_rit_result_unwrap_err__REX__VERBUM(id_res);
    cct_boot_rit_result_free__REX__VERBUM(id_res);
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  long long id = cct_boot_rit_result_unwrap__REX__VERBUM(id_res);
  cct_boot_rit_result_free__REX__VERBUM(id_res);
  if (!cct_boot_rit_aluno_exists_id_215(db, id))
  {
    return cct_boot_rit_Err__VERBUM__VERBUM(cct_boot_str_126);
  }
  if (!cct_boot_rit_aluno_delete_218(db, id))
  {
    char* msg = cct_boot_rit_concat_37(cct_boot_str_129, cct_boot_rit_db_last_error_146(db));
    return cct_boot_rit_Err__VERBUM__VERBUM(msg);
  }
  return cct_boot_rit_Ok__VERBUM__VERBUM(cct_boot_str_130);
}

void cct_boot_rit_ui_print_result_message_225(void* res)
{
  if (cct_boot_rit_result_is_ok__VERBUM__VERBUM(res))
  {
    cct_boot_rit_println_4(cct_boot_rit_result_unwrap__VERBUM__VERBUM(res));
  }
  else
  {
    cct_boot_rit_println_4(cct_boot_rit_concat_37(cct_boot_str_131, cct_boot_rit_result_unwrap_err__VERBUM__VERBUM(res)));
  }
  cct_boot_rit_result_free__VERBUM__VERBUM(res);
  return;
}

void cct_boot_rit_ui_print_separator_226(void)
{
  cct_boot_rit_println_4(cct_boot_rit_repeat_58(cct_boot_str_132, 64));
  return;
}

void cct_boot_rit_ui_print_header_227(void)
{
  cct_boot_rit_ui_print_separator_226();
  cct_boot_rit_println_4(cct_boot_str_133);
  cct_boot_rit_ui_print_separator_226();
  return;
}

void cct_boot_rit_ui_print_aluno_228(cct_boot_sig_Aluno aluno)
{
  char* id_txt = cct_boot_rit_pad_right_60(cct_boot_rit_stringify_int_95(aluno.id), 4, 32);
  char* nome_txt = cct_boot_rit_pad_right_60(aluno.nome, 24, 32);
  char* classe_txt = cct_boot_rit_pad_right_60(aluno.classe, 12, 32);
  char* media_txt = cct_boot_rit_stringify_real_96(aluno.media);
  char* linha = id_txt;
  linha = cct_boot_rit_concat_37(linha, cct_boot_str_134);
  linha = cct_boot_rit_concat_37(linha, nome_txt);
  linha = cct_boot_rit_concat_37(linha, cct_boot_str_134);
  linha = cct_boot_rit_concat_37(linha, classe_txt);
  linha = cct_boot_rit_concat_37(linha, cct_boot_str_134);
  linha = cct_boot_rit_concat_37(linha, media_txt);
  cct_boot_rit_println_4(linha);
  return;
}

long long cct_boot_rit_ui_print_rows_229(void* rows)
{
  long long total = 0;
  cct_boot_rit_ui_print_header_227();
  while (cct_boot_rit_rows_next_148(rows))
  {
    {
      cct_boot_sig_Aluno aluno = cct_boot_rit_aluno_from_rows_210(rows);
      cct_boot_rit_ui_print_aluno_228(aluno);
      total = (total + 1);
    }
    if (0) goto __cct_label_1;
    __cct_label_1: ;
  }
  if (0) goto __cct_label_0;
  __cct_label_0: ;
  cct_boot_rit_ui_print_separator_226();
  if (total == 0)
  {
    cct_boot_rit_println_4(cct_boot_str_135);
  }
  return total;
}

void cct_boot_rit_ui_show_menu_230(void)
{
  cct_boot_rit_println_4(cct_boot_str_136);
  cct_boot_rit_println_4(cct_boot_str_137);
  cct_boot_rit_println_4(cct_boot_str_138);
  cct_boot_rit_println_4(cct_boot_str_139);
  cct_boot_rit_println_4(cct_boot_str_140);
  cct_boot_rit_println_4(cct_boot_str_141);
  cct_boot_rit_println_4(cct_boot_str_142);
  cct_boot_rit_println_4(cct_boot_str_143);
  cct_boot_rit_println_4(cct_boot_str_144);
  cct_boot_rit_println_4(cct_boot_str_145);
  return;
}

void cct_boot_rit_ui_handle_cadastrar_231(void* db)
{
  char* nome = cct_boot_rit_read_line_prompt_11(cct_boot_str_146);
  char* classe = cct_boot_rit_read_line_prompt_11(cct_boot_str_147);
  char* media = cct_boot_rit_read_line_prompt_11(cct_boot_str_148);
  void* res = cct_boot_rit_app_cadastrar_222(db, nome, classe, media);
  cct_boot_rit_ui_print_result_message_225(res);
  return;
}

void cct_boot_rit_ui_handle_listar_232(void* db)
{
  void* rows = cct_boot_rit_aluno_query_all_211(db);
  cct_boot_rit_ui_print_rows_229(rows);
  cct_boot_rit_rows_close_152(rows);
  return;
}

void cct_boot_rit_ui_handle_busca_nome_233(void* db)
{
  char* termo = cct_boot_rit_trim_42(cct_boot_rit_read_line_prompt_11(cct_boot_str_146));
  if (cct_boot_rit_len_30(termo) == 0)
  {
    cct_boot_rit_println_4(cct_boot_str_149);
    return;
  }
  void* rows = cct_boot_rit_aluno_query_by_nome_212(db, termo);
  cct_boot_rit_ui_print_rows_229(rows);
  cct_boot_rit_rows_close_152(rows);
  return;
}

void cct_boot_rit_ui_handle_listar_classe_234(void* db)
{
  char* classe = cct_boot_rit_trim_42(cct_boot_rit_read_line_prompt_11(cct_boot_str_147));
  if (cct_boot_rit_len_30(classe) == 0)
  {
    cct_boot_rit_println_4(cct_boot_str_150);
    return;
  }
  void* rows = cct_boot_rit_aluno_query_by_classe_213(db, classe);
  cct_boot_rit_ui_print_rows_229(rows);
  cct_boot_rit_rows_close_152(rows);
  return;
}

void cct_boot_rit_ui_handle_atualizar_media_235(void* db)
{
  char* id_txt = cct_boot_rit_read_line_prompt_11(cct_boot_str_151);
  char* media_txt = cct_boot_rit_read_line_prompt_11(cct_boot_str_152);
  void* res = cct_boot_rit_app_atualizar_media_223(db, id_txt, media_txt);
  cct_boot_rit_ui_print_result_message_225(res);
  return;
}

void cct_boot_rit_ui_handle_remover_236(void* db)
{
  char* id_txt = cct_boot_rit_read_line_prompt_11(cct_boot_str_151);
  void* res = cct_boot_rit_app_remover_224(db, id_txt);
  cct_boot_rit_ui_print_result_message_225(res);
  return;
}

void cct_boot_rit_ui_handle_total_237(void* db)
{
  cct_boot_rit_println_4(cct_boot_rit_concat_37(cct_boot_str_153, cct_boot_rit_stringify_int_95(cct_boot_rit_aluno_count_214(db))));
  return;
}

void cct_boot_rit_ui_run_238(void* db)
{
  while (1)
  {
    {
      cct_boot_rit_ui_show_menu_230();
      char* opcao = cct_boot_rit_trim_42(cct_boot_rit_read_line_prompt_11(cct_boot_str_154));
      char* __cct_tmp_0 = opcao;
      if (strcmp(__cct_tmp_0, cct_boot_str_155) == 0)
      {
        cct_boot_rit_ui_handle_cadastrar_231(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_156) == 0)
      {
        cct_boot_rit_ui_handle_listar_232(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_157) == 0)
      {
        cct_boot_rit_ui_handle_busca_nome_233(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_158) == 0)
      {
        cct_boot_rit_ui_handle_listar_classe_234(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_159) == 0)
      {
        cct_boot_rit_ui_handle_atualizar_media_235(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_160) == 0)
      {
        cct_boot_rit_ui_handle_remover_236(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_161) == 0)
      {
        cct_boot_rit_ui_handle_total_237(db);
      }
      else if (strcmp(__cct_tmp_0, cct_boot_str_162) == 0)
      {
        goto __cct_label_2;
      }
      else
      {
        cct_boot_rit_println_4(cct_boot_str_163);
      }
    }
    if (0) goto __cct_label_3;
    __cct_label_3: ;
  }
  if (0) goto __cct_label_2;
  __cct_label_2: ;
  return;
}

long long cct_boot_rit_main_239(void)
{
  void* db = cct_boot_rit_aluno_open_default_208();
  cct_boot_rit_aluno_init_schema_209(db);
  cct_boot_rit_ui_run_238(db);
  cct_boot_rit_db_close_144(db);
  return 0;
}
void* cct_boot_rit_Err__VERBUM__VERBUM(char* error)
{
  return cct_rt_result_err((&error), ((long long)sizeof(char*)), ((long long)sizeof(char*)));
}

void* cct_boot_rit_Ok__VERBUM__VERBUM(char* value)
{
  return cct_rt_result_ok((&value), ((long long)sizeof(char*)), ((long long)sizeof(char*)));
}

int cct_boot_rit_option_is_some__UMBRA(void* opt)
{
  return cct_rt_option_is_some(opt);
}

void cct_boot_rit_option_free__UMBRA(void* opt)
{
  cct_rt_option_free(opt);
  return;
}

void* cct_boot_rit_Err__UMBRA__VERBUM(char* error)
{
  return cct_rt_result_err((&error), ((long long)sizeof(double)), ((long long)sizeof(char*)));
}

double cct_boot_rit_option_unwrap__UMBRA(void* opt)
{
  double* ptr = cct_rt_option_unwrap_ptr(opt);
  return (*ptr);
}

void* cct_boot_rit_Ok__UMBRA__VERBUM(double value)
{
  return cct_rt_result_ok((&value), ((long long)sizeof(double)), ((long long)sizeof(char*)));
}

int cct_boot_rit_option_is_some__REX(void* opt)
{
  return cct_rt_option_is_some(opt);
}

void cct_boot_rit_option_free__REX(void* opt)
{
  cct_rt_option_free(opt);
  return;
}

void* cct_boot_rit_Err__REX__VERBUM(char* error)
{
  return cct_rt_result_err((&error), ((long long)sizeof(long long)), ((long long)sizeof(char*)));
}

long long cct_boot_rit_option_unwrap__REX(void* opt)
{
  long long* ptr = cct_rt_option_unwrap_ptr(opt);
  return (*ptr);
}

void* cct_boot_rit_Ok__REX__VERBUM(long long value)
{
  return cct_rt_result_ok((&value), ((long long)sizeof(long long)), ((long long)sizeof(char*)));
}

int cct_boot_rit_result_is_err__VERBUM__VERBUM(void* res)
{
  return cct_rt_result_is_err(res);
}

char* cct_boot_rit_result_unwrap__VERBUM__VERBUM(void* res)
{
  char** ptr = cct_rt_result_unwrap_ptr(res);
  return (*ptr);
}

void cct_boot_rit_result_free__VERBUM__VERBUM(void* res)
{
  cct_rt_result_free(res);
  return;
}

int cct_boot_rit_result_is_err__UMBRA__VERBUM(void* res)
{
  return cct_rt_result_is_err(res);
}

char* cct_boot_rit_result_unwrap_err__UMBRA__VERBUM(void* res)
{
  char** ptr = cct_rt_result_unwrap_err_ptr(res);
  return (*ptr);
}

void cct_boot_rit_result_free__UMBRA__VERBUM(void* res)
{
  cct_rt_result_free(res);
  return;
}

double cct_boot_rit_result_unwrap__UMBRA__VERBUM(void* res)
{
  double* ptr = cct_rt_result_unwrap_ptr(res);
  return (*ptr);
}

int cct_boot_rit_result_is_err__REX__VERBUM(void* res)
{
  return cct_rt_result_is_err(res);
}

char* cct_boot_rit_result_unwrap_err__REX__VERBUM(void* res)
{
  char** ptr = cct_rt_result_unwrap_err_ptr(res);
  return (*ptr);
}

void cct_boot_rit_result_free__REX__VERBUM(void* res)
{
  cct_rt_result_free(res);
  return;
}

long long cct_boot_rit_result_unwrap__REX__VERBUM(void* res)
{
  long long* ptr = cct_rt_result_unwrap_ptr(res);
  return (*ptr);
}

int cct_boot_rit_result_is_ok__VERBUM__VERBUM(void* res)
{
  return cct_rt_result_is_ok(res);
}

char* cct_boot_rit_result_unwrap_err__VERBUM__VERBUM(void* res)
{
  char** ptr = cct_rt_result_unwrap_err_ptr(res);
  return (*ptr);
}

int main(int argc, char **argv)
{
  cct_rt_args_init(argc, argv);
  return (int)cct_boot_rit_main_239();
}
