/* Generated by CCT (FASE 8D C-hosted backend) */
/* Sections: includes, runtime helpers, string pool, type decls, prototypes, rituals, entry wrapper */
/* backend = c_host */
/* source = "lib/cct/kernel/kernel.cct" */

/* ===== Includes (freestanding) ===== */
#include <stdint.h>
#include <stddef.h>
#include "/Users/eabusato/dev/cct/src/runtime/cct_freestanding_rt.h"

/* ===== Freestanding Runtime Adapters (FASE 16B.1) ===== */
static inline void cct_rt_fail(const char *msg) {
    (void)msg;
    cct_fs_panic();
}

static inline int cct_rt_fractum_is_active(void) {
    return 0;
}

static inline const char *cct_rt_fractum_peek(void) {
    return "";
}

static inline void cct_rt_fractum_clear(void) {
}

static inline void cct_rt_fractum_throw_str(const char *msg) {
    (void)msg;
    cct_fs_panic();
}

static inline void cct_rt_fractum_uncaught_abort(void) {
    cct_fs_panic();
}

static inline void *cct_rt_alloc_bytes(size_t n) {
    (void)n;
    cct_fs_panic();
}

static inline void cct_rt_free_ptr(void *p) {
    (void)p;
    cct_fs_panic();
}

static inline void *cct_rt_check_not_null(void *p, const char *ctx) {
    if (!p) {
        (void)ctx;
        cct_fs_panic();
    }
    return p;
}

static inline void *cct_rt_check_not_null_fractum(void *p, const char *ctx) {
    return cct_rt_check_not_null(p, ctx);
}

static inline void cct_rt_mem_copy(void *dst, const void *src, long long n) {
    if (n < 0) cct_fs_panic();
    cct_fs_memcpy(dst, src, (size_t)n);
}

static inline void cct_rt_mem_set(void *dst, long long val, long long n) {
    if (n < 0) cct_fs_panic();
    cct_fs_memset(dst, (int)(val & 0xFF), (size_t)n);
}

static inline void cct_rt_mem_zero(void *dst, long long n) {
    cct_rt_mem_set(dst, 0LL, n);
}

static inline void *cct_rt_mem_alloc(long long n) {
    (void)n;
    cct_fs_panic();
}

static inline void cct_rt_mem_free(void *p) {
    (void)p;
    cct_fs_panic();
}

static inline void *cct_rt_mem_realloc(void *p, long long n) {
    (void)p;
    (void)n;
    cct_fs_panic();
}

static inline long long cct_rt_mem_compare(const void *a, const void *b, long long n) {
    if (n < 0) cct_fs_panic();
    const unsigned char *pa = (const unsigned char*)a;
    const unsigned char *pb = (const unsigned char*)b;
    for (long long i = 0; i < n; i++) {
        if (pa[i] < pb[i]) return -1LL;
        if (pa[i] > pb[i]) return 1LL;
    }
    return 0LL;
}

static inline void cct_rt_scribe_str(const char *s) {
    (void)s;
    cct_fs_panic();
}

static inline void cct_rt_scribe_int(long long v) {
    (void)v;
    cct_fs_panic();
}

static inline void cct_rt_scribe_bool(long long v) {
    (void)v;
    cct_fs_panic();
}

static inline void cct_rt_scribe_real(double v) {
    (void)v;
    cct_fs_panic();
}

/* ===== Math Runtime Helpers (freestanding subset) ===== */
static inline double cct_pow(double base, double exp) {
    return (double)cct_fs_pow_i32((cct_rex_t)base, (cct_rex_t)exp);
}
static inline long long cct_rt_shl_ll(long long lhs, long long rhs) {
    if (rhs < 0 || rhs >= 64) return 0LL;
    return (long long)(((uint64_t)lhs) << (unsigned int)rhs);
}
static inline long long cct_rt_shr_ll(long long lhs, long long rhs) {
    if (rhs < 0 || rhs >= 64) return 0LL;
    return (long long)(((uint64_t)lhs) >> (unsigned int)rhs);
}
static inline long long cct_floor_div_ll(long long a, long long b) {
    if (b == 0) { cct_fs_panic(); return 0LL; }
    long long q = a / b;
    long long r = a % b;
    if (r != 0 && ((r > 0) != (b > 0))) q -= 1;
    return q;
}
static inline long long cct_euclid_mod_ll(long long a, long long b) {
    if (b == 0) { cct_fs_panic(); return 0LL; }
    long long m = a % b;
    long long bb = (b < 0) ? -b : b;
    if (m < 0) m += bb;
    return m;
}

/* ===== String Pool ===== */
/* ===== Type Declarations ===== */
/* ===== Rituale Prototypes ===== */
__attribute__((used)) static long long cct_fn_kernel_memset(long long * dst, long long valor, long long n);
__attribute__((used)) static long long cct_fn_kernel_memcpy(long long * dst, long long * src, long long n);
__attribute__((used)) static long long cct_fn_kernel_inb(long long porta);
__attribute__((used)) static long long cct_fn_kernel_outb(long long porta, long long valor);
long long cct_fn_kernel_kernel_halt();

/* ===== Generated Rituales ===== */
__attribute__((used)) static long long cct_fn_kernel_memset(long long * dst, long long valor, long long n) {
    cct_svc_memset((void*)(dst), valor, n);
    return 0;
    return 0;
}

__attribute__((used)) static long long cct_fn_kernel_memcpy(long long * dst, long long * src, long long n) {
    cct_svc_memcpy((void*)(dst), (const void*)(src), n);
    return 0;
    return 0;
}

__attribute__((used)) static long long cct_fn_kernel_inb(long long porta) {
    return (cct_svc_inb(porta));
    return 0;
}

__attribute__((used)) static long long cct_fn_kernel_outb(long long porta, long long valor) {
    cct_svc_outb(porta, valor);
    return 0;
    return 0;
}

long long cct_fn_kernel_kernel_halt() {
    cct_svc_halt();
    return 0;
    return 0;
}

/* ===== Freestanding Entry (no host wrapper) ===== */
