/*
 * CCT — Clavicula Turing
 * Codegen Runtime Bridge (FASE 8D)
 *
 * Emits generated-C prelude/runtime helper integration and maps codegen kinds
 * to runtime helper calls. This keeps runtime-related textual emission out of
 * the main codegen orchestration path.
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "codegen_internal.h"
#include "../runtime/runtime.h"

#include <stdio.h>

static void cct_cg_emit_escaped_c_string(FILE *out, const char *s) {
    fputc('"', out);
    if (s) {
        for (const unsigned char *p = (const unsigned char*)s; *p; ++p) {
            switch (*p) {
                case '\\': fputs("\\\\", out); break;
                case '"':  fputs("\\\"", out); break;
                case '\n': fputs("\\n", out); break;
                case '\t': fputs("\\t", out); break;
                case '\r': fputs("\\r", out); break;
                default:
                    if (*p < 32 || *p > 126) fprintf(out, "\\x%02x", *p);
                    else fputc(*p, out);
                    break;
            }
        }
    }
    fputc('"', out);
}

bool cct_cg_emit_generated_c_prelude(FILE *out, const cct_codegen_t *cg) {
    if (!out || !cg) return false;

    fputs("/* Generated by CCT (FASE 8D C-hosted backend) */\n", out);
    fputs("/* Sections: includes, runtime helpers, string pool, type decls, prototypes, rituals, entry wrapper */\n", out);
    fputs("/* backend = c_host */\n", out);
    fputs("/* source = ", out);
    cct_cg_emit_escaped_c_string(out, cg->input_path ? cg->input_path : cg->filename);
    fputs(" */\n\n", out);

    fputs("/* ===== Includes ===== */\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <stdint.h>\n\n", out);
    fputs("#include <string.h>\n", out);
    fputs("#include <ctype.h>\n\n", out);
    fputs("#include <errno.h>\n", out);
    fputs("#include <math.h>\n\n", out);
    fputs("static void cct_rt_fail(const char *msg);\n\n", out);

    fputs("/* ===== Math Runtime Helpers (FASE 13A) ===== */\n", out);
    fputs("static inline double cct_sqrt(double x) { return sqrt(x); }\n", out);
    fputs("static inline double cct_cbrt(double x) { return cbrt(x); }\n", out);
    fputs("static inline double cct_pow(double base, double exp) { return pow(base, exp); }\n", out);
    fputs("static inline double cct_hypot(double x, double y) { return hypot(x, y); }\n", out);
    fputs("static inline double cct_sin(double x) { return sin(x); }\n", out);
    fputs("static inline double cct_cos(double x) { return cos(x); }\n", out);
    fputs("static inline double cct_tan(double x) { return tan(x); }\n", out);
    fputs("static inline double cct_asin(double x) { return asin(x); }\n", out);
    fputs("static inline double cct_acos(double x) { return acos(x); }\n", out);
    fputs("static inline double cct_atan(double x) { return atan(x); }\n", out);
    fputs("static inline double cct_atan2(double y, double x) { return atan2(y, x); }\n", out);
    fputs("static inline double cct_deg_to_rad(double deg) { return deg * (3.141592653589793 / 180.0); }\n", out);
    fputs("static inline double cct_rad_to_deg(double rad) { return rad * (180.0 / 3.141592653589793); }\n", out);
    fputs("static inline double cct_exp(double x) { return exp(x); }\n", out);
    fputs("static inline double cct_log(double x) { return log(x); }\n", out);
    fputs("static inline double cct_log10(double x) { return log10(x); }\n", out);
    fputs("static inline double cct_log2(double x) { return log2(x); }\n\n", out);
    fputs("static inline long long cct_floor_div_ll(long long a, long long b) {\n", out);
    fputs("    if (b == 0) { cct_rt_fail(\"integer division by zero\"); return 0LL; }\n", out);
    fputs("    long long q = a / b;\n", out);
    fputs("    long long r = a % b;\n", out);
    fputs("    if (r != 0 && ((r > 0) != (b > 0))) q -= 1;\n", out);
    fputs("    return q;\n", out);
    fputs("}\n", out);
    fputs("static inline long long cct_euclid_mod_ll(long long a, long long b) {\n", out);
    fputs("    if (b == 0) { cct_rt_fail(\"euclidean modulo by zero\"); return 0LL; }\n", out);
    fputs("    long long m = a % b;\n", out);
    fputs("    long long bb = (b < 0) ? -b : b;\n", out);
    fputs("    if (m < 0) m += bb;\n", out);
    fputs("    return m;\n", out);
    fputs("}\n\n", out);

    fputs("/* ===== Runtime Helpers ===== */\n", out);
    cct_runtime_codegen_config_t rt_cfg;
    cct_runtime_codegen_config_defaults(&rt_cfg);
    if (!cct_runtime_emit_c_helpers(out, &rt_cfg)) return false;
    return true;
}

bool cct_cg_emit_runtime_fail_call(FILE *out, const char *message) {
    if (!out) return false;
    fputs("cct_rt_fail(", out);
    cct_cg_emit_escaped_c_string(out, message ? message : "failure");
    fputs(")", out);
    return true;
}

const char* cct_cg_runtime_scribe_helper_name(cct_codegen_value_kind_t kind) {
    switch (kind) {
        case CCT_CODEGEN_VALUE_STRING: return "cct_rt_scribe_str";
        case CCT_CODEGEN_VALUE_REAL: return "cct_rt_scribe_real";
        case CCT_CODEGEN_VALUE_BOOL: return "cct_rt_scribe_bool";
        case CCT_CODEGEN_VALUE_INT: return "cct_rt_scribe_int";
        default: return NULL;
    }
}

const char* cct_cg_runtime_alloc_helper_name(void) {
    return "cct_rt_alloc_bytes";
}

const char* cct_cg_runtime_free_helper_name(void) {
    return "cct_rt_free_ptr";
}

const char* cct_cg_runtime_check_not_null_helper_name(void) {
    return "cct_rt_check_not_null";
}

const char* cct_cg_runtime_check_not_null_fractum_helper_name(void) {
    return "cct_rt_check_not_null_fractum";
}
