/*
 * CCT — Clavicula Turing
 * Codegen Runtime Bridge (FASE 8D)
 *
 * Emits generated-C prelude/runtime helper integration and maps codegen kinds
 * to runtime helper calls. This keeps runtime-related textual emission out of
 * the main codegen orchestration path.
 *
 * Copyright (c) Erick Andrade Busato. Todos os direitos reservados.
 */

#include "codegen_internal.h"
#include "../runtime/runtime.h"

#include <stdio.h>

#ifndef CCT_FREESTANDING_RT_HEADER
#define CCT_FREESTANDING_RT_HEADER "src/runtime/cct_freestanding_rt.h"
#endif

static void cct_cg_emit_escaped_c_string(FILE *out, const char *s) {
    fputc('"', out);
    if (s) {
        for (const unsigned char *p = (const unsigned char*)s; *p; ++p) {
            switch (*p) {
                case '\\': fputs("\\\\", out); break;
                case '"':  fputs("\\\"", out); break;
                case '\n': fputs("\\n", out); break;
                case '\t': fputs("\\t", out); break;
                case '\r': fputs("\\r", out); break;
                default:
                    if (*p < 32 || *p > 126) fprintf(out, "\\x%02x", *p);
                    else fputc(*p, out);
                    break;
            }
        }
    }
    fputc('"', out);
}

bool cct_cg_emit_generated_c_prelude(FILE *out, const cct_codegen_t *cg) {
    if (!out || !cg) return false;

    fputs("/* Generated by CCT (FASE 8D C-hosted backend) */\n", out);
    fputs("/* Sections: includes, runtime helpers, string pool, type decls, prototypes, rituals, entry wrapper */\n", out);
    fputs("/* backend = c_host */\n", out);
    fputs("/* source = ", out);
    cct_cg_emit_escaped_c_string(out, cg->input_path ? cg->input_path : cg->filename);
    fputs(" */\n\n", out);

    if (cg->profile == CCT_PROFILE_FREESTANDING) {
        fputs("/* ===== Includes (freestanding) ===== */\n", out);
        fputs("#include <stdint.h>\n", out);
        fputs("#include <stddef.h>\n", out);
        fprintf(out, "#include \"%s\"\n\n", CCT_FREESTANDING_RT_HEADER);

        fputs("/* ===== Freestanding Runtime Adapters (FASE 16B.1) ===== */\n", out);
        fputs("static inline void cct_rt_fail(const char *msg) {\n", out);
        fputs("    (void)msg;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline int cct_rt_fractum_is_active(void) {\n", out);
        fputs("    return 0;\n", out);
        fputs("}\n\n", out);
        fputs("static inline const char *cct_rt_fractum_peek(void) {\n", out);
        fputs("    return \"\";\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_fractum_clear(void) {\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_fractum_throw_str(const char *msg) {\n", out);
        fputs("    (void)msg;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_fractum_uncaught_abort(void) {\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline void *cct_rt_alloc_bytes(size_t n) {\n", out);
        fputs("    (void)n;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_free_ptr(void *p) {\n", out);
        fputs("    (void)p;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline void *cct_rt_check_not_null(void *p, const char *ctx) {\n", out);
        fputs("    if (!p) {\n", out);
        fputs("        (void)ctx;\n", out);
        fputs("        cct_fs_panic();\n", out);
        fputs("    }\n", out);
        fputs("    return p;\n", out);
        fputs("}\n\n", out);

        fputs("static inline void *cct_rt_check_not_null_fractum(void *p, const char *ctx) {\n", out);
        fputs("    return cct_rt_check_not_null(p, ctx);\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_mem_copy(void *dst, const void *src, long long n) {\n", out);
        fputs("    if (n < 0) cct_fs_panic();\n", out);
        fputs("    cct_fs_memcpy(dst, src, (size_t)n);\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_mem_set(void *dst, long long val, long long n) {\n", out);
        fputs("    if (n < 0) cct_fs_panic();\n", out);
        fputs("    cct_fs_memset(dst, (int)(val & 0xFF), (size_t)n);\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_mem_zero(void *dst, long long n) {\n", out);
        fputs("    cct_rt_mem_set(dst, 0LL, n);\n", out);
        fputs("}\n\n", out);

        fputs("static inline void *cct_rt_mem_alloc(long long n) {\n", out);
        fputs("    (void)n;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_mem_free(void *p) {\n", out);
        fputs("    (void)p;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline void *cct_rt_mem_realloc(void *p, long long n) {\n", out);
        fputs("    (void)p;\n", out);
        fputs("    (void)n;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("static inline long long cct_rt_mem_compare(const void *a, const void *b, long long n) {\n", out);
        fputs("    if (n < 0) cct_fs_panic();\n", out);
        fputs("    const unsigned char *pa = (const unsigned char*)a;\n", out);
        fputs("    const unsigned char *pb = (const unsigned char*)b;\n", out);
        fputs("    for (long long i = 0; i < n; i++) {\n", out);
        fputs("        if (pa[i] < pb[i]) return -1LL;\n", out);
        fputs("        if (pa[i] > pb[i]) return 1LL;\n", out);
        fputs("    }\n", out);
        fputs("    return 0LL;\n", out);
        fputs("}\n\n", out);

        fputs("static inline void cct_rt_scribe_str(const char *s) {\n", out);
        fputs("    (void)s;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_scribe_int(long long v) {\n", out);
        fputs("    (void)v;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_scribe_bool(long long v) {\n", out);
        fputs("    (void)v;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);
        fputs("static inline void cct_rt_scribe_real(double v) {\n", out);
        fputs("    (void)v;\n", out);
        fputs("    cct_fs_panic();\n", out);
        fputs("}\n\n", out);

        fputs("/* ===== Math Runtime Helpers (freestanding subset) ===== */\n", out);
        fputs("static inline double cct_pow(double base, double exp) {\n", out);
        fputs("    return (double)cct_fs_pow_i32((cct_rex_t)base, (cct_rex_t)exp);\n", out);
        fputs("}\n", out);
        fputs("static inline long long cct_floor_div_ll(long long a, long long b) {\n", out);
        fputs("    if (b == 0) { cct_fs_panic(); return 0LL; }\n", out);
        fputs("    long long q = a / b;\n", out);
        fputs("    long long r = a % b;\n", out);
        fputs("    if (r != 0 && ((r > 0) != (b > 0))) q -= 1;\n", out);
        fputs("    return q;\n", out);
        fputs("}\n", out);
        fputs("static inline long long cct_euclid_mod_ll(long long a, long long b) {\n", out);
        fputs("    if (b == 0) { cct_fs_panic(); return 0LL; }\n", out);
        fputs("    long long m = a % b;\n", out);
        fputs("    long long bb = (b < 0) ? -b : b;\n", out);
        fputs("    if (m < 0) m += bb;\n", out);
        fputs("    return m;\n", out);
        fputs("}\n\n", out);

        return true;
    }

    fputs("/* ===== Includes ===== */\n", out);
    fputs("#ifndef _POSIX_C_SOURCE\n", out);
    fputs("#define _POSIX_C_SOURCE 200809L\n", out);
    fputs("#endif\n", out);
    fputs("#ifndef _XOPEN_SOURCE\n", out);
    fputs("#define _XOPEN_SOURCE 700\n", out);
    fputs("#endif\n", out);
    fputs("#include <stdio.h>\n", out);
    fputs("#include <stdlib.h>\n", out);
    fputs("#include <stdint.h>\n\n", out);
    fputs("#include <string.h>\n", out);
    fputs("#include <ctype.h>\n\n", out);
    fputs("#include <errno.h>\n", out);
    fputs("#include <math.h>\n", out);
    fputs("#include <time.h>\n\n", out);
    fputs("#ifdef _WIN32\n", out);
    fputs("#include <direct.h>\n", out);
    fputs("#include <io.h>\n", out);
    fputs("#include <sys/stat.h>\n", out);
    fputs("#define cct_rt_getcwd _getcwd\n", out);
    fputs("#define cct_rt_mkdir(path) _mkdir(path)\n", out);
    fputs("#define cct_rt_fileno _fileno\n", out);
    fputs("#define cct_rt_isatty _isatty\n", out);
    fputs("#else\n", out);
    fputs("#include <unistd.h>\n", out);
    fputs("#include <dirent.h>\n", out);
    fputs("#include <pwd.h>\n", out);
    fputs("#include <signal.h>\n", out);
    fputs("#include <sys/wait.h>\n", out);
    fputs("#include <sys/stat.h>\n", out);
    fputs("#define cct_rt_getcwd getcwd\n", out);
    fputs("#define cct_rt_mkdir(path) mkdir((path), 0777)\n", out);
    fputs("#define cct_rt_fileno fileno\n", out);
    fputs("#define cct_rt_isatty isatty\n", out);
    fputs("#endif\n\n", out);
    fputs("static void cct_rt_fail(const char *msg);\n\n", out);

    fputs("/* ===== Math Runtime Helpers (FASE 13A) ===== */\n", out);
    fputs("static inline double cct_sqrt(double x) { return sqrt(x); }\n", out);
    fputs("static inline double cct_cbrt(double x) { return cbrt(x); }\n", out);
    fputs("static inline double cct_pow(double base, double exp) { return pow(base, exp); }\n", out);
    fputs("static inline double cct_hypot(double x, double y) { return hypot(x, y); }\n", out);
    fputs("static inline double cct_sin(double x) { return sin(x); }\n", out);
    fputs("static inline double cct_cos(double x) { return cos(x); }\n", out);
    fputs("static inline double cct_tan(double x) { return tan(x); }\n", out);
    fputs("static inline double cct_asin(double x) { return asin(x); }\n", out);
    fputs("static inline double cct_acos(double x) { return acos(x); }\n", out);
    fputs("static inline double cct_atan(double x) { return atan(x); }\n", out);
    fputs("static inline double cct_atan2(double y, double x) { return atan2(y, x); }\n", out);
    fputs("static inline double cct_deg_to_rad(double deg) { return deg * (3.141592653589793 / 180.0); }\n", out);
    fputs("static inline double cct_rad_to_deg(double rad) { return rad * (180.0 / 3.141592653589793); }\n", out);
    fputs("static inline double cct_exp(double x) { return exp(x); }\n", out);
    fputs("static inline double cct_log(double x) { return log(x); }\n", out);
    fputs("static inline double cct_log10(double x) { return log10(x); }\n", out);
    fputs("static inline double cct_log2(double x) { return log2(x); }\n\n", out);
    fputs("static inline long long cct_floor_div_ll(long long a, long long b) {\n", out);
    fputs("    if (b == 0) { cct_rt_fail(\"integer division by zero\"); return 0LL; }\n", out);
    fputs("    long long q = a / b;\n", out);
    fputs("    long long r = a % b;\n", out);
    fputs("    if (r != 0 && ((r > 0) != (b > 0))) q -= 1;\n", out);
    fputs("    return q;\n", out);
    fputs("}\n", out);
    fputs("static inline long long cct_euclid_mod_ll(long long a, long long b) {\n", out);
    fputs("    if (b == 0) { cct_rt_fail(\"euclidean modulo by zero\"); return 0LL; }\n", out);
    fputs("    long long m = a % b;\n", out);
    fputs("    long long bb = (b < 0) ? -b : b;\n", out);
    fputs("    if (m < 0) m += bb;\n", out);
    fputs("    return m;\n", out);
    fputs("}\n\n", out);

    fputs("/* ===== Runtime Helpers ===== */\n", out);
    cct_runtime_codegen_config_t rt_cfg;
    cct_runtime_codegen_config_defaults(&rt_cfg);
    if (!cct_runtime_emit_c_helpers(out, &rt_cfg)) return false;
    return true;
}

bool cct_cg_emit_runtime_fail_call(FILE *out, const char *message) {
    if (!out) return false;
    fputs("cct_rt_fail(", out);
    cct_cg_emit_escaped_c_string(out, message ? message : "failure");
    fputs(")", out);
    return true;
}

const char* cct_cg_runtime_scribe_helper_name(cct_codegen_value_kind_t kind) {
    switch (kind) {
        case CCT_CODEGEN_VALUE_STRING: return "cct_rt_scribe_str";
        case CCT_CODEGEN_VALUE_REAL: return "cct_rt_scribe_real";
        case CCT_CODEGEN_VALUE_BOOL: return "cct_rt_scribe_bool";
        case CCT_CODEGEN_VALUE_INT: return "cct_rt_scribe_int";
        default: return NULL;
    }
}

const char* cct_cg_runtime_alloc_helper_name(void) {
    return "cct_rt_alloc_bytes";
}

const char* cct_cg_runtime_free_helper_name(void) {
    return "cct_rt_free_ptr";
}

const char* cct_cg_runtime_check_not_null_helper_name(void) {
    return "cct_rt_check_not_null";
}

const char* cct_cg_runtime_check_not_null_fractum_helper_name(void) {
    return "cct_rt_check_not_null_fractum";
}
